.TH "/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService/Data Directory Reference" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService/Data Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAssignment\&.cs\fP"
.br
.ti -1c
.RI "file \fBAssignmentHistory\&.cs\fP"
.br
.ti -1c
.RI "file \fBAssignmentItem\&.cs\fP"
.br
.ti -1c
.RI "file \fBDatabase\&.cs\fP"
.br
.ti -1c
.RI "file \fBDocument\&.cs\fP"
.br
.ti -1c
.RI "file \fBEnumerations\&.cs\fP"
.br
.ti -1c
.RI "file \fBExpense\&.cs\fP"
.br
.ti -1c
.RI "file \fBExpensePhoto\&.cs\fP"
.br
.ti -1c
.RI "file \fBItem\&.cs\fP"
.br
.ti -1c
.RI "file \fBLabor\&.cs\fP"
.br
.ti -1c
.RI "file \fBPhoto\&.cs\fP"
.br
.ti -1c
.RI "file \fBPropertyChangedBase\&.cs\fP"
.br
.ti -1c
.RI "file \fBSampleAssignmentService\&.cs\fP"
.br
.ti -1c
.RI "file \fBSampleLoginService\&.cs\fP"
.br
.ti -1c
.RI "file \fBSignature\&.cs\fP"
.br
.ti -1c
.RI "file \fBTestData\&.cs\fP"
.br
.ti -1c
.RI "file \fBTimerEntry\&.cs\fP"
.br
.in -1c
