.TH "/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.Android/obj/Debug/android/src/fieldservice/android Directory Reference" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.Android/obj/Debug/android/src/fieldservice/android Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBactivities\fP"
.br
.ti -1c
.RI "directory \fBadapters\fP"
.br
.ti -1c
.RI "directory \fBdialogs\fP"
.br
.ti -1c
.RI "directory \fBfragments\fP"
.br
.ti -1c
.RI "directory \fButilities\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBApplication\&.java\fP"
.br
.ti -1c
.RI "file \fBAssignmentsActivity\&.java\fP"
.br
.ti -1c
.RI "file \fBAssignmentsAdapter\&.java\fP"
.br
.ti -1c
.RI "file \fBAssignmentTabActivity\&.java\fP"
.br
.ti -1c
.RI "file \fBAssignmentTabActivity_MapDataWrapper\&.java\fP"
.br
.ti -1c
.RI "file \fBBaseActivity\&.java\fP"
.br
.ti -1c
.RI "file \fBBaseMapActivity\&.java\fP"
.br
.ti -1c
.RI "file \fBExpensesAdapter\&.java\fP"
.br
.ti -1c
.RI "file \fBItemsAdapter\&.java\fP"
.br
.ti -1c
.RI "file \fBItemsSearchAdapter\&.java\fP"
.br
.ti -1c
.RI "file \fBLaborHoursAdapter\&.java\fP"
.br
.ti -1c
.RI "file \fBLaborTypeSpinnerAdapter\&.java\fP"
.br
.ti -1c
.RI "file \fBLoginActivity\&.java\fP"
.br
.ti -1c
.RI "file \fBMapFragmentActivity\&.java\fP"
.br
.ti -1c
.RI "file \fBMapViewActivity\&.java\fP"
.br
.ti -1c
.RI "file \fBNavigationAdapter\&.java\fP"
.br
.ti -1c
.RI "file \fBPhotosAdapter\&.java\fP"
.br
.ti -1c
.RI "file \fBR\&.java\fP"
.br
.ti -1c
.RI "file \fBSpinnerAdapter_1\&.java\fP"
.br
.ti -1c
.RI "file \fBSummaryActivity\&.java\fP"
.br
.in -1c
