.TH "/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService Directory Reference" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBComponents\fP"
.br
.ti -1c
.RI "directory \fBDependencies\fP"
.br
.ti -1c
.RI "directory \fBFieldService\fP"
.br
.ti -1c
.RI "directory \fBFieldService\&.Android\fP"
.br
.ti -1c
.RI "directory \fBFieldService\&.iOS\fP"
.br
.ti -1c
.RI "directory \fBFieldService\&.Tests\fP"
.br
.ti -1c
.RI "directory \fBFieldService\&.WinRT\fP"
.br
.in -1c
