.TH "/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.Android/Fragments Directory Reference" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.Android/Fragments Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBConfirmationFragment\&.cs\fP"
.br
.ti -1c
.RI "file \fBDocumentFragment\&.cs\fP"
.br
.ti -1c
.RI "file \fBExpenseFragment\&.cs\fP"
.br
.ti -1c
.RI "file \fBHistoryFragment\&.cs\fP"
.br
.ti -1c
.RI "file \fBItemFragment\&.cs\fP"
.br
.ti -1c
.RI "file \fBLaborHourFragment\&.cs\fP"
.br
.ti -1c
.RI "file \fBMapFragment\&.cs\fP"
.br
.ti -1c
.RI "file \fBNavigationFragment\&.cs\fP"
.br
.ti -1c
.RI "file \fBSummaryFragment\&.cs\fP"
.br
.in -1c
