.TH "/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.Android/Dialogs Directory Reference" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.Android/Dialogs Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAddLaborDialog\&.cs\fP"
.br
.ti -1c
.RI "file \fBBaseDialog\&.cs\fP"
.br
.ti -1c
.RI "file \fBExpenseDialog\&.cs\fP"
.br
.ti -1c
.RI "file \fBItemsDialog\&.cs\fP"
.br
.ti -1c
.RI "file \fBPhotoDialog\&.cs\fP"
.br
.ti -1c
.RI "file \fBSignatureDialog\&.cs\fP"
.br
.in -1c
