.TH "/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.iOS/Views Directory Reference" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.iOS/Views Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAssignmentCell\&.cs\fP"
.br
.ti -1c
.RI "file \fBAssignmentCell\&.designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBAssignmentItemCell\&.cs\fP"
.br
.ti -1c
.RI "file \fBAssignmentItemCell\&.designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBAssignmentStatusSheet\&.cs\fP"
.br
.ti -1c
.RI "file \fBCompleteCell\&.cs\fP"
.br
.ti -1c
.RI "file \fBCompleteCell\&.designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBDocumentCell\&.cs\fP"
.br
.ti -1c
.RI "file \fBExpenseCategorySheet\&.cs\fP"
.br
.ti -1c
.RI "file \fBExpenseCell\&.cs\fP"
.br
.ti -1c
.RI "file \fBExpenseCell\&.designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBHistoryCell\&.cs\fP"
.br
.ti -1c
.RI "file \fBHistoryCell\&.designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBHoursField\&.cs\fP"
.br
.ti -1c
.RI "file \fBLaborCell\&.cs\fP"
.br
.ti -1c
.RI "file \fBLaborCell\&.designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBLaborTypeTextField\&.cs\fP"
.br
.ti -1c
.RI "file \fBPhotoAlertSheet\&.cs\fP"
.br
.ti -1c
.RI "file \fBPhotoCell\&.cs\fP"
.br
.ti -1c
.RI "file \fBPhotoCell\&.designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlaceholderTextView\&.cs\fP"
.br
.ti -1c
.RI "file \fBSignatureCell\&.cs\fP"
.br
.ti -1c
.RI "file \fBSignatureCell\&.designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBStatusButton\&.cs\fP"
.br
.ti -1c
.RI "file \fBStatusButton\&.designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextButton\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextButton\&.designer\&.cs\fP"
.br
.in -1c
