.TH "/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.Android/Adapters Directory Reference" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.Android/Adapters Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAssignmentsAdapter\&.cs\fP"
.br
.ti -1c
.RI "file \fBDocumentsAdapter\&.cs\fP"
.br
.ti -1c
.RI "file \fBExpensesAdapter\&.cs\fP"
.br
.ti -1c
.RI "file \fBHistoryListAdapter\&.cs\fP"
.br
.ti -1c
.RI "file \fBItemsAdapter\&.cs\fP"
.br
.ti -1c
.RI "file \fBItemsSearchAdapter\&.cs\fP"
.br
.ti -1c
.RI "file \fBLaborHoursAdapter\&.cs\fP"
.br
.ti -1c
.RI "file \fBLaborTypeSpinnerAdapter\&.cs\fP"
.br
.ti -1c
.RI "file \fBNavigationAdapter\&.cs\fP"
.br
.ti -1c
.RI "file \fBPhotosAdapter\&.cs\fP"
.br
.ti -1c
.RI "file \fBSpinnerAdapter\&.cs\fP"
.br
.in -1c
