.TH "/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.WinRT/Utilities Directory Reference" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.WinRT/Utilities Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBooleanToVisibilityConverter\&.cs\fP"
.br
.ti -1c
.RI "file \fBConstants\&.cs\fP"
.br
.ti -1c
.RI "file \fBDelegateCommand\&.cs\fP"
.br
.ti -1c
.RI "file \fBDocumentSubheaderColorConverter\&.cs\fP"
.br
.ti -1c
.RI "file \fBDocumentTypeToColorConverter\&.cs\fP"
.br
.ti -1c
.RI "file \fBHelpers\&.cs\fP"
.br
.ti -1c
.RI "file \fBPhotoToImageConverter\&.cs\fP"
.br
.ti -1c
.RI "file \fBStatusToColorConverter\&.cs\fP"
.br
.ti -1c
.RI "file \fBTimer\&.cs\fP"
.br
.in -1c
