.TH "/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.iOS/Utilities Directory Reference" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.iOS/Utilities Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBClrWrapper\&.cs\fP"
.br
.ti -1c
.RI "file \fBISearchSource\&.cs\fP"
.br
.ti -1c
.RI "file \fBMenuEventArgs\&.cs\fP"
.br
.ti -1c
.RI "file \fBSearchDisplay\&.cs\fP"
.br
.ti -1c
.RI "file \fBSectionIndex\&.cs\fP"
.br
.ti -1c
.RI "file \fBSynchronizeInvoke\&.cs\fP"
.br
.ti -1c
.RI "file \fBTheme\&.cs\fP"
.br
.ti -1c
.RI "file \fBUIKitExtensions\&.cs\fP"
.br
.in -1c
