.TH "/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.Android/obj/Debug/android/src/fieldservice/android/fragments Directory Reference" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.Android/obj/Debug/android/src/fieldservice/android/fragments Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBConfirmationFragment\&.java\fP"
.br
.ti -1c
.RI "file \fBDocumentFragment\&.java\fP"
.br
.ti -1c
.RI "file \fBExpenseFragment\&.java\fP"
.br
.ti -1c
.RI "file \fBHistoryFragment\&.java\fP"
.br
.ti -1c
.RI "file \fBHistoryFragment_TabContent\&.java\fP"
.br
.ti -1c
.RI "file \fBItemFragment\&.java\fP"
.br
.ti -1c
.RI "file \fBLaborHourFragment\&.java\fP"
.br
.ti -1c
.RI "file \fBMapFragment\&.java\fP"
.br
.ti -1c
.RI "file \fBNavigationFragment\&.java\fP"
.br
.ti -1c
.RI "file \fBNavigationFragment_NavigationItemSelectorListener\&.java\fP"
.br
.ti -1c
.RI "file \fBSummaryFragment\&.java\fP"
.br
.in -1c
