.TH "/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/Components/sqlite-net-1.0.1/samples/SQLite.iOS.Sample Directory Reference" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/Components/sqlite-net-1.0.1/samples/SQLite.iOS.Sample Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBProperties\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAppDelegate\&.cs\fP"
.br
.ti -1c
.RI "file \fBList\&.cs\fP"
.br
.ti -1c
.RI "file \fBListItem\&.cs\fP"
.br
.ti -1c
.RI "file \fBMain\&.cs\fP"
.br
.ti -1c
.RI "file \fBTaskListsViewController\&.cs\fP"
.br
.ti -1c
.RI "file \fBTasksViewController\&.cs\fP"
.br
.in -1c
