.TH "/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.iOS/AppDelegate.cs" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.iOS/AppDelegate.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFieldService\&.iOS\&.AppDelegate\fP"
.br
.RI "\fI\fBAppDelegate\fP, the main callback for application-level events in \fBiOS\fP \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBFieldService\&.iOS\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
