.TH "ContactsSample.Resource.Id" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContactsSample.Resource.Id \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBfull_name\fP = 2131034112"
.br
.ti -1c
.RI "const int \fBmobile_phone\fP = 2131034113"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const int ContactsSample\&.Resource\&.Id\&.full_name = 2131034112"

.SS "const int ContactsSample\&.Resource\&.Id\&.mobile_phone = 2131034113"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
