.TH "ContactsSample.Resource.Layout" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContactsSample.Resource.Layout \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBcontact_view\fP = 2130903040"
.br
.ti -1c
.RI "const int \fBlist_item\fP = 2130903041"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const int ContactsSample\&.Resource\&.Layout\&.contact_view = 2130903040"

.SS "const int ContactsSample\&.Resource\&.Layout\&.list_item = 2130903041"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
