.TH "ContactsSample.DetailContactView" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContactsSample.DetailContactView \- 
.PP
Detail contact view\&. This view displays the details of a contact\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UIViewController\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDetailContactView\fP (Contact c)"
.br
.ti -1c
.RI "override void \fBViewDidLoad\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Detail contact view\&. This view displays the details of a contact\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "ContactsSample\&.DetailContactView\&.DetailContactView (Contactc)"

.SH "Member Function Documentation"
.PP 
.SS "override void ContactsSample\&.DetailContactView\&.ViewDidLoad ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
