.TH "ContactsSample.MainActivity" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContactsSample.MainActivity \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ListActivity\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly AddressBook \fBAddressBook\fP = new AddressBook (Application\&.Context) { PreferContactAggregation = true }"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCreate\fP (Bundle bundle)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void ContactsSample\&.MainActivity\&.OnCreate (Bundlebundle)\fC [protected]\fP"

.SH "Member Data Documentation"
.PP 
.SS "readonly AddressBook ContactsSample\&.MainActivity\&.AddressBook = new AddressBook (Application\&.Context) { PreferContactAggregation = true }\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
