.TH "ContactsSample.MainPageViewModel" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContactsSample.MainPageViewModel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits INotifyPropertyChanged\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainPageViewModel\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBShowProgress\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "IEnumerable< \fBContact\fP > \fBContacts\fP\fC [get]\fP"
.br
.ti -1c
.RI "BitmapImage \fBThumbnail\fP\fC [get]\fP"
.br
.ti -1c
.RI "Contact \fBContact\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler \fBSelectedContact\fP"
.br
.ti -1c
.RI "PropertyChangedEventHandler \fBPropertyChanged\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ContactsSample\&.MainPageViewModel\&.MainPageViewModel ()"

.SH "Property Documentation"
.PP 
.SS "Contact ContactsSample\&.MainPageViewModel\&.Contact\fC [get]\fP, \fC [set]\fP"

.SS "IEnumerable<\fBContact\fP> ContactsSample\&.MainPageViewModel\&.Contacts\fC [get]\fP"

.SS "bool ContactsSample\&.MainPageViewModel\&.ShowProgress\fC [get]\fP, \fC [set]\fP"

.SS "BitmapImage ContactsSample\&.MainPageViewModel\&.Thumbnail\fC [get]\fP"

.SH "Event Documentation"
.PP 
.SS "PropertyChangedEventHandler ContactsSample\&.MainPageViewModel\&.PropertyChanged"

.SS "EventHandler ContactsSample\&.MainPageViewModel\&.SelectedContact"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
