.TH "ContactsSample.Resource.String" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContactsSample.Resource.String \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBApplicationName\fP = 2130968577"
.br
.ti -1c
.RI "const int \fBHello\fP = 2130968576"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const int ContactsSample\&.Resource\&.String\&.ApplicationName = 2130968577"

.SS "const int ContactsSample\&.Resource\&.String\&.Hello = 2130968576"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
