.TH "ContactsSample.AppDelegate" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContactsSample.AppDelegate \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIApplicationDelegate\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBFinishedLaunching\fP (UIApplication app, NSDictionary options)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override bool ContactsSample\&.AppDelegate\&.FinishedLaunching (UIApplicationapp, NSDictionaryoptions)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
