.TH "ContactsSample" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContactsSample \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApp\fP"
.br
.ti -1c
.RI "class \fBAppDelegate\fP"
.br
.ti -1c
.RI "class \fBApplication\fP"
.br
.ti -1c
.RI "class \fBContactActivity\fP"
.br
.ti -1c
.RI "class \fBDetailContactView\fP"
.br
.RI "\fIDetail contact view\&. This view displays the details of a contact\&. \fP"
.ti -1c
.RI "class \fBMainActivity\fP"
.br
.ti -1c
.RI "class \fBMainPage\fP"
.br
.ti -1c
.RI "class \fBMainPageViewModel\fP"
.br
.ti -1c
.RI "class \fBMainView\fP"
.br
.ti -1c
.RI "class \fBResource\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
