.TH "/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService/Data/Enumerations.cs" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService/Data/Enumerations.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBFieldService\&.Data\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBFieldService\&.Data\&.AssignmentStatus\fP { \fBFieldService\&.Data\&.AssignmentStatus\&.New\fP = 0, \fBFieldService\&.Data\&.AssignmentStatus\&.Hold\fP = 1, \fBFieldService\&.Data\&.AssignmentStatus\&.Active\fP = 2, \fBFieldService\&.Data\&.AssignmentStatus\&.Complete\fP = 3, \fBFieldService\&.Data\&.AssignmentStatus\&.Declined\fP = 9999 }"
.br
.RI "\fIAn enumeration for Assignment status \fP"
.ti -1c
.RI "enum \fBFieldService\&.Data\&.LaborType\fP { \fBFieldService\&.Data\&.LaborType\&.Hourly\fP = 0, \fBFieldService\&.Data\&.LaborType\&.OverTime\fP = 1, \fBFieldService\&.Data\&.LaborType\&.HolidayTime\fP = 2 }"
.br
.RI "\fIAn enumeration for Labor types \fP"
.ti -1c
.RI "enum \fBFieldService\&.Data\&.ExpenseCategory\fP { \fBFieldService\&.Data\&.ExpenseCategory\&.Gas\fP = 0, \fBFieldService\&.Data\&.ExpenseCategory\&.Food\fP = 1, \fBFieldService\&.Data\&.ExpenseCategory\&.Supplies\fP = 2, \fBFieldService\&.Data\&.ExpenseCategory\&.Other\fP = 3 }"
.br
.RI "\fIAn enumeration for Expense categories \fP"
.ti -1c
.RI "enum \fBFieldService\&.Data\&.DocumentType\fP { \fBFieldService\&.Data\&.DocumentType\&.Contract\fP = 0, \fBFieldService\&.Data\&.DocumentType\&.ServiceAgreement\fP = 1, \fBFieldService\&.Data\&.DocumentType\&.Specifications\fP = 2 }"
.br
.RI "\fIAn enumeration for different types of Documents \fP"
.ti -1c
.RI "enum \fBFieldService\&.Data\&.AssignmentHistoryType\fP { \fBFieldService\&.Data\&.AssignmentHistoryType\&.Assignment\fP, \fBFieldService\&.Data\&.AssignmentHistoryType\&.PhoneCall\fP }"
.br
.RI "\fIAn enumeration for different types of \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
