.TH "/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.WinRT/Views/ExpensesPage.xaml.cs" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.WinRT/Views/ExpensesPage.xaml.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFieldService\&.WinRT\&.Views\&.ExpensesPage\fP"
.br
.RI "\fIPage for displaying expenses \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBFieldService\&.WinRT\&.Views\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
