.TH "FieldService.Data.SampleLoginService" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Data.SampleLoginService \- 
.PP
Default IService implementation  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.ILoginService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Task< bool > \fBLoginAsync\fP (string username, string password, \fBCancellationToken\fP cancellationToken=default(\fBCancellationToken\fP))"
.br
.RI "\fIAsynchronous login \fP"
.in -1c
.SH "Detailed Description"
.PP 
Default IService implementation 


.IP "\(bu" 2
uses a fake sleep, to emulate network interaction 
.PP

.SH "Member Function Documentation"
.PP 
.SS "Task<bool> FieldService\&.Data\&.SampleLoginService\&.LoginAsync (stringusername, stringpassword, \fBCancellationToken\fPcancellationToken = \fCdefault(\fBCancellationToken\fP)\fP)"

.PP
Asynchronous login 
.PP
Implements \fBFieldService\&.ILoginService\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
