.TH "FieldService.Data.AssignmentItem" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Data.AssignmentItem \- 
.PP
Link from an item to an assignment  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.Data\&.PropertyChangedBase\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.RI "\fIId of the assignment item, not really used \fP"
.ti -1c
.RI "int \fBItemId\fP\fC [get, set]\fP"
.br
.RI "\fILink to an item \fP"
.ti -1c
.RI "int \fBAssignmentId\fP\fC [get, set]\fP"
.br
.RI "\fILink to an assignment \fP"
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "\fIThe item's name \fP"
.ti -1c
.RI "string \fBNumber\fP\fC [get, set]\fP"
.br
.RI "\fIThe item's number \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Link from an item to an assignment 


.IP "\(bu" 2
determines items on an assignment and which have been used 
.PP

.SH "Property Documentation"
.PP 
.SS "int FieldService\&.Data\&.AssignmentItem\&.AssignmentId\fC [get]\fP, \fC [set]\fP"

.PP
Link to an assignment 
.SS "int FieldService\&.Data\&.AssignmentItem\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Id of the assignment item, not really used 
.SS "int FieldService\&.Data\&.AssignmentItem\&.ItemId\fC [get]\fP, \fC [set]\fP"

.PP
Link to an item 
.SS "string FieldService\&.Data\&.AssignmentItem\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
The item's name 
.SS "string FieldService\&.Data\&.AssignmentItem\&.Number\fC [get]\fP, \fC [set]\fP"

.PP
The item's number 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
