.TH "FieldService.Android" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBActivities\fP"
.br
.ti -1c
.RI "package \fBAdapters\fP"
.br
.ti -1c
.RI "package \fBDialogs\fP"
.br
.ti -1c
.RI "package \fBFragments\fP"
.br
.ti -1c
.RI "package \fBUtilities\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApplication\fP"
.br
.ti -1c
.RI "class \fBAssignmentsActivity\fP"
.br
.RI "\fIActivity for the list of assignments \fP"
.ti -1c
.RI "class \fBAssignmentsAdapter\fP"
.br
.RI "\fIAdapter for a list of assignments \fP"
.ti -1c
.RI "class \fBAssignmentTabActivity\fP"
.br
.RI "\fIActivity for the tab bar between 'Assignments' and 'Map Overview' \fP"
.ti -1c
.RI "class \fBBaseActivity\fP"
.br
.RI "\fIBase activity for all activities, handles global OnPause/OnResume \fP"
.ti -1c
.RI "class \fBBaseMapActivity\fP"
.br
.RI "\fIBase activity for all 'map' activities, handles global OnPause/OnResume \fP"
.ti -1c
.RI "class \fBExpensesAdapter\fP"
.br
.ti -1c
.RI "class \fBItemsAdapter\fP"
.br
.RI "\fIAdapter for a list of items \fP"
.ti -1c
.RI "class \fBItemsSearchAdapter\fP"
.br
.RI "\fIAdapter for searching through a list of items \fP"
.ti -1c
.RI "class \fBLaborHoursAdapter\fP"
.br
.RI "\fIAdapter for a list of labor entries \fP"
.ti -1c
.RI "class \fBLaborTypeSpinnerAdapter\fP"
.br
.RI "\fIAdapter for a spinner for selecting LaborType \fP"
.ti -1c
.RI "class \fBLoginActivity\fP"
.br
.RI "\fIActivity for the login screen \fP"
.ti -1c
.RI "class \fBMapFragmentActivity\fP"
.br
.RI "\fI'Fragment' for the map - it is required to be an activity although used as a fragment \fP"
.ti -1c
.RI "class \fBMapViewActivity\fP"
.br
.RI "\fIActivity for the map overview \fP"
.ti -1c
.RI "class \fBNavigationAdapter\fP"
.br
.RI "\fIAdapter for the navigation options in the menu \fP"
.ti -1c
.RI "class \fBPhotosAdapter\fP"
.br
.RI "\fIAdapter for a list of photos \fP"
.ti -1c
.RI "class \fBResource\fP"
.br
.ti -1c
.RI "class \fBSpinnerAdapter< T >\fP"
.br
.RI "\fIGeneric adapter for Spinners throughout the app \fP"
.ti -1c
.RI "class \fBSummaryActivity\fP"
.br
.RI "\fIActivity for the summary screen \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
