.TH "FieldService.Tests.ViewModels.ExpenseViewModelTests" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Tests.ViewModels.ExpenseViewModelTests \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP ()"
.br
.ti -1c
.RI "void \fBLoadExpenses\fP ()"
.br
.ti -1c
.RI "void \fBSaveExpense\fP ()"
.br
.ti -1c
.RI "void \fBDeleteExpense\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void FieldService\&.Tests\&.ViewModels\&.ExpenseViewModelTests\&.DeleteExpense ()"

.SS "void FieldService\&.Tests\&.ViewModels\&.ExpenseViewModelTests\&.LoadExpenses ()"

.SS "void FieldService\&.Tests\&.ViewModels\&.ExpenseViewModelTests\&.SaveExpense ()"

.SS "void FieldService\&.Tests\&.ViewModels\&.ExpenseViewModelTests\&.SetUp ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
