.TH "FieldService.iOS.StatusButton" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.StatusButton \- 
.PP
Status button for assignments  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UIButton\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStatusButton\fP (IntPtr handle)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBAssignment\fP \fBAssignment\fP\fC [get, set]\fP"
.br
.RI "\fIThe current assignment \fP"
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler \fBStatusChanged\fP"
.br
.RI "\fIOccurs when the status changes \fP"
.ti -1c
.RI "EventHandler \fBCompleted\fP"
.br
.RI "\fIOccurs when the user completes an assignment, we need to move to the confirmation screen \fP"
.in -1c
.SH "Detailed Description"
.PP 
Status button for assignments 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.StatusButton\&.StatusButton (IntPtrhandle)"

.SH "Property Documentation"
.PP 
.SS "\fBAssignment\fP FieldService\&.iOS\&.StatusButton\&.Assignment\fC [get]\fP, \fC [set]\fP"

.PP
The current assignment 
.SH "Event Documentation"
.PP 
.SS "EventHandler FieldService\&.iOS\&.StatusButton\&.Completed"

.PP
Occurs when the user completes an assignment, we need to move to the confirmation screen 
.SS "EventHandler FieldService\&.iOS\&.StatusButton\&.StatusChanged"

.PP
Occurs when the status changes 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
