.TH "FieldService.Data.Photo" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Data.Photo \- 
.PP
Holds a photo for an assignment  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.RI "\fI\fBPhoto\fP Id \fP"
.ti -1c
.RI "int \fBAssignmentId\fP\fC [get, set]\fP"
.br
.RI "\fILink to assignment \fP"
.ti -1c
.RI "byte[] \fBImage\fP\fC [get, set]\fP"
.br
.RI "\fIActual image \fP"
.ti -1c
.RI "DateTime \fBDate\fP\fC [get, set]\fP"
.br
.RI "\fIDate image was saved \fP"
.ti -1c
.RI "string \fBDescription\fP\fC [get, set]\fP"
.br
.RI "\fIDescription for photo \fP"
.ti -1c
.RI "string \fBTimeFormatted\fP\fC [get]\fP"
.br
.RI "\fIThe time component of the DateTime on the photo \fP"
.ti -1c
.RI "string \fBDateFormatted\fP\fC [get]\fP"
.br
.RI "\fIThe date component of the DateTime on the photo \fP"
.in -1c
.SH "Detailed Description"
.PP 
Holds a photo for an assignment 


.SH "Property Documentation"
.PP 
.SS "int FieldService\&.Data\&.Photo\&.AssignmentId\fC [get]\fP, \fC [set]\fP"

.PP
Link to assignment 
.SS "DateTime FieldService\&.Data\&.Photo\&.Date\fC [get]\fP, \fC [set]\fP"

.PP
Date image was saved 
.SS "string FieldService\&.Data\&.Photo\&.DateFormatted\fC [get]\fP"

.PP
The date component of the DateTime on the photo 
.SS "string FieldService\&.Data\&.Photo\&.Description\fC [get]\fP, \fC [set]\fP"

.PP
Description for photo 
.SS "int FieldService\&.Data\&.Photo\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
\fBPhoto\fP Id 
.SS "byte [] FieldService\&.Data\&.Photo\&.Image\fC [get]\fP, \fC [set]\fP"

.PP
Actual image 
.SS "string FieldService\&.Data\&.Photo\&.TimeFormatted\fC [get]\fP"

.PP
The time component of the DateTime on the photo 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
