.TH "FieldService.Android.Utilities.EventArgs< T >" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Utilities.EventArgs< T > \- 
.PP
Helper class for making strongly typed EventArgs  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "T \fBValue\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Helper class for making strongly typed EventArgs 


.SH "Property Documentation"
.PP 
.SS "T FieldService\&.Android\&.Utilities\&.EventArgs< T >\&.Value\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
