.TH "FieldService.Data.Labor" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Data.Labor \- 
.PP
\fBLabor\fP to be performed on an assignment  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.RI "\fIId of the item \fP"
.ti -1c
.RI "\fBLaborType\fP \fBType\fP\fC [get, set]\fP"
.br
.RI "\fIType of labor performed \fP"
.ti -1c
.RI "string \fBDescription\fP\fC [get, set]\fP"
.br
.RI "\fIAn extended description for the job \fP"
.ti -1c
.RI "int \fBAssignmentId\fP\fC [get, set]\fP"
.br
.RI "\fILink to an assignment \fP"
.ti -1c
.RI "TimeSpan \fBHours\fP\fC [get, set]\fP"
.br
.RI "\fIThe duration of this labor expressed in hours \fP"
.ti -1c
.RI "long \fBTicks\fP\fC [get, set]\fP"
.br
.RI "\fI\fBLabor\fP hours for the assignment (in ticks) \fP"
.ti -1c
.RI "string \fBTypeAsString\fP\fC [get]\fP"
.br
.RI "\fIA nicely string formatted version of Type \fP"
.ti -1c
.RI "string \fBHoursFormatted\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBLabor\fP to be performed on an assignment 


.SH "Property Documentation"
.PP 
.SS "int FieldService\&.Data\&.Labor\&.AssignmentId\fC [get]\fP, \fC [set]\fP"

.PP
Link to an assignment 
.SS "string FieldService\&.Data\&.Labor\&.Description\fC [get]\fP, \fC [set]\fP"

.PP
An extended description for the job 
.SS "TimeSpan FieldService\&.Data\&.Labor\&.Hours\fC [get]\fP, \fC [set]\fP"

.PP
The duration of this labor expressed in hours 
.SS "string FieldService\&.Data\&.Labor\&.HoursFormatted\fC [get]\fP"

.SS "int FieldService\&.Data\&.Labor\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Id of the item 
.SS "long FieldService\&.Data\&.Labor\&.Ticks\fC [get]\fP, \fC [set]\fP"

.PP
\fBLabor\fP hours for the assignment (in ticks) 
.SS "\fBLaborType\fP FieldService\&.Data\&.Labor\&.Type\fC [get]\fP, \fC [set]\fP"

.PP
Type of labor performed 
.SS "string FieldService\&.Data\&.Labor\&.TypeAsString\fC [get]\fP"

.PP
A nicely string formatted version of Type 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
