.TH "FieldService.WinRT.Views.LoginPage" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.WinRT.Views.LoginPage \- 
.PP
The initial login page  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Page\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoginPage\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnNavigatedTo\fP (NavigationEventArgs e)"
.br
.RI "\fIInvoked when this page is about to be displayed in a Frame\&. \fP"
.ti -1c
.RI "override void \fBOnNavigatedFrom\fP (NavigationEventArgs e)"
.br
.ti -1c
.RI "override void \fBOnKeyDown\fP (KeyRoutedEventArgs e)"
.br
.RI "\fIUsed for hooking up enter key to login \fP"
.in -1c
.SH "Detailed Description"
.PP 
The initial login page 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.WinRT\&.Views\&.LoginPage\&.LoginPage ()"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.WinRT\&.Views\&.LoginPage\&.OnKeyDown (KeyRoutedEventArgse)\fC [protected]\fP"

.PP
Used for hooking up enter key to login 
.PP
\fBParameters:\fP
.RS 4
\fIe\fP 
.RE
.PP

.SS "override void FieldService\&.WinRT\&.Views\&.LoginPage\&.OnNavigatedFrom (NavigationEventArgse)\fC [protected]\fP"

.SS "override void FieldService\&.WinRT\&.Views\&.LoginPage\&.OnNavigatedTo (NavigationEventArgse)\fC [protected]\fP"

.PP
Invoked when this page is about to be displayed in a Frame\&. 
.PP
\fBParameters:\fP
.RS 4
\fIe\fP Event data that describes how this page was reached\&. The Parameter property is typically used to configure the page\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
