.TH "FieldService.Android.AssignmentsAdapter" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.AssignmentsAdapter \- 
.PP
Adapter for a list of assignments  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ArrayAdapter< Assignment >, IOnClickListener, and IOnItemSelectedListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssignmentsAdapter\fP (\fBAssignmentsActivity\fP activity, int resourceId, List< \fBAssignment\fP > assignments)"
.br
.ti -1c
.RI "override View \fBGetView\fP (int position, View convertView, ViewGroup parent)"
.br
.ti -1c
.RI "void \fBOnClick\fP (View v)"
.br
.ti -1c
.RI "void \fBOnItemSelected\fP (AdapterView parent, View view, int position, long id)"
.br
.ti -1c
.RI "void \fBOnNothingSelected\fP (AdapterView parent)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Adapter for a list of assignments 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.AssignmentsAdapter\&.AssignmentsAdapter (\fBAssignmentsActivity\fPactivity, intresourceId, List< \fBAssignment\fP >assignments)"

.SH "Member Function Documentation"
.PP 
.SS "override View FieldService\&.Android\&.AssignmentsAdapter\&.GetView (intposition, ViewconvertView, ViewGroupparent)"

.SS "void FieldService\&.Android\&.AssignmentsAdapter\&.OnClick (Viewv)"

.SS "void FieldService\&.Android\&.AssignmentsAdapter\&.OnItemSelected (AdapterViewparent, Viewview, intposition, longid)"

.SS "void FieldService\&.Android\&.AssignmentsAdapter\&.OnNothingSelected (AdapterViewparent)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
