.TH "FieldService.Android.Fragments.ConfirmationFragment" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Fragments.ConfirmationFragment \- 
.PP
Fragment for the confirmation section  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Fragment\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "override View \fBOnCreateView\fP (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)"
.br
.ti -1c
.RI "override void \fBOnPause\fP ()"
.br
.RI "\fIDismiss the signature dialog if shown \fP"
.ti -1c
.RI "void \fBReloadConfirmation\fP ()"
.br
.RI "\fIReload Confirmation fragment \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBPhoto\fP > \fBPhotos\fP\fC [get, set]\fP"
.br
.RI "\fIList of photos \fP"
.ti -1c
.RI "\fBAssignment\fP \fBAssignment\fP\fC [get, set]\fP"
.br
.RI "\fIThe current assignment \fP"
.in -1c
.SH "Detailed Description"
.PP 
Fragment for the confirmation section 


.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.Android\&.Fragments\&.ConfirmationFragment\&.OnCreate (BundlesavedInstanceState)"

.SS "override View FieldService\&.Android\&.Fragments\&.ConfirmationFragment\&.OnCreateView (LayoutInflaterinflater, ViewGroupcontainer, BundlesavedInstanceState)"

.SS "override void FieldService\&.Android\&.Fragments\&.ConfirmationFragment\&.OnPause ()"

.PP
Dismiss the signature dialog if shown 
.SS "void FieldService\&.Android\&.Fragments\&.ConfirmationFragment\&.ReloadConfirmation ()"

.PP
Reload Confirmation fragment 
.SH "Property Documentation"
.PP 
.SS "\fBAssignment\fP FieldService\&.Android\&.Fragments\&.ConfirmationFragment\&.Assignment\fC [get]\fP, \fC [set]\fP"

.PP
The current assignment 
.SS "List<\fBPhoto\fP> FieldService\&.Android\&.Fragments\&.ConfirmationFragment\&.Photos\fC [get]\fP, \fC [set]\fP"

.PP
List of photos 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
