.TH "FieldService.iOS.ItemsViewController" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.ItemsViewController \- 
.PP
Controller for the list of items  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.iOS\&.BaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBItemsViewController\fP (IntPtr handle)"
.br
.ti -1c
.RI "override void \fBViewDidLoad\fP ()"
.br
.ti -1c
.RI "override void \fBViewWillAppear\fP (bool animated)"
.br
.ti -1c
.RI "override void \fBViewWillDisappear\fP (bool animated)"
.br
.ti -1c
.RI "void \fBReloadItems\fP ()"
.br
.RI "\fICall to reload the list of items \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Controller for the list of items 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.ItemsViewController\&.ItemsViewController (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "void FieldService\&.iOS\&.ItemsViewController\&.ReloadItems ()"

.PP
Call to reload the list of items 
.SS "override void FieldService\&.iOS\&.ItemsViewController\&.ViewDidLoad ()"

.SS "override void FieldService\&.iOS\&.ItemsViewController\&.ViewWillAppear (boolanimated)"

.SS "override void FieldService\&.iOS\&.ItemsViewController\&.ViewWillDisappear (boolanimated)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
