.TH "FieldService.Android.Dialogs.AddLaborDialog" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Dialogs.AddLaborDialog \- 
.PP
Dialog for adding labor entries  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.Android\&.Dialogs\&.BaseDialog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddLaborDialog\fP (Activity activity)"
.br
.ti -1c
.RI "override void \fBOnAttachedToWindow\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCreate\fP (Bundle savedInstanceState)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBLabor\fP \fBCurrentLabor\fP\fC [get, set]\fP"
.br
.RI "\fISelected labor entry \fP"
.ti -1c
.RI "\fBAssignment\fP \fBAssignment\fP\fC [get, set]\fP"
.br
.RI "\fIThe selected assignment \fP"
.in -1c
.SH "Detailed Description"
.PP 
Dialog for adding labor entries 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.Dialogs\&.AddLaborDialog\&.AddLaborDialog (Activityactivity)"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.Android\&.Dialogs\&.AddLaborDialog\&.OnAttachedToWindow ()"

.SS "override void FieldService\&.Android\&.Dialogs\&.AddLaborDialog\&.OnCreate (BundlesavedInstanceState)\fC [protected]\fP"

.SH "Property Documentation"
.PP 
.SS "\fBAssignment\fP FieldService\&.Android\&.Dialogs\&.AddLaborDialog\&.Assignment\fC [get]\fP, \fC [set]\fP"

.PP
The selected assignment 
.SS "\fBLabor\fP FieldService\&.Android\&.Dialogs\&.AddLaborDialog\&.CurrentLabor\fC [get]\fP, \fC [set]\fP"

.PP
Selected labor entry 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
