.TH "FieldService.Android.ItemsAdapter" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.ItemsAdapter \- 
.PP
Adapter for a list of items  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ArrayAdapter< AssignmentItem >, and IOnClickListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBItemsAdapter\fP (Context context, int resourceId, IList< \fBAssignmentItem\fP > assignmentItems)"
.br
.ti -1c
.RI "override View \fBGetView\fP (int position, View convertView, ViewGroup parent)"
.br
.ti -1c
.RI "void \fBOnClick\fP (View v)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBItemFragment\fP \fBFragment\fP\fC [get, set]\fP"
.br
.RI "\fIThe parent fragment this adapter is in \fP"
.in -1c
.SH "Detailed Description"
.PP 
Adapter for a list of items 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.ItemsAdapter\&.ItemsAdapter (Contextcontext, intresourceId, IList< \fBAssignmentItem\fP >assignmentItems)"

.SH "Member Function Documentation"
.PP 
.SS "override View FieldService\&.Android\&.ItemsAdapter\&.GetView (intposition, ViewconvertView, ViewGroupparent)"

.SS "void FieldService\&.Android\&.ItemsAdapter\&.OnClick (Viewv)"

.SH "Property Documentation"
.PP 
.SS "\fBItemFragment\fP FieldService\&.Android\&.ItemsAdapter\&.Fragment\fC [get]\fP, \fC [set]\fP"

.PP
The parent fragment this adapter is in 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
