.TH "FieldService.iOS.TabController" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.TabController \- 
.PP
Tab controller on the assignments page  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UITabBarController\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTabController\fP (IntPtr handle)"
.br
.ti -1c
.RI "override void \fBViewDidLoad\fP ()"
.br
.ti -1c
.RI "override bool \fBShouldAutorotate\fP ()"
.br
.RI "\fIThis is how orientation is setup on \fBiOS\fP 6 \fP"
.ti -1c
.RI "override UIInterfaceOrientationMask \fBGetSupportedInterfaceOrientations\fP ()"
.br
.RI "\fIThis is how orientation is setup on \fBiOS\fP 6 \fP"
.in -1c
.SH "Detailed Description"
.PP 
Tab controller on the assignments page 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.TabController\&.TabController (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "override UIInterfaceOrientationMask FieldService\&.iOS\&.TabController\&.GetSupportedInterfaceOrientations ()"

.PP
This is how orientation is setup on \fBiOS\fP 6 
.SS "override bool FieldService\&.iOS\&.TabController\&.ShouldAutorotate ()"

.PP
This is how orientation is setup on \fBiOS\fP 6 
.SS "override void FieldService\&.iOS\&.TabController\&.ViewDidLoad ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
