.TH "FieldService.Android.NavigationAdapter" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.NavigationAdapter \- 
.PP
Adapter for the navigation options in the menu  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ArrayAdapter< string >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNavigationAdapter\fP (Context context, int resourceId, List< string > items)"
.br
.ti -1c
.RI "override View \fBGetView\fP (int position, View convertView, ViewGroup parent)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Adapter for the navigation options in the menu 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.NavigationAdapter\&.NavigationAdapter (Contextcontext, intresourceId, List< string >items)"

.SH "Member Function Documentation"
.PP 
.SS "override View FieldService\&.Android\&.NavigationAdapter\&.GetView (intposition, ViewconvertView, ViewGroupparent)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
