.TH "FieldService.Data.Signature" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Data.Signature \- 
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.RI "\fI\fBSignature\fP Id \fP"
.ti -1c
.RI "int \fBAssignmentId\fP\fC [get, set]\fP"
.br
.RI "\fILink to an assignment \fP"
.ti -1c
.RI "byte[] \fBImage\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the signature image \fP"
.in -1c
.SH "Property Documentation"
.PP 
.SS "int FieldService\&.Data\&.Signature\&.AssignmentId\fC [get]\fP, \fC [set]\fP"

.PP
Link to an assignment 
.SS "int FieldService\&.Data\&.Signature\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
\fBSignature\fP Id 
.SS "byte [] FieldService\&.Data\&.Signature\&.Image\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the signature image 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
