.TH "FieldService.iOS.ExpenseController" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.ExpenseController \- 
.PP
Controller for the expenses section  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.iOS\&.BaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExpenseController\fP (IntPtr handle)"
.br
.ti -1c
.RI "override void \fBViewDidLoad\fP ()"
.br
.ti -1c
.RI "override void \fBViewWillAppear\fP (bool animated)"
.br
.ti -1c
.RI "override void \fBViewWillDisappear\fP (bool animated)"
.br
.ti -1c
.RI "void \fBReloadExpenses\fP ()"
.br
.RI "\fIReload the expenses \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Controller for the expenses section 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.ExpenseController\&.ExpenseController (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "void FieldService\&.iOS\&.ExpenseController\&.ReloadExpenses ()"

.PP
Reload the expenses 
.SS "override void FieldService\&.iOS\&.ExpenseController\&.ViewDidLoad ()"

.SS "override void FieldService\&.iOS\&.ExpenseController\&.ViewWillAppear (boolanimated)"

.SS "override void FieldService\&.iOS\&.ExpenseController\&.ViewWillDisappear (boolanimated)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
