.TH "FieldService.Android.BaseMapActivity" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.BaseMapActivity \- 
.PP
Base activity for all 'map' activities, handles global OnPause/OnResume  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MapActivity\&.
.PP
Inherited by \fBFieldService\&.Android\&.MapFragmentActivity\fP, and \fBFieldService\&.Android\&.MapViewActivity\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnPause\fP ()"
.br
.ti -1c
.RI "override void \fBOnResume\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBIsRouteDisplayed\fP\fC [get]\fP"
.br
.RI "\fIRequired abstract member, we don't need to display routes \fP"
.in -1c
.SH "Detailed Description"
.PP 
Base activity for all 'map' activities, handles global OnPause/OnResume 


.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.Android\&.BaseMapActivity\&.OnPause ()\fC [protected]\fP"

.SS "override void FieldService\&.Android\&.BaseMapActivity\&.OnResume ()\fC [protected]\fP"

.SH "Property Documentation"
.PP 
.SS "override bool FieldService\&.Android\&.BaseMapActivity\&.IsRouteDisplayed\fC [get]\fP, \fC [protected]\fP"

.PP
Required abstract member, we don't need to display routes 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
