.TH "FieldService.iOS.ISearchSource" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.ISearchSource \- 
.PP
A simple interface for supplying UISearchBar interaction  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBSearchText\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the search text the user entered \fP"
.in -1c
.SH "Detailed Description"
.PP 
A simple interface for supplying UISearchBar interaction 


.SH "Property Documentation"
.PP 
.SS "string FieldService\&.iOS\&.ISearchSource\&.SearchText\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the search text the user entered 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
