.TH "FieldService.Android.SummaryActivity" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.SummaryActivity \- 
.PP
Activity for the summary screen  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.Android\&.BaseActivity\fP, and IOnMenuItemClickListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSummaryActivity\fP ()"
.br
.ti -1c
.RI "override bool \fBOnCreateOptionsMenu\fP (IMenu menu)"
.br
.ti -1c
.RI "override bool \fBOnOptionsItemSelected\fP (IMenuItem item)"
.br
.ti -1c
.RI "bool \fBOnMenuItemClick\fP (IMenuItem item)"
.br
.ti -1c
.RI "override void \fBOnBackPressed\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCreate\fP (Bundle bundle)"
.br
.ti -1c
.RI "override void \fBOnResume\fP ()"
.br
.ti -1c
.RI "override void \fBOnPause\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Activity for the summary screen 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.SummaryActivity\&.SummaryActivity ()"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.Android\&.SummaryActivity\&.OnBackPressed ()"

.SS "override void FieldService\&.Android\&.SummaryActivity\&.OnCreate (Bundlebundle)\fC [protected]\fP"

.SS "override bool FieldService\&.Android\&.SummaryActivity\&.OnCreateOptionsMenu (IMenumenu)"

.SS "bool FieldService\&.Android\&.SummaryActivity\&.OnMenuItemClick (IMenuItemitem)"

.SS "override bool FieldService\&.Android\&.SummaryActivity\&.OnOptionsItemSelected (IMenuItemitem)"

.SS "override void FieldService\&.Android\&.SummaryActivity\&.OnPause ()\fC [protected]\fP"

.SS "override void FieldService\&.Android\&.SummaryActivity\&.OnResume ()\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
