.TH "FieldService.Android.Dialogs.ExpenseDialog" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Dialogs.ExpenseDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.Android\&.Dialogs\&.BaseDialog\fP, IOnClickListener, and IOnItemSelectedListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExpenseDialog\fP (Activity activity)"
.br
.ti -1c
.RI "override void \fBOnAttachedToWindow\fP ()"
.br
.ti -1c
.RI "override void \fBOnDetachedFromWindow\fP ()"
.br
.ti -1c
.RI "void \fBOnClick\fP (View v)"
.br
.ti -1c
.RI "void \fBOnItemSelected\fP (AdapterView parent, View view, int position, long id)"
.br
.ti -1c
.RI "void \fBOnNothingSelected\fP (AdapterView parent)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCreate\fP (Bundle savedInstanceState)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBAssignment\fP \fBAssignment\fP\fC [get, set]\fP"
.br
.RI "\fIfragment's current assignment \fP"
.ti -1c
.RI "\fBExpense\fP \fBCurrentExpense\fP\fC [get, set]\fP"
.br
.RI "\fIcurrent expense that is being edited \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.Dialogs\&.ExpenseDialog\&.ExpenseDialog (Activityactivity)"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.Android\&.Dialogs\&.ExpenseDialog\&.OnAttachedToWindow ()"

.SS "void FieldService\&.Android\&.Dialogs\&.ExpenseDialog\&.OnClick (Viewv)"

.SS "override void FieldService\&.Android\&.Dialogs\&.ExpenseDialog\&.OnCreate (BundlesavedInstanceState)\fC [protected]\fP"

.SS "override void FieldService\&.Android\&.Dialogs\&.ExpenseDialog\&.OnDetachedFromWindow ()"

.SS "void FieldService\&.Android\&.Dialogs\&.ExpenseDialog\&.OnItemSelected (AdapterViewparent, Viewview, intposition, longid)"

.SS "void FieldService\&.Android\&.Dialogs\&.ExpenseDialog\&.OnNothingSelected (AdapterViewparent)"

.SH "Property Documentation"
.PP 
.SS "\fBAssignment\fP FieldService\&.Android\&.Dialogs\&.ExpenseDialog\&.Assignment\fC [get]\fP, \fC [set]\fP"

.PP
fragment's current assignment 
.SS "\fBExpense\fP FieldService\&.Android\&.Dialogs\&.ExpenseDialog\&.CurrentExpense\fC [get]\fP, \fC [set]\fP"

.PP
current expense that is being edited 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
