.TH "FieldService.Data.Item" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Data.Item \- 
.PP
An item to be used on an assignment  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.RI "\fIId of the item \fP"
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "\fIName of the item \fP"
.ti -1c
.RI "string \fBNumber\fP\fC [get, set]\fP"
.br
.RI "\fINumber of the item \fP"
.ti -1c
.RI "string \fBNumberName\fP\fC [get]\fP"
.br
.RI "\fINumber & Name of \fBItem\fP for \fBWinRT\fP \fP"
.in -1c
.SH "Detailed Description"
.PP 
An item to be used on an assignment 


.SH "Property Documentation"
.PP 
.SS "int FieldService\&.Data\&.Item\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Id of the item 
.SS "string FieldService\&.Data\&.Item\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Name of the item 
.SS "string FieldService\&.Data\&.Item\&.Number\fC [get]\fP, \fC [set]\fP"

.PP
Number of the item 
.SS "string FieldService\&.Data\&.Item\&.NumberName\fC [get]\fP"

.PP
Number & Name of \fBItem\fP for \fBWinRT\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
