.TH "FieldService.Tests.Mocks.MockSynchronizeInvoke" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Tests.Mocks.MockSynchronizeInvoke \- 
.PP
Simple implementation of ISynchronizeInvoke for testing  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ISynchronizeInvoke\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "IAsyncResult \fBBeginInvoke\fP (Delegate method, object[] args)"
.br
.ti -1c
.RI "object \fBEndInvoke\fP (IAsyncResult result)"
.br
.ti -1c
.RI "object \fBInvoke\fP (Delegate method, object[] args)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBInvokeRequired\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Simple implementation of ISynchronizeInvoke for testing 


.SH "Member Function Documentation"
.PP 
.SS "IAsyncResult FieldService\&.Tests\&.Mocks\&.MockSynchronizeInvoke\&.BeginInvoke (Delegatemethod, object[]args)"

.SS "object FieldService\&.Tests\&.Mocks\&.MockSynchronizeInvoke\&.EndInvoke (IAsyncResultresult)"

.SS "object FieldService\&.Tests\&.Mocks\&.MockSynchronizeInvoke\&.Invoke (Delegatemethod, object[]args)"

.SH "Property Documentation"
.PP 
.SS "bool FieldService\&.Tests\&.Mocks\&.MockSynchronizeInvoke\&.InvokeRequired\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
