.TH "FieldService.Android.Fragments.DocumentFragment" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Fragments.DocumentFragment \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Fragment\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override View \fBOnCreateView\fP (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBDocument\fP > \fBDocuments\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override View FieldService\&.Android\&.Fragments\&.DocumentFragment\&.OnCreateView (LayoutInflaterinflater, ViewGroupcontainer, BundlesavedInstanceState)"

.SH "Property Documentation"
.PP 
.SS "List<\fBDocument\fP> FieldService\&.Android\&.Fragments\&.DocumentFragment\&.Documents\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
