.TH "FieldService.iOS.AssignmentCell" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.AssignmentCell \- 
.PP
Table cell for an assignment  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UITableViewCell\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssignmentCell\fP (IntPtr handle)"
.br
.ti -1c
.RI "override void \fBAwakeFromNib\fP ()"
.br
.ti -1c
.RI "void \fBSetAssignment\fP (\fBAssignmentsController\fP controller, \fBAssignment\fP assignment, NSIndexPath indexPath)"
.br
.RI "\fISets up the assignment for the cell \fP"
.ti -1c
.RI "override void \fBSetHighlighted\fP (bool highlighted, bool animated)"
.br
.RI "\fIWe override this to remove some highlighting behavior we don't want \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Table cell for an assignment 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.AssignmentCell\&.AssignmentCell (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.iOS\&.AssignmentCell\&.AwakeFromNib ()"

.SS "override void FieldService\&.iOS\&.AssignmentCell\&.Dispose (booldisposing)\fC [protected]\fP"

.SS "void FieldService\&.iOS\&.AssignmentCell\&.SetAssignment (\fBAssignmentsController\fPcontroller, \fBAssignment\fPassignment, NSIndexPathindexPath)"

.PP
Sets up the assignment for the cell 
.SS "override void FieldService\&.iOS\&.AssignmentCell\&.SetHighlighted (boolhighlighted, boolanimated)"

.PP
We override this to remove some highlighting behavior we don't want 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
