.TH "FieldService.Android.Dialogs" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Dialogs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAddLaborDialog\fP"
.br
.RI "\fIDialog for adding labor entries \fP"
.ti -1c
.RI "class \fBBaseDialog\fP"
.br
.RI "\fIBase dialog class, mainly for setting the CustomDialogTheme \fP"
.ti -1c
.RI "class \fBExpenseDialog\fP"
.br
.ti -1c
.RI "class \fBItemsDialog\fP"
.br
.RI "\fIDialog for searching through items \fP"
.ti -1c
.RI "class \fBPhotoDialog\fP"
.br
.RI "\fIDialog for the photos \fP"
.ti -1c
.RI "class \fBSignatureDialog\fP"
.br
.RI "\fIDialog for capturing a signature \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
