.TH "FieldService.Tests.ViewModels.AssignmentViewModelTests" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Tests.ViewModels.AssignmentViewModelTests \- 
.PP
\fBTests\fP for AssignmentViewModel  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP ()"
.br
.ti -1c
.RI "void \fBLoad\fP ()"
.br
.ti -1c
.RI "void \fBSaveAssignment\fP ()"
.br
.ti -1c
.RI "void \fBSaveAssignmentAsActive\fP ()"
.br
.ti -1c
.RI "void \fBRecord\fP ()"
.br
.ti -1c
.RI "void \fBPause\fP ()"
.br
.ti -1c
.RI "void \fBLoadTimerEntry\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBTests\fP for AssignmentViewModel 


.SH "Member Function Documentation"
.PP 
.SS "void FieldService\&.Tests\&.ViewModels\&.AssignmentViewModelTests\&.Load ()"

.SS "void FieldService\&.Tests\&.ViewModels\&.AssignmentViewModelTests\&.LoadTimerEntry ()"

.SS "void FieldService\&.Tests\&.ViewModels\&.AssignmentViewModelTests\&.Pause ()"

.SS "void FieldService\&.Tests\&.ViewModels\&.AssignmentViewModelTests\&.Record ()"

.SS "void FieldService\&.Tests\&.ViewModels\&.AssignmentViewModelTests\&.SaveAssignment ()"

.SS "void FieldService\&.Tests\&.ViewModels\&.AssignmentViewModelTests\&.SaveAssignmentAsActive ()"

.SS "void FieldService\&.Tests\&.ViewModels\&.AssignmentViewModelTests\&.SetUp ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
