.TH "FieldService.ViewModels.DocumentViewModel" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.ViewModels.DocumentViewModel \- 
.PP
ViewModel for managing documents  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.ViewModels\&.ViewModelBase\fP\&.
.PP
Inherited by \fBFieldService\&.WinRT\&.ViewModels\&.DocumentViewModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDocumentViewModel\fP ()"
.br
.ti -1c
.RI "Task \fBLoadDocumentsAsync\fP ()"
.br
.RI "\fIGets the list of documents \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBDocument\fP > \fBDocuments\fP\fC [get, set]\fP"
.br
.RI "\fIList of documents to display \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
ViewModel for managing documents 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.ViewModels\&.DocumentViewModel\&.DocumentViewModel ()"

.SH "Member Function Documentation"
.PP 
.SS "Task FieldService\&.ViewModels\&.DocumentViewModel\&.LoadDocumentsAsync ()"

.PP
Gets the list of documents 
.SH "Property Documentation"
.PP 
.SS "List<\fBDocument\fP> FieldService\&.ViewModels\&.DocumentViewModel\&.Documents\fC [get]\fP, \fC [set]\fP"

.PP
List of documents to display 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
