.TH "FieldService.Android.Resource.String" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Resource.String \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBAccept\fP = 2130968582"
.br
.ti -1c
.RI "const int \fBAddExpense\fP = 2130968606"
.br
.ti -1c
.RI "const int \fBAddItem\fP = 2130968605"
.br
.ti -1c
.RI "const int \fBAddLabor\fP = 2130968588"
.br
.ti -1c
.RI "const int \fBAddPhoto\fP = 2130968596"
.br
.ti -1c
.RI "const int \fBAddSignature\fP = 2130968597"
.br
.ti -1c
.RI "const int \fBApplicationName\fP = 2130968577"
.br
.ti -1c
.RI "const int \fBCamera\fP = 2130968603"
.br
.ti -1c
.RI "const int \fBCancel\fP = 2130968590"
.br
.ti -1c
.RI "const int \fBClear\fP = 2130968602"
.br
.ti -1c
.RI "const int \fBComplete\fP = 2130968598"
.br
.ti -1c
.RI "const int \fBConfirmations\fP = 2130968616"
.br
.ti -1c
.RI "const int \fBDecline\fP = 2130968583"
.br
.ti -1c
.RI "const int \fBDelete\fP = 2130968591"
.br
.ti -1c
.RI "const int \fBDeletePhoto\fP = 2130968599"
.br
.ti -1c
.RI "const int \fBDocuments\fP = 2130968615"
.br
.ti -1c
.RI "const int \fBDollarSign\fP = 2130968607"
.br
.ti -1c
.RI "const int \fBDone\fP = 2130968600"
.br
.ti -1c
.RI "const int \fBEnterDescription\fP = 2130968610"
.br
.ti -1c
.RI "const int \fBExpenses\fP = 2130968585"
.br
.ti -1c
.RI "const int \fBGallery\fP = 2130968604"
.br
.ti -1c
.RI "const int \fBGoogleMapsAPIKey\fP = 2130968609"
.br
.ti -1c
.RI "const int \fBGoogleMapsKeyIssue\fP = 2130968617"
.br
.ti -1c
.RI "const int \fBHello\fP = 2130968576"
.br
.ti -1c
.RI "const int \fBHistory\fP = 2130968614"
.br
.ti -1c
.RI "const int \fBHoursAbbrev\fP = 2130968589"
.br
.ti -1c
.RI "const int \fBItems\fP = 2130968586"
.br
.ti -1c
.RI "const int \fBLaborHours\fP = 2130968587"
.br
.ti -1c
.RI "const int \fBMap\fP = 2130968613"
.br
.ti -1c
.RI "const int \fBMapTab\fP = 2130968581"
.br
.ti -1c
.RI "const int \fBOptionalCaption\fP = 2130968611"
.br
.ti -1c
.RI "const int \fBPassword\fP = 2130968579"
.br
.ti -1c
.RI "const int \fBPhoto\fP = 2130968594"
.br
.ti -1c
.RI "const int \fBPhotos\fP = 2130968593"
.br
.ti -1c
.RI "const int \fBPleaseSign\fP = 2130968601"
.br
.ti -1c
.RI "const int \fBPriorityTab\fP = 2130968580"
.br
.ti -1c
.RI "const int \fBSave\fP = 2130968592"
.br
.ti -1c
.RI "const int \fBSearch\fP = 2130968608"
.br
.ti -1c
.RI "const int \fBSignature\fP = 2130968595"
.br
.ti -1c
.RI "const int \fBSummary\fP = 2130968612"
.br
.ti -1c
.RI "const int \fBUsername\fP = 2130968578"
.br
.ti -1c
.RI "const int \fBXamarin\fP = 2130968584"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const int FieldService\&.Android\&.Resource\&.String\&.Accept = 2130968582"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.AddExpense = 2130968606"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.AddItem = 2130968605"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.AddLabor = 2130968588"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.AddPhoto = 2130968596"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.AddSignature = 2130968597"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.ApplicationName = 2130968577"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Camera = 2130968603"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Cancel = 2130968590"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Clear = 2130968602"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Complete = 2130968598"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Confirmations = 2130968616"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Decline = 2130968583"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Delete = 2130968591"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.DeletePhoto = 2130968599"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Documents = 2130968615"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.DollarSign = 2130968607"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Done = 2130968600"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.EnterDescription = 2130968610"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Expenses = 2130968585"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Gallery = 2130968604"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.GoogleMapsAPIKey = 2130968609"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.GoogleMapsKeyIssue = 2130968617"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Hello = 2130968576"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.History = 2130968614"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.HoursAbbrev = 2130968589"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Items = 2130968586"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.LaborHours = 2130968587"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Map = 2130968613"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.MapTab = 2130968581"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.OptionalCaption = 2130968611"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Password = 2130968579"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Photo = 2130968594"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Photos = 2130968593"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.PleaseSign = 2130968601"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.PriorityTab = 2130968580"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Save = 2130968592"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Search = 2130968608"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Signature = 2130968595"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Summary = 2130968612"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Username = 2130968578"

.SS "const int FieldService\&.Android\&.Resource\&.String\&.Xamarin = 2130968584"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
