.TH "fieldservice.android.fragments.HistoryFragment_TabContent" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fieldservice.android.fragments.HistoryFragment_TabContent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Object, IGCUserPeer, and TabContentFactory\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHistoryFragment_TabContent\fP ()  throws java\&.lang\&.Throwable 	"
.br
.ti -1c
.RI "\fBHistoryFragment_TabContent\fP (android\&.view\&.View p0)  throws java\&.lang\&.Throwable 	"
.br
.ti -1c
.RI "android\&.view\&.View \fBcreateTabContent\fP (java\&.lang\&.String p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "fieldservice\&.android\&.fragments\&.HistoryFragment_TabContent\&.HistoryFragment_TabContent () throws java\&.lang\&.Throwable"

.SS "fieldservice\&.android\&.fragments\&.HistoryFragment_TabContent\&.HistoryFragment_TabContent (android\&.view\&.Viewp0) throws java\&.lang\&.Throwable"

.SH "Member Function Documentation"
.PP 
.SS "android\&.view\&.View fieldservice\&.android\&.fragments\&.HistoryFragment_TabContent\&.createTabContent (java\&.lang\&.Stringp0)"

.SS "void fieldservice\&.android\&.fragments\&.HistoryFragment_TabContent\&.monodroidAddReference (java\&.lang\&.Objectobj)"

.SS "void fieldservice\&.android\&.fragments\&.HistoryFragment_TabContent\&.monodroidClearReferences ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
