.TH "FieldService.Android.Activities.SummaryHistoryActivity" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Activities.SummaryHistoryActivity \- 
.PP
History Activity  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Activity, and IOnMenuItemClickListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSummaryHistoryActivity\fP ()"
.br
.ti -1c
.RI "override bool \fBOnCreateOptionsMenu\fP (IMenu menu)"
.br
.ti -1c
.RI "override bool \fBOnOptionsItemSelected\fP (IMenuItem item)"
.br
.ti -1c
.RI "bool \fBOnMenuItemClick\fP (IMenuItem item)"
.br
.ti -1c
.RI "override void \fBOnBackPressed\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCreate\fP (Bundle bundle)"
.br
.ti -1c
.RI "override void \fBOnResume\fP ()"
.br
.ti -1c
.RI "override void \fBOnPause\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
History Activity 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.Activities\&.SummaryHistoryActivity\&.SummaryHistoryActivity ()"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.Android\&.Activities\&.SummaryHistoryActivity\&.OnBackPressed ()"

.SS "override void FieldService\&.Android\&.Activities\&.SummaryHistoryActivity\&.OnCreate (Bundlebundle)\fC [protected]\fP"

.SS "override bool FieldService\&.Android\&.Activities\&.SummaryHistoryActivity\&.OnCreateOptionsMenu (IMenumenu)"

.SS "bool FieldService\&.Android\&.Activities\&.SummaryHistoryActivity\&.OnMenuItemClick (IMenuItemitem)"

.SS "override bool FieldService\&.Android\&.Activities\&.SummaryHistoryActivity\&.OnOptionsItemSelected (IMenuItemitem)"

.SS "override void FieldService\&.Android\&.Activities\&.SummaryHistoryActivity\&.OnPause ()\fC [protected]\fP"

.SS "override void FieldService\&.Android\&.Activities\&.SummaryHistoryActivity\&.OnResume ()\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
