.TH "FieldService.iOS.AppDelegate" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.AppDelegate \- 
.PP
\fBAppDelegate\fP, the main callback for application-level events in \fBiOS\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UIApplicationDelegate\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBFinishedLaunching\fP (UIApplication application, NSDictionary launchOptions)"
.br
.RI "\fIThis the main entry point for the app on \fBiOS\fP \fP"
.ti -1c
.RI "override UIInterfaceOrientationMask \fBGetSupportedInterfaceOrientations\fP (UIApplication application, UIWindow forWindow)"
.br
.RI "\fIThis is how orientation is setup on \fBiOS\fP 6 \fP"
.ti -1c
.RI "override void \fBDidEnterBackground\fP (UIApplication application)"
.br
.RI "\fIEvent when the app is backgrounded, or screen turned off \fP"
.ti -1c
.RI "override void \fBWillEnterForeground\fP (UIApplication application)"
.br
.RI "\fIEvent when the app is brought back to the foreground or screen unlocked \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override UIWindow \fBWindow\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAppDelegate\fP, the main callback for application-level events in \fBiOS\fP 


.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.iOS\&.AppDelegate\&.DidEnterBackground (UIApplicationapplication)"

.PP
Event when the app is backgrounded, or screen turned off 
.SS "override bool FieldService\&.iOS\&.AppDelegate\&.FinishedLaunching (UIApplicationapplication, NSDictionarylaunchOptions)"

.PP
This the main entry point for the app on \fBiOS\fP 
.SS "override UIInterfaceOrientationMask FieldService\&.iOS\&.AppDelegate\&.GetSupportedInterfaceOrientations (UIApplicationapplication, UIWindowforWindow)"

.PP
This is how orientation is setup on \fBiOS\fP 6 
.SS "override void FieldService\&.iOS\&.AppDelegate\&.WillEnterForeground (UIApplicationapplication)"

.PP
Event when the app is brought back to the foreground or screen unlocked 
.SH "Property Documentation"
.PP 
.SS "override UIWindow FieldService\&.iOS\&.AppDelegate\&.Window\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
