.TH "FieldService.Tests.Mocks" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Tests.Mocks \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMockAssignmentService\fP"
.br
.RI "\fIThis is just a mock service to bypass the \fBSQLite\fP database for speed during test runs \fP"
.ti -1c
.RI "class \fBMockSynchronizeInvoke\fP"
.br
.RI "\fISimple implementation of ISynchronizeInvoke for testing \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
