.TH "FieldService.Data.Document" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Data.Document \- 
.PP
Class holding information about a document  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTitle\fP\fC [get, set]\fP"
.br
.RI "\fITitle of the document \fP"
.ti -1c
.RI "string \fBPath\fP\fC [get, set]\fP"
.br
.RI "\fIFile path to the document \fP"
.ti -1c
.RI "\fBDocumentType\fP \fBType\fP\fC [get, set]\fP"
.br
.RI "\fIThe document type, this determines the color for the UI on some platforms \fP"
.in -1c
.SH "Detailed Description"
.PP 
Class holding information about a document 


.SH "Property Documentation"
.PP 
.SS "string FieldService\&.Data\&.Document\&.Path\fC [get]\fP, \fC [set]\fP"

.PP
File path to the document 
.SS "string FieldService\&.Data\&.Document\&.Title\fC [get]\fP, \fC [set]\fP"

.PP
Title of the document 
.SS "\fBDocumentType\fP FieldService\&.Data\&.Document\&.Type\fC [get]\fP, \fC [set]\fP"

.PP
The document type, this determines the color for the UI on some platforms 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
