.TH "FieldService.iOS.MenuEventArgs" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.MenuEventArgs \- 
.PP
EventArgs used for when the selection changes in \fBMenuController\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMenuEventArgs\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "UITableView \fBTableView\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "NSIndexPath \fBIndexPath\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBAnimated\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
EventArgs used for when the selection changes in \fBMenuController\fP 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.MenuEventArgs\&.MenuEventArgs ()"

.SH "Property Documentation"
.PP 
.SS "bool FieldService\&.iOS\&.MenuEventArgs\&.Animated\fC [get]\fP, \fC [set]\fP"

.SS "NSIndexPath FieldService\&.iOS\&.MenuEventArgs\&.IndexPath\fC [get]\fP, \fC [set]\fP"

.SS "UITableView FieldService\&.iOS\&.MenuEventArgs\&.TableView\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
