.TH "FieldService.WinRT.Utilities" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.WinRT.Utilities \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBooleanToVisibilityConverter\fP"
.br
.RI "\fIConverts a Boolean into a Visibility\&. \fP"
.ti -1c
.RI "class \fBConstants\fP"
.br
.RI "\fIHolds constant values for \fBWinRT\fP \fP"
.ti -1c
.RI "class \fBDocumentSubheaderColorConverter\fP"
.br
.ti -1c
.RI "class \fBDocumentTypeToColorConverter\fP"
.br
.ti -1c
.RI "class \fBHelpers\fP"
.br
.RI "\fISet of helper methods for \fBWinRT\fP \fP"
.ti -1c
.RI "class \fBPhotoToImageConverter\fP"
.br
.ti -1c
.RI "class \fBStatusToColorConverter\fP"
.br
.RI "\fIConverter for converting an AssignmentStatus to a Brush \fP"
.ti -1c
.RI "class \fBTimer\fP"
.br
.RI "\fIThis is a wrapper around DispatcherTimer for \fBWinRT\fP It is for exposing methods identical to System\&.Timers\&.Timer, to make code simpler in view models using it \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
