.TH "FieldService.iOS.SignatureController" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.SignatureController \- 
.PP
Controller for displaying the popover for signatures  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UIPopoverController\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSignatureController\fP ()"
.br
.ti -1c
.RI "override void \fBDismiss\fP (bool animated)"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler \fBDismissed\fP"
.br
.RI "\fIOccurs when dismissed\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Controller for displaying the popover for signatures 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.SignatureController\&.SignatureController ()"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.iOS\&.SignatureController\&.Dismiss (boolanimated)"

.SH "Event Documentation"
.PP 
.SS "EventHandler FieldService\&.iOS\&.SignatureController\&.Dismissed"

.PP
Occurs when dismissed\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
