.TH "FieldService.Android.Dialogs.SignatureDialog" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Dialogs.SignatureDialog \- 
.PP
Dialog for capturing a signature  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.Android\&.Dialogs\&.BaseDialog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSignatureDialog\fP (\fBActivity\fP activity)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCreate\fP (Bundle bundle)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Activity \fBActivity\fP\fC [get, set]\fP"
.br
.RI "\fIThe activity holding this dialog \fP"
.ti -1c
.RI "\fBAssignment\fP \fBAssignment\fP\fC [get, set]\fP"
.br
.RI "\fIThe current assignment \fP"
.in -1c
.SH "Detailed Description"
.PP 
Dialog for capturing a signature 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.Dialogs\&.SignatureDialog\&.SignatureDialog (\fBActivity\fPactivity)"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.Android\&.Dialogs\&.SignatureDialog\&.OnCreate (Bundlebundle)\fC [protected]\fP"

.SH "Property Documentation"
.PP 
.SS "Activity FieldService\&.Android\&.Dialogs\&.SignatureDialog\&.Activity\fC [get]\fP, \fC [set]\fP"

.PP
The activity holding this dialog 
.SS "\fBAssignment\fP FieldService\&.Android\&.Dialogs\&.SignatureDialog\&.Assignment\fC [get]\fP, \fC [set]\fP"

.PP
The current assignment 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
