.TH "FieldService.ViewModels.MenuViewModel" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.ViewModels.MenuViewModel \- 
.PP
A simple ViewModel for coordinating menu changes within the app  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.ViewModels\&.ViewModelBase\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBMenuIndex\fP\fC [get, set]\fP"
.br
.RI "\fIThe current selected index for the menu in the split controller/fragment \fP"
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler \fBMenuIndexChanged\fP"
.br
.RI "\fIEvent when the menu index changes \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A simple ViewModel for coordinating menu changes within the app 


.SH "Property Documentation"
.PP 
.SS "int FieldService\&.ViewModels\&.MenuViewModel\&.MenuIndex\fC [get]\fP, \fC [set]\fP"

.PP
The current selected index for the menu in the split controller/fragment 
.SH "Event Documentation"
.PP 
.SS "EventHandler FieldService\&.ViewModels\&.MenuViewModel\&.MenuIndexChanged"

.PP
Event when the menu index changes 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
