.TH "FieldService.WinRT.Views.AddItemFlyoutPanel" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.WinRT.Views.AddItemFlyoutPanel \- 
.PP
Add item flyout panel  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UserControl\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddItemFlyoutPanel\fP ()"
.br
.ti -1c
.RI "async void \fBOnItemClick\fP (object sender, ItemClickEventArgs e)"
.br
.RI "\fIList view item click event \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnKeyDown\fP (KeyRoutedEventArgs e)"
.br
.RI "\fIUsed for hooking up enter key to search \fP"
.in -1c
.SH "Detailed Description"
.PP 
Add item flyout panel 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.WinRT\&.Views\&.AddItemFlyoutPanel\&.AddItemFlyoutPanel ()"

.SH "Member Function Documentation"
.PP 
.SS "async void FieldService\&.WinRT\&.Views\&.AddItemFlyoutPanel\&.OnItemClick (objectsender, ItemClickEventArgse)"

.PP
List view item click event 
.PP
\fBParameters:\fP
.RS 4
\fIsender\fP 
.br
\fIe\fP 
.RE
.PP

.SS "override void FieldService\&.WinRT\&.Views\&.AddItemFlyoutPanel\&.OnKeyDown (KeyRoutedEventArgse)\fC [protected]\fP"

.PP
Used for hooking up enter key to search 
.PP
\fBParameters:\fP
.RS 4
\fIe\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
