.TH "fieldservice.android.utilities.MapOverlayItem" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fieldservice.android.utilities.MapOverlayItem \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ItemizedOverlay, and IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMapOverlayItem\fP (android\&.graphics\&.drawable\&.Drawable p0)  throws java\&.lang\&.Throwable 	"
.br
.ti -1c
.RI "com\&.google\&.android\&.maps\&.OverlayItem \fBcreateItem\fP (int p0)"
.br
.ti -1c
.RI "int \fBsize\fP ()"
.br
.ti -1c
.RI "boolean \fBonTap\fP (int p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "fieldservice\&.android\&.utilities\&.MapOverlayItem\&.MapOverlayItem (android\&.graphics\&.drawable\&.Drawablep0) throws java\&.lang\&.Throwable"

.SH "Member Function Documentation"
.PP 
.SS "com\&.google\&.android\&.maps\&.OverlayItem fieldservice\&.android\&.utilities\&.MapOverlayItem\&.createItem (intp0)"

.SS "void fieldservice\&.android\&.utilities\&.MapOverlayItem\&.monodroidAddReference (java\&.lang\&.Objectobj)"

.SS "void fieldservice\&.android\&.utilities\&.MapOverlayItem\&.monodroidClearReferences ()"

.SS "boolean fieldservice\&.android\&.utilities\&.MapOverlayItem\&.onTap (intp0)"

.SS "int fieldservice\&.android\&.utilities\&.MapOverlayItem\&.size ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
