.TH "FieldService.iOS.SignatureCell" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.SignatureCell \- 
.PP
The table cell for adding signatures to an assignment  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UITableViewCell\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSignatureCell\fP (IntPtr handle)"
.br
.ti -1c
.RI "override void \fBAwakeFromNib\fP ()"
.br
.ti -1c
.RI "void \fBSetSignature\fP (\fBConfirmationController\fP controller, \fBAssignment\fP assignment, \fBData\&.Signature\fP signature)"
.br
.RI "\fISet the signature for this cell \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The table cell for adding signatures to an assignment 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.SignatureCell\&.SignatureCell (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.iOS\&.SignatureCell\&.AwakeFromNib ()"

.SS "override void FieldService\&.iOS\&.SignatureCell\&.Dispose (booldisposing)\fC [protected]\fP"

.SS "void FieldService\&.iOS\&.SignatureCell\&.SetSignature (\fBConfirmationController\fPcontroller, \fBAssignment\fPassignment, \fBData\&.Signature\fPsignature)"

.PP
Set the signature for this cell 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
