.TH "FieldService.Android.Adapters.DocumentsAdapter" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Adapters.DocumentsAdapter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ArrayAdapter< Document >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDocumentsAdapter\fP (Context context, int resourceId, List< \fBDocument\fP > documents)"
.br
.ti -1c
.RI "override View \fBGetView\fP (int position, View convertView, ViewGroup parent)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.Adapters\&.DocumentsAdapter\&.DocumentsAdapter (Contextcontext, intresourceId, List< \fBDocument\fP >documents)"

.SH "Member Function Documentation"
.PP 
.SS "override View FieldService\&.Android\&.Adapters\&.DocumentsAdapter\&.GetView (intposition, ViewconvertView, ViewGroupparent)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
