.TH "FieldService.Android.MapFragmentActivity" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.MapFragmentActivity \- 
.PP
'Fragment' for the map - it is required to be an activity although used as a fragment  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.Android\&.BaseMapActivity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMapFragmentActivity\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCreate\fP (Bundle bundle)"
.br
.ti -1c
.RI "override void \fBOnResume\fP ()"
.br
.RI "\fIEnable location tracking and place any overlays \fP"
.ti -1c
.RI "override void \fBOnPause\fP ()"
.br
.RI "\fIClear overlays and disable location tracking \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
'Fragment' for the map - it is required to be an activity although used as a fragment 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.MapFragmentActivity\&.MapFragmentActivity ()"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.Android\&.MapFragmentActivity\&.OnCreate (Bundlebundle)\fC [protected]\fP"

.SS "override void FieldService\&.Android\&.MapFragmentActivity\&.OnPause ()\fC [protected]\fP"

.PP
Clear overlays and disable location tracking 
.SS "override void FieldService\&.Android\&.MapFragmentActivity\&.OnResume ()\fC [protected]\fP"

.PP
Enable location tracking and place any overlays 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
