.TH "FieldService.Android.Adapters.HistoryListAdapter" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Adapters.HistoryListAdapter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ArrayAdapter< AssignmentHistory >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHistoryListAdapter\fP (Context context, int resourceId, List< \fBAssignmentHistory\fP > assignments)"
.br
.ti -1c
.RI "override View \fBGetView\fP (int position, View convertView, ViewGroup parent)"
.br
.ti -1c
.RI "void \fBFilterItems\fP (string filter)"
.br
.ti -1c
.RI "\fBAssignmentHistory\fP \fBGetAssignmentHistory\fP (int position)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBAssignment\fP \fBAssignment\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "override int \fBCount\fP hh\\:mm\\:ss'\fC [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.Adapters\&.HistoryListAdapter\&.HistoryListAdapter (Contextcontext, intresourceId, List< \fBAssignmentHistory\fP >assignments)"

.SH "Member Function Documentation"
.PP 
.SS "void FieldService\&.Android\&.Adapters\&.HistoryListAdapter\&.FilterItems (stringfilter)"

.SS "\fBAssignmentHistory\fP FieldService\&.Android\&.Adapters\&.HistoryListAdapter\&.GetAssignmentHistory (intposition)"

.SS "override View FieldService\&.Android\&.Adapters\&.HistoryListAdapter\&.GetView (intposition, ViewconvertView, ViewGroupparent)"

.SH "Property Documentation"
.PP 
.SS "\fBAssignment\fP FieldService\&.Android\&.Adapters\&.HistoryListAdapter\&.Assignment\fC [get]\fP, \fC [set]\fP"

.SS "override int FieldService\&.Android\&.Adapters\&.HistoryListAdapter\&.Count hh\\:mm\\:ss'\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
