.TH "FieldService.Android.Fragments.HistoryFragment" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Fragments.HistoryFragment \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Fragment\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTabContent\fP"
.br
.RI "\fICustom class to create tabs for the history fragment \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override View \fBOnCreateView\fP (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)"
.br
.ti -1c
.RI "override void \fBOnResume\fP ()"
.br
.ti -1c
.RI "override void \fBOnPause\fP ()"
.br
.ti -1c
.RI "override void \fBOnStop\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBAssignment\fP \fBAssignment\fP\fC [get, set]\fP"
.br
.RI "\fIthe selected assignment \fP"
.ti -1c
.RI "List< \fBAssignmentHistory\fP > \fBHistory\fP\fC [get, set]\fP"
.br
.RI "\fIlist of history items\&. \fP"
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override View FieldService\&.Android\&.Fragments\&.HistoryFragment\&.OnCreateView (LayoutInflaterinflater, ViewGroupcontainer, BundlesavedInstanceState)"

.SS "override void FieldService\&.Android\&.Fragments\&.HistoryFragment\&.OnPause ()"

.SS "override void FieldService\&.Android\&.Fragments\&.HistoryFragment\&.OnResume ()"

.SS "override void FieldService\&.Android\&.Fragments\&.HistoryFragment\&.OnStop ()"

.SH "Property Documentation"
.PP 
.SS "\fBAssignment\fP FieldService\&.Android\&.Fragments\&.HistoryFragment\&.Assignment\fC [get]\fP, \fC [set]\fP"

.PP
the selected assignment 
.SS "List<\fBAssignmentHistory\fP> FieldService\&.Android\&.Fragments\&.HistoryFragment\&.History\fC [get]\fP, \fC [set]\fP"

.PP
list of history items\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
