.TH "FieldService.iOS.MainMapController" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.MainMapController \- 
.PP
The controller for the main map with all the assignments on it  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.iOS\&.BaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainMapController\fP (IntPtr handle)"
.br
.ti -1c
.RI "override void \fBViewDidLoad\fP ()"
.br
.ti -1c
.RI "override void \fBViewWillAppear\fP (bool animated)"
.br
.ti -1c
.RI "override void \fBWillRotate\fP (UIInterfaceOrientation toInterfaceOrientation, double duration)"
.br
.RI "\fIWe override this to show/hide some controls during rotation \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The controller for the main map with all the assignments on it 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.MainMapController\&.MainMapController (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.iOS\&.MainMapController\&.Dispose (booldisposing)\fC [protected]\fP"

.SS "override void FieldService\&.iOS\&.MainMapController\&.ViewDidLoad ()"

.SS "override void FieldService\&.iOS\&.MainMapController\&.ViewWillAppear (boolanimated)"

.SS "override void FieldService\&.iOS\&.MainMapController\&.WillRotate (UIInterfaceOrientationtoInterfaceOrientation, doubleduration)"

.PP
We override this to show/hide some controls during rotation c 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
