.TH "FieldService.Android.Fragments.ItemFragment" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Fragments.ItemFragment \- 
.PP
Fragment for the items section  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Fragment\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override View \fBOnCreateView\fP (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)"
.br
.ti -1c
.RI "void \fBDeleteItem\fP (\fBAssignmentItem\fP item)"
.br
.RI "\fIDeletes an AssignmentItem \fP"
.ti -1c
.RI "void \fBReloadItems\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBAssignment\fP \fBAssignment\fP\fC [get, set]\fP"
.br
.RI "\fIThe currrent assignment \fP"
.ti -1c
.RI "List< \fBAssignmentItem\fP > \fBAssignmentItems\fP\fC [get, set]\fP"
.br
.RI "\fIList of assignment items \fP"
.in -1c
.SH "Detailed Description"
.PP 
Fragment for the items section 


.SH "Member Function Documentation"
.PP 
.SS "void FieldService\&.Android\&.Fragments\&.ItemFragment\&.DeleteItem (\fBAssignmentItem\fPitem)"

.PP
Deletes an AssignmentItem 
.SS "override View FieldService\&.Android\&.Fragments\&.ItemFragment\&.OnCreateView (LayoutInflaterinflater, ViewGroupcontainer, BundlesavedInstanceState)"

.SS "void FieldService\&.Android\&.Fragments\&.ItemFragment\&.ReloadItems ()"

.SH "Property Documentation"
.PP 
.SS "\fBAssignment\fP FieldService\&.Android\&.Fragments\&.ItemFragment\&.Assignment\fC [get]\fP, \fC [set]\fP"

.PP
The currrent assignment 
.SS "List<\fBAssignmentItem\fP> FieldService\&.Android\&.Fragments\&.ItemFragment\&.AssignmentItems\fC [get]\fP, \fC [set]\fP"

.PP
List of assignment items 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
