.TH "FieldService.WinRT.ViewModels.HistoryViewModel" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.WinRT.ViewModels.HistoryViewModel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.ViewModels\&.HistoryViewModel\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnPropertyChanged\fP (string propertyName)"
.br
.RI "\fIProtected method for firing PropertyChanged \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBAssignmentHistory\fP \fBRecentHistory\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.WinRT\&.ViewModels\&.HistoryViewModel\&.OnPropertyChanged (stringpropertyName)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Protected method for firing PropertyChanged 
.PP
\fBParameters:\fP
.RS 4
\fIpropertyName\fP The name of the property that changed
.RE
.PP

.PP
Reimplemented from \fBFieldService\&.Data\&.PropertyChangedBase\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBAssignmentHistory\fP FieldService\&.WinRT\&.ViewModels\&.HistoryViewModel\&.RecentHistory\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
