.TH "FieldService.Android.Resource.Style" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Resource.Style \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBCustomDialogTheme\fP = 2131099649"
.br
.ti -1c
.RI "const int \fBCustomHoloTheme\fP = 2131099648"
.br
.ti -1c
.RI "const int \fBMono_Android_Theme_Splash\fP = 2131099650"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const int FieldService\&.Android\&.Resource\&.Style\&.CustomDialogTheme = 2131099649"

.SS "const int FieldService\&.Android\&.Resource\&.Style\&.CustomHoloTheme = 2131099648"

.SS "const int FieldService\&.Android\&.Resource\&.Style\&.Mono_Android_Theme_Splash = 2131099650"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
