.TH "FieldService.WinRT.Views.AssignmentControl" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.WinRT.Views.AssignmentControl \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits UserControl\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssignmentControl\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.WinRT\&.Views\&.AssignmentControl\&.AssignmentControl ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
