.TH "FieldService.Android.Resource.Menu" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Resource.Menu \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBFragmentNavigationMenu\fP = 2131165184"
.br
.ti -1c
.RI "const int \fBSummaryMenu\fP = 2131165185"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const int FieldService\&.Android\&.Resource\&.Menu\&.FragmentNavigationMenu = 2131165184"

.SS "const int FieldService\&.Android\&.Resource\&.Menu\&.SummaryMenu = 2131165185"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
