.TH "FieldService.iOS.TextButton" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.TextButton \- 
.PP
This is a button for providing 2 lines of text and a nice icon to the left  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UIButton\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextButton\fP (IntPtr handle)"
.br
.ti -1c
.RI "override void \fBLayoutSubviews\fP ()"
.br
.RI "\fISet correct spacing for subviews \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "UIImage \fBIconImage\fP\fC [get, set]\fP"
.br
.RI "\fIIcon image used on the button to the left \fP"
.ti -1c
.RI "UILabel \fBTopLabel\fP\fC [get, set]\fP"
.br
.RI "\fITop label text \fP"
.ti -1c
.RI "UILabel \fBBottomLabel\fP\fC [get, set]\fP"
.br
.RI "\fISecond label text \fP"
.ti -1c
.RI "override bool \fBHighlighted\fP\fC [get, set]\fP"
.br
.RI "\fIOverride Highlighted so that the child controls function correctly \fP"
.in -1c
.SH "Detailed Description"
.PP 
This is a button for providing 2 lines of text and a nice icon to the left 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.TextButton\&.TextButton (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.iOS\&.TextButton\&.Dispose (booldisposing)\fC [protected]\fP"

.SS "override void FieldService\&.iOS\&.TextButton\&.LayoutSubviews ()"

.PP
Set correct spacing for subviews 
.SH "Property Documentation"
.PP 
.SS "UILabel FieldService\&.iOS\&.TextButton\&.BottomLabel\fC [get]\fP, \fC [set]\fP"

.PP
Second label text 
.SS "override bool FieldService\&.iOS\&.TextButton\&.Highlighted\fC [get]\fP, \fC [set]\fP"

.PP
Override Highlighted so that the child controls function correctly 
.SS "UIImage FieldService\&.iOS\&.TextButton\&.IconImage\fC [get]\fP, \fC [set]\fP"

.PP
Icon image used on the button to the left 
.SS "UILabel FieldService\&.iOS\&.TextButton\&.TopLabel\fC [get]\fP, \fC [set]\fP"

.PP
Top label text 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
