.TH "FieldService.Android.Resource.Drawable" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Resource.Drawable \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBaccept\fP = 2130837504"
.br
.ti -1c
.RI "const int \fBaccept_assignment\fP = 2130837505"
.br
.ti -1c
.RI "const int \fBAcceptedAssignmentIcon\fP = 2130837506"
.br
.ti -1c
.RI "const int \fBaction_bar_back\fP = 2130837507"
.br
.ti -1c
.RI "const int \fBactionbar\fP = 2130837508"
.br
.ti -1c
.RI "const int \fBactive_assignment_selector\fP = 2130837509"
.br
.ti -1c
.RI "const int \fBActiveAssignmentIcon\fP = 2130837510"
.br
.ti -1c
.RI "const int \fBassignment_list_selector\fP = 2130837511"
.br
.ti -1c
.RI "const int \fBback_button\fP = 2130837512"
.br
.ti -1c
.RI "const int \fBborder\fP = 2130837513"
.br
.ti -1c
.RI "const int \fBbottomSearchBar\fP = 2130837514"
.br
.ti -1c
.RI "const int \fBcameraIcon\fP = 2130837515"
.br
.ti -1c
.RI "const int \fBcancel_button\fP = 2130837516"
.br
.ti -1c
.RI "const int \fBclear_search_button\fP = 2130837517"
.br
.ti -1c
.RI "const int \fBclearIcon\fP = 2130837518"
.br
.ti -1c
.RI "const int \fBclearIconDown\fP = 2130837519"
.br
.ti -1c
.RI "const int \fBdarkPhoneIcon\fP = 2130837520"
.br
.ti -1c
.RI "const int \fBdecline\fP = 2130837521"
.br
.ti -1c
.RI "const int \fBdecline_assignment\fP = 2130837522"
.br
.ti -1c
.RI "const int \fBdocumentIcon\fP = 2130837523"
.br
.ti -1c
.RI "const int \fBdownlaborhours\fP = 2130837524"
.br
.ti -1c
.RI "const int \fBEnrouteImage\fP = 2130837525"
.br
.ti -1c
.RI "const int \fBget_directions_button\fP = 2130837526"
.br
.ti -1c
.RI "const int \fBHoldImage\fP = 2130837527"
.br
.ti -1c
.RI "const int \fBIcon\fP = 2130837528"
.br
.ti -1c
.RI "const int \fBItemPopupDivider\fP = 2130837529"
.br
.ti -1c
.RI "const int \fBitems_selector\fP = 2130837530"
.br
.ti -1c
.RI "const int \fBlabordescriptionbottom\fP = 2130837531"
.br
.ti -1c
.RI "const int \fBlaborHoursBottom\fP = 2130837532"
.br
.ti -1c
.RI "const int \fBLaborHoursDivider\fP = 2130837533"
.br
.ti -1c
.RI "const int \fBlogin_button\fP = 2130837534"
.br
.ti -1c
.RI "const int \fBloginbox\fP = 2130837535"
.br
.ti -1c
.RI "const int \fBMapIcon\fP = 2130837536"
.br
.ti -1c
.RI "const int \fBmapOverlay\fP = 2130837537"
.br
.ti -1c
.RI "const int \fBMapOverlayDirections\fP = 2130837538"
.br
.ti -1c
.RI "const int \fBMapOverlayDirectionsDown\fP = 2130837539"
.br
.ti -1c
.RI "const int \fBMapOverlayDivider\fP = 2130837540"
.br
.ti -1c
.RI "const int \fBMapOverlayIcon\fP = 2130837541"
.br
.ti -1c
.RI "const int \fBMapOverlayIconDown\fP = 2130837542"
.br
.ti -1c
.RI "const int \fBmonoandroidsplash\fP = 2130837543"
.br
.ti -1c
.RI "const int \fBnavigation_selector\fP = 2130837544"
.br
.ti -1c
.RI "const int \fBnavigationIcon\fP = 2130837545"
.br
.ti -1c
.RI "const int \fBNewAssignmentIcon\fP = 2130837546"
.br
.ti -1c
.RI "const int \fBNextButton\fP = 2130837547"
.br
.ti -1c
.RI "const int \fBPhoneIcon\fP = 2130837548"
.br
.ti -1c
.RI "const int \fBPreviousButton\fP = 2130837549"
.br
.ti -1c
.RI "const int \fBquestionmark\fP = 2130837550"
.br
.ti -1c
.RI "const int \fBroundedblack\fP = 2130837551"
.br
.ti -1c
.RI "const int \fBSearchIcon\fP = 2130837552"
.br
.ti -1c
.RI "const int \fBSelectedItem\fP = 2130837553"
.br
.ti -1c
.RI "const int \fBsmallBlueRectangle\fP = 2130837554"
.br
.ti -1c
.RI "const int \fBsummary_timer\fP = 2130837555"
.br
.ti -1c
.RI "const int \fBSummaryPause\fP = 2130837556"
.br
.ti -1c
.RI "const int \fBSummaryRecord\fP = 2130837557"
.br
.ti -1c
.RI "const int \fBtab_selected\fP = 2130837558"
.br
.ti -1c
.RI "const int \fBtab_selector\fP = 2130837559"
.br
.ti -1c
.RI "const int \fBtab_unselected\fP = 2130837560"
.br
.ti -1c
.RI "const int \fBtimer_selector\fP = 2130837561"
.br
.ti -1c
.RI "const int \fBTimerPause\fP = 2130837562"
.br
.ti -1c
.RI "const int \fBTimerRecord\fP = 2130837563"
.br
.ti -1c
.RI "const int \fBTrashCanIcon\fP = 2130837564"
.br
.ti -1c
.RI "const int \fBtriangleblue\fP = 2130837565"
.br
.ti -1c
.RI "const int \fBtriangledark\fP = 2130837566"
.br
.ti -1c
.RI "const int \fBtrianglegrey\fP = 2130837567"
.br
.ti -1c
.RI "const int \fBtrianglewhite\fP = 2130837568"
.br
.ti -1c
.RI "const int \fBUpLaborHours\fP = 2130837569"
.br
.ti -1c
.RI "const int \fBXamarinTitle\fP = 2130837570"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.accept = 2130837504"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.accept_assignment = 2130837505"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.AcceptedAssignmentIcon = 2130837506"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.action_bar_back = 2130837507"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.actionbar = 2130837508"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.active_assignment_selector = 2130837509"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.ActiveAssignmentIcon = 2130837510"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.assignment_list_selector = 2130837511"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.back_button = 2130837512"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.border = 2130837513"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.bottomSearchBar = 2130837514"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.cameraIcon = 2130837515"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.cancel_button = 2130837516"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.clear_search_button = 2130837517"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.clearIcon = 2130837518"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.clearIconDown = 2130837519"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.darkPhoneIcon = 2130837520"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.decline = 2130837521"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.decline_assignment = 2130837522"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.documentIcon = 2130837523"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.downlaborhours = 2130837524"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.EnrouteImage = 2130837525"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.get_directions_button = 2130837526"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.HoldImage = 2130837527"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.Icon = 2130837528"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.ItemPopupDivider = 2130837529"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.items_selector = 2130837530"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.labordescriptionbottom = 2130837531"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.laborHoursBottom = 2130837532"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.LaborHoursDivider = 2130837533"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.login_button = 2130837534"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.loginbox = 2130837535"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.MapIcon = 2130837536"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.mapOverlay = 2130837537"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.MapOverlayDirections = 2130837538"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.MapOverlayDirectionsDown = 2130837539"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.MapOverlayDivider = 2130837540"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.MapOverlayIcon = 2130837541"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.MapOverlayIconDown = 2130837542"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.monoandroidsplash = 2130837543"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.navigation_selector = 2130837544"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.navigationIcon = 2130837545"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.NewAssignmentIcon = 2130837546"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.NextButton = 2130837547"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.PhoneIcon = 2130837548"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.PreviousButton = 2130837549"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.questionmark = 2130837550"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.roundedblack = 2130837551"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.SearchIcon = 2130837552"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.SelectedItem = 2130837553"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.smallBlueRectangle = 2130837554"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.summary_timer = 2130837555"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.SummaryPause = 2130837556"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.SummaryRecord = 2130837557"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.tab_selected = 2130837558"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.tab_selector = 2130837559"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.tab_unselected = 2130837560"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.timer_selector = 2130837561"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.TimerPause = 2130837562"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.TimerRecord = 2130837563"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.TrashCanIcon = 2130837564"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.triangleblue = 2130837565"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.triangledark = 2130837566"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.trianglegrey = 2130837567"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.trianglewhite = 2130837568"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.UpLaborHours = 2130837569"

.SS "const int FieldService\&.Android\&.Resource\&.Drawable\&.XamarinTitle = 2130837570"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
