.TH "FieldService.iOS.AssignmentStatusSheet" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.AssignmentStatusSheet \- 
.PP
A UIActionSheet that provides AssignmentStatus as a selection  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UIActionSheet\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssignmentStatusSheet\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBAssignmentStatus\fP \fBStatus\fP\fC [get, set]\fP"
.br
.RI "\fIThe selected status \fP"
.in -1c
.SH "Detailed Description"
.PP 
A UIActionSheet that provides AssignmentStatus as a selection 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.AssignmentStatusSheet\&.AssignmentStatusSheet ()"

.SH "Property Documentation"
.PP 
.SS "\fBAssignmentStatus\fP FieldService\&.iOS\&.AssignmentStatusSheet\&.Status\fC [get]\fP, \fC [set]\fP"

.PP
The selected status 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
