.TH "fieldservice.android.fragments.NavigationFragment_NavigationItemSelectorListener" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fieldservice.android.fragments.NavigationFragment_NavigationItemSelectorListener \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Object, IGCUserPeer, and OnItemClickListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNavigationFragment_NavigationItemSelectorListener\fP ()  throws java\&.lang\&.Throwable 	"
.br
.ti -1c
.RI "\fBNavigationFragment_NavigationItemSelectorListener\fP (\fBfieldservice\&.android\&.fragments\&.NavigationFragment\fP p0)  throws java\&.lang\&.Throwable 	"
.br
.ti -1c
.RI "void \fBonItemClick\fP (android\&.widget\&.AdapterView p0, android\&.view\&.View p1, int p2, long p3)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "fieldservice\&.android\&.fragments\&.NavigationFragment_NavigationItemSelectorListener\&.NavigationFragment_NavigationItemSelectorListener () throws java\&.lang\&.Throwable"

.SS "fieldservice\&.android\&.fragments\&.NavigationFragment_NavigationItemSelectorListener\&.NavigationFragment_NavigationItemSelectorListener (\fBfieldservice\&.android\&.fragments\&.NavigationFragment\fPp0) throws java\&.lang\&.Throwable"

.SH "Member Function Documentation"
.PP 
.SS "void fieldservice\&.android\&.fragments\&.NavigationFragment_NavigationItemSelectorListener\&.monodroidAddReference (java\&.lang\&.Objectobj)"

.SS "void fieldservice\&.android\&.fragments\&.NavigationFragment_NavigationItemSelectorListener\&.monodroidClearReferences ()"

.SS "void fieldservice\&.android\&.fragments\&.NavigationFragment_NavigationItemSelectorListener\&.onItemClick (android\&.widget\&.AdapterViewp0, android\&.view\&.Viewp1, intp2, longp3)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
