.TH "FieldService.Android.LaborHoursAdapter" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.LaborHoursAdapter \- 
.PP
Adapter for a list of labor entries  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ArrayAdapter< Labor >, and IOnItemSelectedListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLaborHoursAdapter\fP (Activity activity, int resourceId, List< \fBLabor\fP > laborHours)"
.br
.ti -1c
.RI "override View \fBGetView\fP (int position, View convertView, ViewGroup parent)"
.br
.ti -1c
.RI "void \fBOnItemSelected\fP (AdapterView parent, View view, int position, long id)"
.br
.ti -1c
.RI "void \fBOnNothingSelected\fP (AdapterView parent)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBAssignment\fP \fBAssignment\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBLaborHourFragment\fP \fBFragment\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Adapter for a list of labor entries 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.LaborHoursAdapter\&.LaborHoursAdapter (Activityactivity, intresourceId, List< \fBLabor\fP >laborHours)"

.SH "Member Function Documentation"
.PP 
.SS "override View FieldService\&.Android\&.LaborHoursAdapter\&.GetView (intposition, ViewconvertView, ViewGroupparent)"

.SS "void FieldService\&.Android\&.LaborHoursAdapter\&.OnItemSelected (AdapterViewparent, Viewview, intposition, longid)"

.SS "void FieldService\&.Android\&.LaborHoursAdapter\&.OnNothingSelected (AdapterViewparent)"

.SH "Property Documentation"
.PP 
.SS "\fBAssignment\fP FieldService\&.Android\&.LaborHoursAdapter\&.Assignment\fC [get]\fP, \fC [set]\fP"

.SS "\fBLaborHourFragment\fP FieldService\&.Android\&.LaborHoursAdapter\&.Fragment\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
