.TH "FieldService.Android.Dialogs.BaseDialog" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Dialogs.BaseDialog \- 
.PP
Base dialog class, mainly for setting the CustomDialogTheme  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Dialog\&.
.PP
Inherited by \fBFieldService\&.Android\&.Dialogs\&.AddLaborDialog\fP, \fBFieldService\&.Android\&.Dialogs\&.ExpenseDialog\fP, \fBFieldService\&.Android\&.Dialogs\&.ItemsDialog\fP, \fBFieldService\&.Android\&.Dialogs\&.PhotoDialog\fP, and \fBFieldService\&.Android\&.Dialogs\&.SignatureDialog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseDialog\fP (Context context)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base dialog class, mainly for setting the CustomDialogTheme 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.Dialogs\&.BaseDialog\&.BaseDialog (Contextcontext)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
