.TH "FieldService.iOS.ConfirmationController" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.ConfirmationController \- 
.PP
Controller for the confirmation screen  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.iOS\&.BaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfirmationController\fP (IntPtr handle)"
.br
.ti -1c
.RI "override void \fBViewDidLoad\fP ()"
.br
.ti -1c
.RI "override void \fBViewWillAppear\fP (bool animated)"
.br
.ti -1c
.RI "void \fBReloadConfirmation\fP ()"
.br
.RI "\fILoads the confirmation screen's info \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Controller for the confirmation screen 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.ConfirmationController\&.ConfirmationController (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "void FieldService\&.iOS\&.ConfirmationController\&.ReloadConfirmation ()"

.PP
Loads the confirmation screen's info 
.SS "override void FieldService\&.iOS\&.ConfirmationController\&.ViewDidLoad ()"

.SS "override void FieldService\&.iOS\&.ConfirmationController\&.ViewWillAppear (boolanimated)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
