.TH "FieldService.Android.ItemsSearchAdapter" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.ItemsSearchAdapter \- 
.PP
Adapter for searching through a list of items  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ArrayAdapter< Item >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBItemsSearchAdapter\fP (Context context, int resourceId, IList< \fBItem\fP > items)"
.br
.ti -1c
.RI "override View \fBGetView\fP (int position, View convertView, ViewGroup parent)"
.br
.ti -1c
.RI "void \fBFilterItems\fP (string filter)"
.br
.ti -1c
.RI "\fBItem\fP \fBGetAssignmentItem\fP (int position)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override int \fBCount\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Adapter for searching through a list of items 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.ItemsSearchAdapter\&.ItemsSearchAdapter (Contextcontext, intresourceId, IList< \fBItem\fP >items)"

.SH "Member Function Documentation"
.PP 
.SS "void FieldService\&.Android\&.ItemsSearchAdapter\&.FilterItems (stringfilter)"

.SS "\fBItem\fP FieldService\&.Android\&.ItemsSearchAdapter\&.GetAssignmentItem (intposition)"

.SS "override View FieldService\&.Android\&.ItemsSearchAdapter\&.GetView (intposition, ViewconvertView, ViewGroupparent)"

.SH "Property Documentation"
.PP 
.SS "override int FieldService\&.Android\&.ItemsSearchAdapter\&.Count\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
