.TH "FieldService.iOS.HistoryCell" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.HistoryCell \- 
.PP
History table view cell  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UITableViewCell\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHistoryCell\fP (IntPtr handle)"
.br
.ti -1c
.RI "void \fBSetHistory\fP (\fBAssignmentHistory\fP history, bool enabled)"
.br
.RI "\fISets up the history record for this cell \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.in -1c
.SH "Detailed Description"
.PP 
History table view cell 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.HistoryCell\&.HistoryCell (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.iOS\&.HistoryCell\&.Dispose (booldisposing)\fC [protected]\fP"

.SS "void FieldService\&.iOS\&.HistoryCell\&.SetHistory (\fBAssignmentHistory\fPhistory, boolenabled)"

.PP
Sets up the history record for this cell 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
