.TH "FieldService.Utilities.ServiceContainer" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Utilities.ServiceContainer \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBRegister< T >\fP (T service)"
.br
.ti -1c
.RI "static void \fBRegister< T >\fP ()"
.br
.ti -1c
.RI "static void \fBRegister< T >\fP (Func< object > function)"
.br
.ti -1c
.RI "static T \fBResolve< T >\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void FieldService\&.Utilities\&.ServiceContainer\&.Register< T > (Tservice)\fC [static]\fP"

.SS "static void FieldService\&.Utilities\&.ServiceContainer\&.Register< T > ()\fC [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fInew\fP
.SS "static void FieldService\&.Utilities\&.ServiceContainer\&.Register< T > (Func< object >function)\fC [static]\fP"

.SS "static T FieldService\&.Utilities\&.ServiceContainer\&.Resolve< T > ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
