.TH "FieldService.Android.Fragments.SummaryFragment" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Fragments.SummaryFragment \- 
.PP
Fragment for the summary screen  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Fragment\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override View \fBOnCreateView\fP (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBAssignment\fP \fBAssignment\fP\fC [get, set]\fP"
.br
.RI "\fIThe selected assignment \fP"
.in -1c
.SH "Detailed Description"
.PP 
Fragment for the summary screen 


.SH "Member Function Documentation"
.PP 
.SS "override View FieldService\&.Android\&.Fragments\&.SummaryFragment\&.OnCreateView (LayoutInflaterinflater, ViewGroupcontainer, BundlesavedInstanceState)"

.SH "Property Documentation"
.PP 
.SS "\fBAssignment\fP FieldService\&.Android\&.Fragments\&.SummaryFragment\&.Assignment\fC [get]\fP, \fC [set]\fP"

.PP
The selected assignment 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
