.TH "FieldService.iOS.AddItemController" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.AddItemController \- 
.PP
Modal view controller for adding items to an assignment  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UIViewController\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddItemController\fP (IntPtr handle)"
.br
.ti -1c
.RI "override void \fBViewDidLoad\fP ()"
.br
.ti -1c
.RI "override void \fBViewWillAppear\fP (bool animated)"
.br
.ti -1c
.RI "override void \fBViewWillDisappear\fP (bool animated)"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler \fBDismissed\fP"
.br
.RI "\fIOccurs when dismissed\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Modal view controller for adding items to an assignment 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.AddItemController\&.AddItemController (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.iOS\&.AddItemController\&.ViewDidLoad ()"

.SS "override void FieldService\&.iOS\&.AddItemController\&.ViewWillAppear (boolanimated)"

.SS "override void FieldService\&.iOS\&.AddItemController\&.ViewWillDisappear (boolanimated)"

.SH "Event Documentation"
.PP 
.SS "EventHandler FieldService\&.iOS\&.AddItemController\&.Dismissed"

.PP
Occurs when dismissed\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
