.TH "FieldService.iOS.BaseNavigationController" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.BaseNavigationController \- 
.PP
Base navigation controller, used in a couple places throughout our Storyboard file  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UINavigationController\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseNavigationController\fP (IntPtr handle)"
.br
.ti -1c
.RI "override void \fBViewDidLoad\fP ()"
.br
.ti -1c
.RI "override UIStatusBarStyle \fBPreferredStatusBarStyle\fP ()"
.br
.ti -1c
.RI "override bool \fBShouldAutorotate\fP ()"
.br
.RI "\fIThis is how orientation is setup on \fBiOS\fP 6 \fP"
.ti -1c
.RI "override UIInterfaceOrientationMask \fBGetSupportedInterfaceOrientations\fP ()"
.br
.RI "\fIThis is how orientation is setup on \fBiOS\fP 6 \fP"
.in -1c
.SH "Detailed Description"
.PP 
Base navigation controller, used in a couple places throughout our Storyboard file 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.BaseNavigationController\&.BaseNavigationController (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "override UIInterfaceOrientationMask FieldService\&.iOS\&.BaseNavigationController\&.GetSupportedInterfaceOrientations ()"

.PP
This is how orientation is setup on \fBiOS\fP 6 
.SS "override UIStatusBarStyle FieldService\&.iOS\&.BaseNavigationController\&.PreferredStatusBarStyle ()"

.SS "override bool FieldService\&.iOS\&.BaseNavigationController\&.ShouldAutorotate ()"

.PP
This is how orientation is setup on \fBiOS\fP 6 
.SS "override void FieldService\&.iOS\&.BaseNavigationController\&.ViewDidLoad ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
