.TH "FieldService.Android.ExpensesAdapter" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.ExpensesAdapter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ArrayAdapter< Expense >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExpensesAdapter\fP (Context context, int resourceId, List< \fBExpense\fP > expenses)"
.br
.ti -1c
.RI "override View \fBGetView\fP (int position, View convertView, ViewGroup parent)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.ExpensesAdapter\&.ExpensesAdapter (Contextcontext, intresourceId, List< \fBExpense\fP >expenses)"

.SH "Member Function Documentation"
.PP 
.SS "override View FieldService\&.Android\&.ExpensesAdapter\&.GetView (intposition, ViewconvertView, ViewGroupparent)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
