.TH "FieldService.Android.BaseActivity" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.BaseActivity \- 
.PP
Base activity for all activities, handles global OnPause/OnResume  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Activity\&.
.PP
Inherited by \fBFieldService\&.Android\&.AssignmentsActivity\fP, \fBFieldService\&.Android\&.AssignmentTabActivity\fP, and \fBFieldService\&.Android\&.SummaryActivity\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnPause\fP ()"
.br
.ti -1c
.RI "override void \fBOnResume\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base activity for all activities, handles global OnPause/OnResume 


.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.Android\&.BaseActivity\&.OnPause ()\fC [protected]\fP"

.SS "override void FieldService\&.Android\&.BaseActivity\&.OnResume ()\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
