.TH "FieldService.iOS.LoginController" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.LoginController \- 
.PP
Controller for the login screen  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.iOS\&.BaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoginController\fP (IntPtr handle)"
.br
.ti -1c
.RI "override void \fBViewDidLoad\fP ()"
.br
.ti -1c
.RI "override void \fBViewWillAppear\fP (bool animated)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.ti -1c
.RI "override void \fBOnKeyboardChanged\fP (bool visible, float height)"
.br
.RI "\fIOverride this method to apply custom logic when the keyboard is shown/hidden \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBHandlesKeyboardNotifications\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Controller for the login screen 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.LoginController\&.LoginController (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.iOS\&.LoginController\&.Dispose (booldisposing)\fC [protected]\fP"

.SS "override void FieldService\&.iOS\&.LoginController\&.OnKeyboardChanged (boolvisible, floatheight)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to apply custom logic when the keyboard is shown/hidden 
.PP
\fBParameters:\fP
.RS 4
\fIvisible\fP If the keyboard is visible 
.br
\fIheight\fP Calculated height of the keyboard (width not generally needed here) 
.RE
.PP

.PP
Reimplemented from \fBFieldService\&.iOS\&.BaseController\fP\&.
.SS "override void FieldService\&.iOS\&.LoginController\&.ViewDidLoad ()"

.SS "override void FieldService\&.iOS\&.LoginController\&.ViewWillAppear (boolanimated)"

.SH "Property Documentation"
.PP 
.SS "override bool FieldService\&.iOS\&.LoginController\&.HandlesKeyboardNotifications\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
