.TH "FieldService.iOS.AddLaborController" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.AddLaborController \- 
.PP
Controller for manually adding labor to an assignment  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.iOS\&.BaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddLaborController\fP (IntPtr handle)"
.br
.ti -1c
.RI "override void \fBViewDidLoad\fP ()"
.br
.ti -1c
.RI "override void \fBViewWillAppear\fP (bool animated)"
.br
.ti -1c
.RI "override void \fBViewWillDisappear\fP (bool animated)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBDisablesAutomaticKeyboardDismissal\fP\fC [get]\fP"
.br
.RI "\fIOverriding this allows us to dismiss the keyboard programmatically from a modal controller \fP"
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler \fBDismissed\fP"
.br
.RI "\fIOccurs when dismissed\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Controller for manually adding labor to an assignment 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.AddLaborController\&.AddLaborController (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.iOS\&.AddLaborController\&.ViewDidLoad ()"

.SS "override void FieldService\&.iOS\&.AddLaborController\&.ViewWillAppear (boolanimated)"

.SS "override void FieldService\&.iOS\&.AddLaborController\&.ViewWillDisappear (boolanimated)"

.SH "Property Documentation"
.PP 
.SS "override bool FieldService\&.iOS\&.AddLaborController\&.DisablesAutomaticKeyboardDismissal\fC [get]\fP"

.PP
Overriding this allows us to dismiss the keyboard programmatically from a modal controller 
.SH "Event Documentation"
.PP 
.SS "EventHandler FieldService\&.iOS\&.AddLaborController\&.Dismissed"

.PP
Occurs when dismissed\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
