.TH "FieldService.iOS.PhotoAlertSheet" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.PhotoAlertSheet \- 
.PP
Alert sheet for choosing a photo  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UIActionSheet\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPhotoAlertSheet\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "SizeF \fBDesiredSize\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the size to scale the image to, SizeF\&.Zero turns off sizing \fP"
.ti -1c
.RI "Action< UIImage > \fBCallback\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the callback for when an image is selected and resized \fP"
.in -1c
.SH "Detailed Description"
.PP 
Alert sheet for choosing a photo 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.PhotoAlertSheet\&.PhotoAlertSheet ()"

.SH "Property Documentation"
.PP 
.SS "Action<UIImage> FieldService\&.iOS\&.PhotoAlertSheet\&.Callback\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the callback for when an image is selected and resized 
.SS "SizeF FieldService\&.iOS\&.PhotoAlertSheet\&.DesiredSize\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the size to scale the image to, SizeF\&.Zero turns off sizing 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
