.TH "FieldService.iOS.DocumentController" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.DocumentController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.iOS\&.BaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDocumentController\fP (IntPtr handle)"
.br
.ti -1c
.RI "override void \fBViewDidLoad\fP ()"
.br
.ti -1c
.RI "override void \fBViewWillAppear\fP (bool animated)"
.br
.ti -1c
.RI "void \fBReloadDocuments\fP ()"
.br
.RI "\fIReload the documents \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.DocumentController\&.DocumentController (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "void FieldService\&.iOS\&.DocumentController\&.ReloadDocuments ()"

.PP
Reload the documents 
.SS "override void FieldService\&.iOS\&.DocumentController\&.ViewDidLoad ()"

.SS "override void FieldService\&.iOS\&.DocumentController\&.ViewWillAppear (boolanimated)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
