.TH "FieldService.iOS.AssignmentItemCell" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.AssignmentItemCell \- 
.PP
Table cell for assignment items  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UITableViewCell\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssignmentItemCell\fP (IntPtr handle)"
.br
.ti -1c
.RI "override void \fBAwakeFromNib\fP ()"
.br
.ti -1c
.RI "void \fBSetItem\fP (\fBAssignmentItem\fP item)"
.br
.RI "\fISets the current assignment item \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Table cell for assignment items 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.AssignmentItemCell\&.AssignmentItemCell (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.iOS\&.AssignmentItemCell\&.AwakeFromNib ()"

.SS "override void FieldService\&.iOS\&.AssignmentItemCell\&.Dispose (booldisposing)\fC [protected]\fP"

.SS "void FieldService\&.iOS\&.AssignmentItemCell\&.SetItem (\fBAssignmentItem\fPitem)"

.PP
Sets the current assignment item 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
