.TH "FieldService" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBAndroid\fP"
.br
.ti -1c
.RI "package \fBData\fP"
.br
.ti -1c
.RI "package \fBiOS\fP"
.br
.ti -1c
.RI "package \fBTests\fP"
.br
.ti -1c
.RI "package \fBUtilities\fP"
.br
.ti -1c
.RI "package \fBViewModels\fP"
.br
.ti -1c
.RI "package \fBWinRT\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCatalog\fP"
.br
.RI "\fIStatic class containing strings used throughout the app \fP"
.ti -1c
.RI "interface \fBIAssignmentService\fP"
.br
.RI "\fIService for returning and saving assignment information \fP"
.ti -1c
.RI "interface \fBILoginService\fP"
.br
.RI "\fIInterface providing backend data to \fBViewModels\fP \fP"
.ti -1c
.RI "class \fBServiceRegistrar\fP"
.br
.RI "\fIClass for registering services for the app \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
