.TH "FieldService.WinRT.App" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.WinRT.App \- 
.PP
Provides application-specific behavior to supplement the default Application class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Application\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBApp\fP ()"
.br
.RI "\fIInitializes the singleton application object\&. This is the first line of authored code executed, and as such is the logical equivalent of main() or WinMain()\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnLaunched\fP (LaunchActivatedEventArgs args)"
.br
.RI "\fIInvoked when the application is launched normally by the end user\&. Other entry points will be used when the application is launched to open a specific file, to display search results, and so forth\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Frame \fBRootFrame\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides application-specific behavior to supplement the default Application class\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.WinRT\&.App\&.App ()"

.PP
Initializes the singleton application object\&. This is the first line of authored code executed, and as such is the logical equivalent of main() or WinMain()\&. 
.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.WinRT\&.App\&.OnLaunched (LaunchActivatedEventArgsargs)\fC [protected]\fP"

.PP
Invoked when the application is launched normally by the end user\&. Other entry points will be used when the application is launched to open a specific file, to display search results, and so forth\&. 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP Details about the launch request and process\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "Frame FieldService\&.WinRT\&.App\&.RootFrame\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
