.TH "fieldservice.android.SpinnerAdapter_1" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fieldservice.android.SpinnerAdapter_1 \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseAdapter, IGCUserPeer, SpinnerAdapter, and Adapter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpinnerAdapter_1\fP ()  throws java\&.lang\&.Throwable 	"
.br
.ti -1c
.RI "int \fBgetCount\fP ()"
.br
.ti -1c
.RI "java\&.lang\&.Object \fBgetItem\fP (int p0)"
.br
.ti -1c
.RI "long \fBgetItemId\fP (int p0)"
.br
.ti -1c
.RI "android\&.view\&.View \fBgetView\fP (int p0, android\&.view\&.View p1, android\&.view\&.ViewGroup p2)"
.br
.ti -1c
.RI "android\&.view\&.View \fBgetDropDownView\fP (int p0, android\&.view\&.View p1, android\&.view\&.ViewGroup p2)"
.br
.ti -1c
.RI "boolean \fBhasStableIds\fP ()"
.br
.ti -1c
.RI "boolean \fBisEmpty\fP ()"
.br
.ti -1c
.RI "int \fBgetViewTypeCount\fP ()"
.br
.ti -1c
.RI "int \fBgetItemViewType\fP (int p0)"
.br
.ti -1c
.RI "void \fBregisterDataSetObserver\fP (android\&.database\&.DataSetObserver p0)"
.br
.ti -1c
.RI "void \fBunregisterDataSetObserver\fP (android\&.database\&.DataSetObserver p0)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "fieldservice\&.android\&.SpinnerAdapter_1\&.SpinnerAdapter_1 () throws java\&.lang\&.Throwable"

.SH "Member Function Documentation"
.PP 
.SS "int fieldservice\&.android\&.SpinnerAdapter_1\&.getCount ()"

.SS "android\&.view\&.View fieldservice\&.android\&.SpinnerAdapter_1\&.getDropDownView (intp0, android\&.view\&.Viewp1, android\&.view\&.ViewGroupp2)"

.SS "java\&.lang\&.Object fieldservice\&.android\&.SpinnerAdapter_1\&.getItem (intp0)"

.SS "long fieldservice\&.android\&.SpinnerAdapter_1\&.getItemId (intp0)"

.SS "int fieldservice\&.android\&.SpinnerAdapter_1\&.getItemViewType (intp0)"

.SS "android\&.view\&.View fieldservice\&.android\&.SpinnerAdapter_1\&.getView (intp0, android\&.view\&.Viewp1, android\&.view\&.ViewGroupp2)"

.SS "int fieldservice\&.android\&.SpinnerAdapter_1\&.getViewTypeCount ()"

.SS "boolean fieldservice\&.android\&.SpinnerAdapter_1\&.hasStableIds ()"

.SS "boolean fieldservice\&.android\&.SpinnerAdapter_1\&.isEmpty ()"

.SS "void fieldservice\&.android\&.SpinnerAdapter_1\&.monodroidAddReference (java\&.lang\&.Objectobj)"

.SS "void fieldservice\&.android\&.SpinnerAdapter_1\&.monodroidClearReferences ()"

.SS "void fieldservice\&.android\&.SpinnerAdapter_1\&.registerDataSetObserver (android\&.database\&.DataSetObserverp0)"

.SS "void fieldservice\&.android\&.SpinnerAdapter_1\&.unregisterDataSetObserver (android\&.database\&.DataSetObserverp0)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
