.TH "FieldService.ViewModels" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.ViewModels \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAssignmentViewModel\fP"
.br
.RI "\fIView model for assignments list \fP"
.ti -1c
.RI "class \fBDocumentViewModel\fP"
.br
.RI "\fIViewModel for managing documents \fP"
.ti -1c
.RI "class \fBExpenseViewModel\fP"
.br
.RI "\fIViewModel for expense \fP"
.ti -1c
.RI "class \fBHistoryViewModel\fP"
.br
.RI "\fIViewModel for assignment history \fP"
.ti -1c
.RI "class \fBItemViewModel\fP"
.br
.RI "\fIViewModel for working with items \fP"
.ti -1c
.RI "class \fBLaborViewModel\fP"
.br
.RI "\fIView model for labor hours \fP"
.ti -1c
.RI "class \fBLoginViewModel\fP"
.br
.RI "\fIViewModel class for the Login screen \fP"
.ti -1c
.RI "class \fBMenuViewModel\fP"
.br
.RI "\fIA simple ViewModel for coordinating menu changes within the app \fP"
.ti -1c
.RI "class \fBPhotoViewModel\fP"
.br
.RI "\fIViewModel for working with photos \fP"
.ti -1c
.RI "class \fBViewModelBase\fP"
.br
.RI "\fIBase class for all view models \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
