.TH "FieldService.Android.Utilities.SynchronizeInvoke" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Utilities.SynchronizeInvoke \- 
.PP
\fBAndroid\fP implementation of ISynchronizeInvoke  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ISynchronizeInvoke\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "IAsyncResult \fBBeginInvoke\fP (Delegate method, object[] args)"
.br
.ti -1c
.RI "object \fBEndInvoke\fP (IAsyncResult result)"
.br
.ti -1c
.RI "object \fBInvoke\fP (Delegate method, object[] args)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Activity \fBActivity\fP\fC [get, set]\fP"
.br
.RI "\fIAn activity is required for RunOnUiThread \fP"
.ti -1c
.RI "bool \fBInvokeRequired\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAndroid\fP implementation of ISynchronizeInvoke 


.SH "Member Function Documentation"
.PP 
.SS "IAsyncResult FieldService\&.Android\&.Utilities\&.SynchronizeInvoke\&.BeginInvoke (Delegatemethod, object[]args)"

.SS "object FieldService\&.Android\&.Utilities\&.SynchronizeInvoke\&.EndInvoke (IAsyncResultresult)"

.SS "object FieldService\&.Android\&.Utilities\&.SynchronizeInvoke\&.Invoke (Delegatemethod, object[]args)"

.SH "Property Documentation"
.PP 
.SS "Activity FieldService\&.Android\&.Utilities\&.SynchronizeInvoke\&.Activity\fC [get]\fP, \fC [set]\fP"

.PP
An activity is required for RunOnUiThread 
.SS "bool FieldService\&.Android\&.Utilities\&.SynchronizeInvoke\&.InvokeRequired\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
