.TH "FieldService.Tests.Data.SampleAssignmentServiceTests" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Tests.Data.SampleAssignmentServiceTests \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP ()"
.br
.ti -1c
.RI "void \fBGetAssignments\fP ()"
.br
.ti -1c
.RI "void \fBGetAssignmentAndCheckTotalHours\fP ()"
.br
.ti -1c
.RI "void \fBGetAssignmentAndCheckTotalItems\fP ()"
.br
.ti -1c
.RI "void \fBGetAssignmentAndCheckTotalExpenses\fP ()"
.br
.ti -1c
.RI "void \fBSaveAssignment\fP ()"
.br
.ti -1c
.RI "void \fBSaveAssignmentItemInsert\fP ()"
.br
.ti -1c
.RI "void \fBSaveAssignmentItemUpdate\fP ()"
.br
.ti -1c
.RI "void \fBSaveLaborInsert\fP ()"
.br
.ti -1c
.RI "void \fBSaveLaborUpdate\fP ()"
.br
.ti -1c
.RI "void \fBSaveExpenseInsert\fP ()"
.br
.ti -1c
.RI "void \fBSaveExpenseUpdate\fP ()"
.br
.ti -1c
.RI "void \fBGetItems\fP ()"
.br
.ti -1c
.RI "void \fBGetAssignmentItems\fP ()"
.br
.ti -1c
.RI "void \fBGetAssignmentLabor\fP ()"
.br
.ti -1c
.RI "void \fBGetAssignmentExpenses\fP ()"
.br
.ti -1c
.RI "void \fBDeleteAssignment\fP ()"
.br
.ti -1c
.RI "void \fBDeleteAssignmentItem\fP ()"
.br
.ti -1c
.RI "void \fBDeleteLabor\fP ()"
.br
.ti -1c
.RI "void \fBDeleteExpense\fP ()"
.br
.ti -1c
.RI "void \fBSaveTimerEntry\fP ()"
.br
.ti -1c
.RI "void \fBUpdateTimerEntry\fP ()"
.br
.ti -1c
.RI "void \fBGetTimerEntry\fP ()"
.br
.ti -1c
.RI "void \fBDeleteTimerEntry\fP ()"
.br
.ti -1c
.RI "void \fBGetPhotos\fP ()"
.br
.ti -1c
.RI "void \fBSavePhoto\fP ()"
.br
.ti -1c
.RI "void \fBDeletePhoto\fP ()"
.br
.ti -1c
.RI "void \fBGetHistory\fP ()"
.br
.ti -1c
.RI "void \fBGetSignature\fP ()"
.br
.ti -1c
.RI "void \fBGetExpensePhoto\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.DeleteAssignment ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.DeleteAssignmentItem ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.DeleteExpense ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.DeleteLabor ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.DeletePhoto ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.DeleteTimerEntry ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.GetAssignmentAndCheckTotalExpenses ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.GetAssignmentAndCheckTotalHours ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.GetAssignmentAndCheckTotalItems ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.GetAssignmentExpenses ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.GetAssignmentItems ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.GetAssignmentLabor ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.GetAssignments ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.GetExpensePhoto ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.GetHistory ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.GetItems ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.GetPhotos ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.GetSignature ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.GetTimerEntry ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.SaveAssignment ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.SaveAssignmentItemInsert ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.SaveAssignmentItemUpdate ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.SaveExpenseInsert ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.SaveExpenseUpdate ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.SaveLaborInsert ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.SaveLaborUpdate ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.SavePhoto ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.SaveTimerEntry ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.SetUp ()"

.SS "void FieldService\&.Tests\&.Data\&.SampleAssignmentServiceTests\&.UpdateTimerEntry ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
