.TH "FieldService.Utilities" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Utilities \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataExtensions\fP"
.br
.ti -1c
.RI "class \fBServiceContainer\fP"
.br
.ti -1c
.RI "class \fBTaskExtensions\fP"
.br
.RI "\fIClass containing helper extension methods \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
