.TH "FieldService.Android.AssignmentTabActivity.MapDataWrapper" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.AssignmentTabActivity.MapDataWrapper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Object, and ISerializable\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBZoom\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "View \fBOverlayBubble\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "GeoPoint \fBOverlayPoint\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "View FieldService\&.Android\&.AssignmentTabActivity\&.MapDataWrapper\&.OverlayBubble\fC [get]\fP, \fC [set]\fP"

.SS "GeoPoint FieldService\&.Android\&.AssignmentTabActivity\&.MapDataWrapper\&.OverlayPoint\fC [get]\fP, \fC [set]\fP"

.SS "int FieldService\&.Android\&.AssignmentTabActivity\&.MapDataWrapper\&.Zoom\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
