.TH "FieldService.Android.Resource.Color" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Resource.Color \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBassignmentblue\fP = 2131034118"
.br
.ti -1c
.RI "const int \fBassignmentgrey\fP = 2131034119"
.br
.ti -1c
.RI "const int \fBassignmentoffwhite\fP = 2131034117"
.br
.ti -1c
.RI "const int \fBblueassignmentbutton\fP = 2131034113"
.br
.ti -1c
.RI "const int \fBblueclick\fP = 2131034112"
.br
.ti -1c
.RI "const int \fBconfirmationborder\fP = 2131034122"
.br
.ti -1c
.RI "const int \fBdisabledText\fP = 2131034125"
.br
.ti -1c
.RI "const int \fBgreybutton\fP = 2131034114"
.br
.ti -1c
.RI "const int \fBgreyheadertext\fP = 2131034116"
.br
.ti -1c
.RI "const int \fBgreyspinnertext\fP = 2131034115"
.br
.ti -1c
.RI "const int \fBhistorycolor\fP = 2131034124"
.br
.ti -1c
.RI "const int \fBitemssearchcolor\fP = 2131034121"
.br
.ti -1c
.RI "const int \fBlistviewdivider\fP = 2131034123"
.br
.ti -1c
.RI "const int \fBnavigationitemselected\fP = 2131034120"
.br
.ti -1c
.RI "const int \fBradio_selector_color\fP = 2131034126"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const int FieldService\&.Android\&.Resource\&.Color\&.assignmentblue = 2131034118"

.SS "const int FieldService\&.Android\&.Resource\&.Color\&.assignmentgrey = 2131034119"

.SS "const int FieldService\&.Android\&.Resource\&.Color\&.assignmentoffwhite = 2131034117"

.SS "const int FieldService\&.Android\&.Resource\&.Color\&.blueassignmentbutton = 2131034113"

.SS "const int FieldService\&.Android\&.Resource\&.Color\&.blueclick = 2131034112"

.SS "const int FieldService\&.Android\&.Resource\&.Color\&.confirmationborder = 2131034122"

.SS "const int FieldService\&.Android\&.Resource\&.Color\&.disabledText = 2131034125"

.SS "const int FieldService\&.Android\&.Resource\&.Color\&.greybutton = 2131034114"

.SS "const int FieldService\&.Android\&.Resource\&.Color\&.greyheadertext = 2131034116"

.SS "const int FieldService\&.Android\&.Resource\&.Color\&.greyspinnertext = 2131034115"

.SS "const int FieldService\&.Android\&.Resource\&.Color\&.historycolor = 2131034124"

.SS "const int FieldService\&.Android\&.Resource\&.Color\&.itemssearchcolor = 2131034121"

.SS "const int FieldService\&.Android\&.Resource\&.Color\&.listviewdivider = 2131034123"

.SS "const int FieldService\&.Android\&.Resource\&.Color\&.navigationitemselected = 2131034120"

.SS "const int FieldService\&.Android\&.Resource\&.Color\&.radio_selector_color = 2131034126"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
