.TH "FieldService.Tests.ViewModels.ItemViewModelTests" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Tests.ViewModels.ItemViewModelTests \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP ()"
.br
.ti -1c
.RI "void \fBLoadAssignmentItems\fP ()"
.br
.ti -1c
.RI "void \fBLoadItems\fP ()"
.br
.ti -1c
.RI "void \fBSaveAssignmentItem\fP ()"
.br
.ti -1c
.RI "void \fBDeleteAssignmentItem\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void FieldService\&.Tests\&.ViewModels\&.ItemViewModelTests\&.DeleteAssignmentItem ()"

.SS "void FieldService\&.Tests\&.ViewModels\&.ItemViewModelTests\&.LoadAssignmentItems ()"

.SS "void FieldService\&.Tests\&.ViewModels\&.ItemViewModelTests\&.LoadItems ()"

.SS "void FieldService\&.Tests\&.ViewModels\&.ItemViewModelTests\&.SaveAssignmentItem ()"

.SS "void FieldService\&.Tests\&.ViewModels\&.ItemViewModelTests\&.SetUp ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
