.TH "FieldService.ViewModels.HistoryViewModel" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.ViewModels.HistoryViewModel \- 
.PP
ViewModel for assignment history  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.ViewModels\&.ViewModelBase\fP\&.
.PP
Inherited by \fBFieldService\&.WinRT\&.ViewModels\&.HistoryViewModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHistoryViewModel\fP ()"
.br
.ti -1c
.RI "Task \fBLoadHistoryAsync\fP (\fBAssignment\fP assignment)"
.br
.RI "\fILoads the assignment history \fP"
.ti -1c
.RI "Task \fBLoadAssignmentFromHistory\fP (\fBAssignmentHistory\fP assignmentHistory)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBAssignmentHistory\fP > \fBHistory\fP\fC [get, set]\fP"
.br
.RI "\fIList of assignment history \fP"
.ti -1c
.RI "\fBAssignment\fP \fBPastAssignment\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAssignmentHistory\fP \fBSelectedAssignmentHistory\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
ViewModel for assignment history 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.ViewModels\&.HistoryViewModel\&.HistoryViewModel ()"

.SH "Member Function Documentation"
.PP 
.SS "Task FieldService\&.ViewModels\&.HistoryViewModel\&.LoadAssignmentFromHistory (\fBAssignmentHistory\fPassignmentHistory)"

.SS "Task FieldService\&.ViewModels\&.HistoryViewModel\&.LoadHistoryAsync (\fBAssignment\fPassignment)"

.PP
Loads the assignment history 
.SH "Property Documentation"
.PP 
.SS "List<\fBAssignmentHistory\fP> FieldService\&.ViewModels\&.HistoryViewModel\&.History\fC [get]\fP, \fC [set]\fP"

.PP
List of assignment history 
.SS "\fBAssignment\fP FieldService\&.ViewModels\&.HistoryViewModel\&.PastAssignment\fC [get]\fP, \fC [set]\fP"

.SS "\fBAssignmentHistory\fP FieldService\&.ViewModels\&.HistoryViewModel\&.SelectedAssignmentHistory\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
