.TH "fieldservice.android.R" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fieldservice.android.R \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBattr\fP"
.br
.ti -1c
.RI "class \fBcolor\fP"
.br
.ti -1c
.RI "class \fBdrawable\fP"
.br
.ti -1c
.RI "class \fBid\fP"
.br
.ti -1c
.RI "class \fBlayout\fP"
.br
.ti -1c
.RI "class \fBmenu\fP"
.br
.ti -1c
.RI "class \fBstring\fP"
.br
.ti -1c
.RI "class \fBstyle\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
