.TH "FieldService.WinRT.Views.ExpensesPage" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.WinRT.Views.ExpensesPage \- 
.PP
Page for displaying expenses  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Page\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExpensesPage\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnNavigatedTo\fP (NavigationEventArgs e)"
.br
.RI "\fIInvoked when this page is about to be displayed in a Frame\&. \fP"
.ti -1c
.RI "override void \fBOnNavigatedFrom\fP (NavigationEventArgs e)"
.br
.RI "\fIInvoked when this page is unloaded\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Page for displaying expenses 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.WinRT\&.Views\&.ExpensesPage\&.ExpensesPage ()"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.WinRT\&.Views\&.ExpensesPage\&.OnNavigatedFrom (NavigationEventArgse)\fC [protected]\fP"

.PP
Invoked when this page is unloaded\&. 
.PP
\fBParameters:\fP
.RS 4
\fIe\fP 
.RE
.PP

.SS "override void FieldService\&.WinRT\&.Views\&.ExpensesPage\&.OnNavigatedTo (NavigationEventArgse)\fC [protected]\fP"

.PP
Invoked when this page is about to be displayed in a Frame\&. 
.PP
\fBParameters:\fP
.RS 4
\fIe\fP Event data that describes how this page was reached\&. The Parameter property is typically used to configure the page\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
