.TH "FieldService.Catalog" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Catalog \- 
.PP
Static class containing strings used throughout the app  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBGetString\fP (string key, string comment=null)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Static class containing strings used throughout the app 


.IP "\(bu" 2
a developer could replace this with *\&.resx supporting globalization if desired 
.PP

.SH "Member Function Documentation"
.PP 
.SS "static string FieldService\&.Catalog\&.GetString (stringkey, stringcomment = \fCnull\fP)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
