.TH "FieldService.WinRT.Utilities.StatusToColorConverter" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.WinRT.Utilities.StatusToColorConverter \- 
.PP
Converter for converting an AssignmentStatus to a Brush  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IValueConverter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBConvert\fP (object value, Type targetType, object parameter, string language)"
.br
.ti -1c
.RI "object \fBConvertBack\fP (object value, Type targetType, object parameter, string language)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Converter for converting an AssignmentStatus to a Brush 


.SH "Member Function Documentation"
.PP 
.SS "object FieldService\&.WinRT\&.Utilities\&.StatusToColorConverter\&.Convert (objectvalue, TypetargetType, objectparameter, stringlanguage)"

.SS "object FieldService\&.WinRT\&.Utilities\&.StatusToColorConverter\&.ConvertBack (objectvalue, TypetargetType, objectparameter, stringlanguage)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
