.TH "FieldService.ILoginService" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.ILoginService \- 
.PP
Interface providing backend data to \fBViewModels\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBFieldService\&.Data\&.SampleLoginService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Task< bool > \fBLoginAsync\fP (string username, string password, \fBCancellationToken\fP cancellationToken=default(\fBCancellationToken\fP))"
.br
.RI "\fIAsynchronous login \fP"
.in -1c
.SH "Detailed Description"
.PP 
Interface providing backend data to \fBViewModels\fP 


.SH "Member Function Documentation"
.PP 
.SS "Task<bool> FieldService\&.ILoginService\&.LoginAsync (stringusername, stringpassword, \fBCancellationToken\fPcancellationToken = \fCdefault(\fBCancellationToken\fP)\fP)"

.PP
Asynchronous login 
.PP
Implemented in \fBFieldService\&.Data\&.SampleLoginService\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
