.TH "FieldService.Android.LoginActivity" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.LoginActivity \- 
.PP
Activity for the login screen  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Activity, and IOnEditorActionListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoginActivity\fP ()"
.br
.RI "\fIClass constructor \fP"
.ti -1c
.RI "override void \fBOnBackPressed\fP ()"
.br
.RI "\fIOverride on back pressed so when the user is on the inactive login screen we don't let them back out of it\&. \fP"
.ti -1c
.RI "bool \fBOnEditorAction\fP (TextView v, ImeAction actionId, KeyEvent e)"
.br
.RI "\fIObserves the TextView's ImeAction so an action can be taken on keypress\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCreate\fP (Bundle bundle)"
.br
.ti -1c
.RI "override void \fBOnResume\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Activity for the login screen 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.LoginActivity\&.LoginActivity ()"

.PP
Class constructor 
.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.Android\&.LoginActivity\&.OnBackPressed ()"

.PP
Override on back pressed so when the user is on the inactive login screen we don't let them back out of it\&. 
.SS "override void FieldService\&.Android\&.LoginActivity\&.OnCreate (Bundlebundle)\fC [protected]\fP"

.SS "bool FieldService\&.Android\&.LoginActivity\&.OnEditorAction (TextViewv, ImeActionactionId, KeyEvente)"

.PP
Observes the TextView's ImeAction so an action can be taken on keypress\&. 
.SS "override void FieldService\&.Android\&.LoginActivity\&.OnResume ()\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
