.TH "FieldService.iOS.PhotoCell" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.PhotoCell \- 
.PP
Table cell for a photo on an assignment  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UITableViewCell\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPhotoCell\fP (IntPtr handle)"
.br
.ti -1c
.RI "override void \fBAwakeFromNib\fP ()"
.br
.ti -1c
.RI "void \fBSetPhoto\fP (\fBPhoto\fP photo)"
.br
.RI "\fISet the photo for this cell \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Table cell for a photo on an assignment 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.PhotoCell\&.PhotoCell (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.iOS\&.PhotoCell\&.AwakeFromNib ()"

.SS "override void FieldService\&.iOS\&.PhotoCell\&.Dispose (booldisposing)\fC [protected]\fP"

.SS "void FieldService\&.iOS\&.PhotoCell\&.SetPhoto (\fBPhoto\fPphoto)"

.PP
Set the photo for this cell 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
