.TH "FieldService.iOS.ClrWrapper" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.ClrWrapper \- 
.PP
An NSObject for holding CLR objects, for passing C# objects through NSDictionary, etc\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits NSObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClrWrapper\fP (object value)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "object \fBValue\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An NSObject for holding CLR objects, for passing C# objects through NSDictionary, etc\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.ClrWrapper\&.ClrWrapper (objectvalue)"

.SH "Property Documentation"
.PP 
.SS "object FieldService\&.iOS\&.ClrWrapper\&.Value\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
