.TH "FieldService.Android.Fragments" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Fragments \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfirmationFragment\fP"
.br
.RI "\fIFragment for the confirmation section \fP"
.ti -1c
.RI "class \fBDocumentFragment\fP"
.br
.ti -1c
.RI "class \fBExpenseFragment\fP"
.br
.ti -1c
.RI "class \fBHistoryFragment\fP"
.br
.ti -1c
.RI "class \fBItemFragment\fP"
.br
.RI "\fIFragment for the items section \fP"
.ti -1c
.RI "class \fBLaborHourFragment\fP"
.br
.RI "\fIFragment for the labor hours section \fP"
.ti -1c
.RI "class \fBMapFragment\fP"
.br
.RI "\fIFragment for the maps section \fP"
.ti -1c
.RI "class \fBNavigationFragment\fP"
.br
.RI "\fIFragment for the navigation menu as well as the active assignment's timer \fP"
.ti -1c
.RI "class \fBSummaryFragment\fP"
.br
.RI "\fIFragment for the summary screen \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
