.TH "FieldService.iOS.MapController" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.MapController \- 
.PP
Controller for displaying the map for an assignment  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.iOS\&.BaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMapController\fP ()"
.br
.ti -1c
.RI "override void \fBViewDidLoad\fP ()"
.br
.ti -1c
.RI "override void \fBViewWillAppear\fP (bool animated)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Controller for displaying the map for an assignment 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.MapController\&.MapController ()"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.iOS\&.MapController\&.ViewDidLoad ()"

.SS "override void FieldService\&.iOS\&.MapController\&.ViewWillAppear (boolanimated)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
