.TH "FieldService.iOS.ExpenseCell" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.ExpenseCell \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits UITableViewCell\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExpenseCell\fP (IntPtr handle)"
.br
.ti -1c
.RI "void \fBSetExpense\fP (\fBExpense\fP expense)"
.br
.RI "\fISets the labor hours on this cell \fP"
.ti -1c
.RI "override void \fBWillTransitionToState\fP (UITableViewCellState mask)"
.br
.ti -1c
.RI "override void \fBDidTransitionToState\fP (UITableViewCellState mask)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.ExpenseCell\&.ExpenseCell (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.iOS\&.ExpenseCell\&.DidTransitionToState (UITableViewCellStatemask)"

.SS "override void FieldService\&.iOS\&.ExpenseCell\&.Dispose (booldisposing)\fC [protected]\fP"

.SS "void FieldService\&.iOS\&.ExpenseCell\&.SetExpense (\fBExpense\fPexpense)"

.PP
Sets the labor hours on this cell 
.SS "override void FieldService\&.iOS\&.ExpenseCell\&.WillTransitionToState (UITableViewCellStatemask)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
