.TH "FieldService.WinRT.ViewModels" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.WinRT.ViewModels \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAssignmentViewModel\fP"
.br
.ti -1c
.RI "class \fBDocumentViewModel\fP"
.br
.ti -1c
.RI "class \fBExpenseViewModel\fP"
.br
.ti -1c
.RI "class \fBHistoryViewModel\fP"
.br
.ti -1c
.RI "class \fBItemViewModel\fP"
.br
.RI "\fI\fBWinRT\fP version of the \fBItemViewModel\fP \fP"
.ti -1c
.RI "class \fBLaborViewModel\fP"
.br
.RI "\fI\fBWinRT\fP version of the \fBLaborViewModel\fP \fP"
.ti -1c
.RI "class \fBLoginViewModel\fP"
.br
.RI "\fI\fBWinRT\fP version of the \fBLoginViewModel\fP \fP"
.ti -1c
.RI "class \fBPhotoViewModel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
