.TH "FieldService.Data.TimerEntry" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Data.TimerEntry \- 
.PP
Class for holding a TimeStamp to persist the timer while the app is closed  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBDate\fP\fC [get, set]\fP"
.br
.RI "\fIThe time the entry was started \fP"
.in -1c
.SH "Detailed Description"
.PP 
Class for holding a TimeStamp to persist the timer while the app is closed 


.SH "Property Documentation"
.PP 
.SS "DateTime FieldService\&.Data\&.TimerEntry\&.Date\fC [get]\fP, \fC [set]\fP"

.PP
The time the entry was started 
.SS "int FieldService\&.Data\&.TimerEntry\&.Id\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
