.TH "FieldService.WinRT.Views.ConfirmationsPage" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.WinRT.Views.ConfirmationsPage \- 
.PP
Confirmations page for  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Page\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfirmationsPage\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnNavigatedTo\fP (NavigationEventArgs e)"
.br
.RI "\fIInvoked when this page is about to be displayed in a Frame\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Confirmations page for 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.WinRT\&.Views\&.ConfirmationsPage\&.ConfirmationsPage ()"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.WinRT\&.Views\&.ConfirmationsPage\&.OnNavigatedTo (NavigationEventArgse)\fC [protected]\fP"

.PP
Invoked when this page is about to be displayed in a Frame\&. 
.PP
\fBParameters:\fP
.RS 4
\fIe\fP Event data that describes how this page was reached\&. The Parameter property is typically used to configure the page\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
