.TH "FieldService.iOS.LaborController" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.LaborController \- 
.PP
Controller for the labor section  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.iOS\&.BaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLaborController\fP (IntPtr handle)"
.br
.ti -1c
.RI "override void \fBViewDidLoad\fP ()"
.br
.ti -1c
.RI "override void \fBViewWillAppear\fP (bool animated)"
.br
.ti -1c
.RI "override void \fBViewWillDisappear\fP (bool animated)"
.br
.ti -1c
.RI "void \fBReloadLabor\fP ()"
.br
.RI "\fIReload the labor hours \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Controller for the labor section 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.LaborController\&.LaborController (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "void FieldService\&.iOS\&.LaborController\&.ReloadLabor ()"

.PP
Reload the labor hours 
.SS "override void FieldService\&.iOS\&.LaborController\&.ViewDidLoad ()"

.SS "override void FieldService\&.iOS\&.LaborController\&.ViewWillAppear (boolanimated)"

.SS "override void FieldService\&.iOS\&.LaborController\&.ViewWillDisappear (boolanimated)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
