.TH "FieldService.WinRT.Utilities.BooleanToVisibilityConverter" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.WinRT.Utilities.BooleanToVisibilityConverter \- 
.PP
Converts a Boolean into a Visibility\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IValueConverter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBConvert\fP (object value, Type targetType, object parameter, string language)"
.br
.ti -1c
.RI "object \fBConvertBack\fP (object value, Type targetType, object parameter, string language)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsReversed\fP\fC [get, set]\fP"
.br
.RI "\fIIf set to True, conversion is reversed: True will become Collapsed\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Converts a Boolean into a Visibility\&. 


.SH "Member Function Documentation"
.PP 
.SS "object FieldService\&.WinRT\&.Utilities\&.BooleanToVisibilityConverter\&.Convert (objectvalue, TypetargetType, objectparameter, stringlanguage)"

.SS "object FieldService\&.WinRT\&.Utilities\&.BooleanToVisibilityConverter\&.ConvertBack (objectvalue, TypetargetType, objectparameter, stringlanguage)"

.SH "Property Documentation"
.PP 
.SS "bool FieldService\&.WinRT\&.Utilities\&.BooleanToVisibilityConverter\&.IsReversed\fC [get]\fP, \fC [set]\fP"

.PP
If set to True, conversion is reversed: True will become Collapsed\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
