.TH "FieldService.Android.Dialogs.ItemsDialog" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Dialogs.ItemsDialog \- 
.PP
Dialog for searching through items  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.Android\&.Dialogs\&.BaseDialog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBItemsDialog\fP (\fBSummaryActivity\fP activity)"
.br
.ti -1c
.RI "void \fBOnClick\fP (View v)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCreate\fP (Bundle savedInstanceState)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBAssignment\fP \fBAssignment\fP\fC [get, set]\fP"
.br
.RI "\fIThe selected assignment \fP"
.in -1c
.SH "Detailed Description"
.PP 
Dialog for searching through items 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.Dialogs\&.ItemsDialog\&.ItemsDialog (\fBSummaryActivity\fPactivity)"

.SH "Member Function Documentation"
.PP 
.SS "void FieldService\&.Android\&.Dialogs\&.ItemsDialog\&.OnClick (Viewv)"

.SS "override void FieldService\&.Android\&.Dialogs\&.ItemsDialog\&.OnCreate (BundlesavedInstanceState)\fC [protected]\fP"

.SH "Property Documentation"
.PP 
.SS "\fBAssignment\fP FieldService\&.Android\&.Dialogs\&.ItemsDialog\&.Assignment\fC [get]\fP, \fC [set]\fP"

.PP
The selected assignment 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
