.TH "FieldService.iOS.ExpenseCategorySheet" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.ExpenseCategorySheet \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIActionSheet\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExpenseCategorySheet\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBExpenseCategory\fP \fBCategory\fP\fC [get, set]\fP"
.br
.RI "\fIThe category the user selected, or null if none \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.ExpenseCategorySheet\&.ExpenseCategorySheet ()"

.SH "Property Documentation"
.PP 
.SS "\fBExpenseCategory\fP FieldService\&.iOS\&.ExpenseCategorySheet\&.Category\fC [get]\fP, \fC [set]\fP"

.PP
The category the user selected, or null if none 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
