.TH "FieldService.Android.Fragments.MapFragment" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Fragments.MapFragment \- 
.PP
Fragment for the maps section  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Fragment\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "override View \fBOnCreateView\fP (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)"
.br
.ti -1c
.RI "override void \fBOnResume\fP ()"
.br
.RI "\fIResume the LocalActivityManager \fP"
.ti -1c
.RI "override void \fBOnPause\fP ()"
.br
.RI "\fIPause the LocalActivityManager \fP"
.ti -1c
.RI "override void \fBOnStop\fP ()"
.br
.RI "\fIStop the LocalActivityManager \fP"
.in -1c
.SH "Detailed Description"
.PP 
Fragment for the maps section 


.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.Android\&.Fragments\&.MapFragment\&.OnCreate (BundlesavedInstanceState)"

.SS "override View FieldService\&.Android\&.Fragments\&.MapFragment\&.OnCreateView (LayoutInflaterinflater, ViewGroupcontainer, BundlesavedInstanceState)"

.SS "override void FieldService\&.Android\&.Fragments\&.MapFragment\&.OnPause ()"

.PP
Pause the LocalActivityManager 
.SS "override void FieldService\&.Android\&.Fragments\&.MapFragment\&.OnResume ()"

.PP
Resume the LocalActivityManager 
.SS "override void FieldService\&.Android\&.Fragments\&.MapFragment\&.OnStop ()"

.PP
Stop the LocalActivityManager 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
