.TH "FieldService.Android.Resource.Layout" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Resource.Layout \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBAddExpensePopUpLayout\fP = 2130903040"
.br
.ti -1c
.RI "const int \fBAddLaborPopUpLayout\fP = 2130903041"
.br
.ti -1c
.RI "const int \fBAddPhotoPopUpLayout\fP = 2130903042"
.br
.ti -1c
.RI "const int \fBAddSignatureLayout\fP = 2130903043"
.br
.ti -1c
.RI "const int \fBAssignmentHistoryLayout\fP = 2130903044"
.br
.ti -1c
.RI "const int \fBAssignmentItemLayout\fP = 2130903045"
.br
.ti -1c
.RI "const int \fBAssignmentsLayout\fP = 2130903046"
.br
.ti -1c
.RI "const int \fBAssignmentsTabsLayout\fP = 2130903047"
.br
.ti -1c
.RI "const int \fBConfirmationsLayout\fP = 2130903048"
.br
.ti -1c
.RI "const int \fBDocumentFragmentLayout\fP = 2130903049"
.br
.ti -1c
.RI "const int \fBDocumentListItemLayout\fP = 2130903050"
.br
.ti -1c
.RI "const int \fBExpenseListItemLayout\fP = 2130903051"
.br
.ti -1c
.RI "const int \fBExpensesFragmentLayout\fP = 2130903052"
.br
.ti -1c
.RI "const int \fBHistoryFragmentLayout\fP = 2130903053"
.br
.ti -1c
.RI "const int \fBHistoryItemLayout\fP = 2130903054"
.br
.ti -1c
.RI "const int \fBHistoryTabs\fP = 2130903055"
.br
.ti -1c
.RI "const int \fBItemLayout\fP = 2130903056"
.br
.ti -1c
.RI "const int \fBItemSearchListItemLayout\fP = 2130903057"
.br
.ti -1c
.RI "const int \fBItemsFragmentLayout\fP = 2130903058"
.br
.ti -1c
.RI "const int \fBItemsPopUpLayout\fP = 2130903059"
.br
.ti -1c
.RI "const int \fBLaborHoursLayout\fP = 2130903060"
.br
.ti -1c
.RI "const int \fBLaborHoursListItemLayout\fP = 2130903061"
.br
.ti -1c
.RI "const int \fBLoginLayout\fP = 2130903062"
.br
.ti -1c
.RI "const int \fBMapFragmentLayout\fP = 2130903063"
.br
.ti -1c
.RI "const int \fBMapOverlayLayout\fP = 2130903064"
.br
.ti -1c
.RI "const int \fBMapViewLayout\fP = 2130903065"
.br
.ti -1c
.RI "const int \fBNavigationLayout\fP = 2130903066"
.br
.ti -1c
.RI "const int \fBNavigationListItemLayout\fP = 2130903067"
.br
.ti -1c
.RI "const int \fBPhotoItemLayout\fP = 2130903068"
.br
.ti -1c
.RI "const int \fBSimpleSpinnerItem\fP = 2130903069"
.br
.ti -1c
.RI "const int \fBSummaryFragmentLayout\fP = 2130903070"
.br
.ti -1c
.RI "const int \fBSummaryLayout\fP = 2130903071"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.AddExpensePopUpLayout = 2130903040"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.AddLaborPopUpLayout = 2130903041"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.AddPhotoPopUpLayout = 2130903042"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.AddSignatureLayout = 2130903043"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.AssignmentHistoryLayout = 2130903044"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.AssignmentItemLayout = 2130903045"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.AssignmentsLayout = 2130903046"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.AssignmentsTabsLayout = 2130903047"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.ConfirmationsLayout = 2130903048"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.DocumentFragmentLayout = 2130903049"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.DocumentListItemLayout = 2130903050"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.ExpenseListItemLayout = 2130903051"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.ExpensesFragmentLayout = 2130903052"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.HistoryFragmentLayout = 2130903053"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.HistoryItemLayout = 2130903054"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.HistoryTabs = 2130903055"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.ItemLayout = 2130903056"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.ItemSearchListItemLayout = 2130903057"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.ItemsFragmentLayout = 2130903058"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.ItemsPopUpLayout = 2130903059"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.LaborHoursLayout = 2130903060"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.LaborHoursListItemLayout = 2130903061"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.LoginLayout = 2130903062"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.MapFragmentLayout = 2130903063"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.MapOverlayLayout = 2130903064"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.MapViewLayout = 2130903065"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.NavigationLayout = 2130903066"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.NavigationListItemLayout = 2130903067"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.PhotoItemLayout = 2130903068"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.SimpleSpinnerItem = 2130903069"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.SummaryFragmentLayout = 2130903070"

.SS "const int FieldService\&.Android\&.Resource\&.Layout\&.SummaryLayout = 2130903071"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
