.TH "FieldService.iOS.LaborTypeTextField" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.LaborTypeTextField \- 
.PP
Custom text field for choosing a labor type -> uses UIPickerView underneath  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UITextField\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLaborTypeTextField\fP (IntPtr handle)"
.br
.ti -1c
.RI "\fBLaborTypeTextField\fP (RectangleF frame)"
.br
.ti -1c
.RI "\fBLaborTypeTextField\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBLaborType\fP \fBLaborType\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the current labor type \fP"
.in -1c
.SH "Detailed Description"
.PP 
Custom text field for choosing a labor type -> uses UIPickerView underneath 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.LaborTypeTextField\&.LaborTypeTextField (IntPtrhandle)"

.SS "FieldService\&.iOS\&.LaborTypeTextField\&.LaborTypeTextField (RectangleFframe)"

.SS "FieldService\&.iOS\&.LaborTypeTextField\&.LaborTypeTextField ()"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.iOS\&.LaborTypeTextField\&.Dispose (booldisposing)\fC [protected]\fP"
summary> Sets up the 'delegate' for the UIPickerView - not sure why Apple chose 'ViewModel' as their wording here 
.SH "Property Documentation"
.PP 
.SS "\fBLaborType\fP FieldService\&.iOS\&.LaborTypeTextField\&.LaborType\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the current labor type 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
