.TH "FieldService.iOS.HistoryController" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.HistoryController \- 
.PP
Controller for the history section  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.iOS\&.BaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHistoryController\fP (IntPtr handle)"
.br
.ti -1c
.RI "override void \fBViewDidLoad\fP ()"
.br
.ti -1c
.RI "override void \fBViewWillAppear\fP (bool animated)"
.br
.ti -1c
.RI "void \fBReloadHIstory\fP ()"
.br
.RI "\fIReload history \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Controller for the history section 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.HistoryController\&.HistoryController (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "void FieldService\&.iOS\&.HistoryController\&.ReloadHIstory ()"

.PP
Reload history 
.SS "override void FieldService\&.iOS\&.HistoryController\&.ViewDidLoad ()"

.SS "override void FieldService\&.iOS\&.HistoryController\&.ViewWillAppear (boolanimated)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
