.TH "FieldService.Android.Dialogs.PhotoDialog" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.Dialogs.PhotoDialog \- 
.PP
Dialog for the photos  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.Android\&.Dialogs\&.BaseDialog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPhotoDialog\fP (\fBActivity\fP activity)"
.br
.ti -1c
.RI "override void \fBOnAttachedToWindow\fP ()"
.br
.RI "\fILoad the photo and description \fP"
.ti -1c
.RI "override void \fBOnDetachedFromWindow\fP ()"
.br
.RI "\fICleanup data when dialog is dismissed from window \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCreate\fP (Bundle savedInstanceState)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Activity \fBActivity\fP\fC [get, set]\fP"
.br
.RI "\fIThe parent activity \fP"
.ti -1c
.RI "\fBAssignment\fP \fBAssignment\fP\fC [get, set]\fP"
.br
.RI "\fIThe selected assignment \fP"
.ti -1c
.RI "\fBPhoto\fP \fBPhoto\fP\fC [get, set]\fP"
.br
.RI "\fIThe photo \fP"
.ti -1c
.RI "Stream \fBPhotoStream\fP\fC [get, set]\fP"
.br
.RI "\fIStream passed in from MediaPicker \fP"
.in -1c
.SH "Detailed Description"
.PP 
Dialog for the photos 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.Dialogs\&.PhotoDialog\&.PhotoDialog (\fBActivity\fPactivity)"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.Android\&.Dialogs\&.PhotoDialog\&.OnAttachedToWindow ()"

.PP
Load the photo and description 
.SS "override void FieldService\&.Android\&.Dialogs\&.PhotoDialog\&.OnCreate (BundlesavedInstanceState)\fC [protected]\fP"

.SS "override void FieldService\&.Android\&.Dialogs\&.PhotoDialog\&.OnDetachedFromWindow ()"

.PP
Cleanup data when dialog is dismissed from window 
.SH "Property Documentation"
.PP 
.SS "Activity FieldService\&.Android\&.Dialogs\&.PhotoDialog\&.Activity\fC [get]\fP, \fC [set]\fP"

.PP
The parent activity 
.SS "\fBAssignment\fP FieldService\&.Android\&.Dialogs\&.PhotoDialog\&.Assignment\fC [get]\fP, \fC [set]\fP"

.PP
The selected assignment 
.SS "\fBPhoto\fP FieldService\&.Android\&.Dialogs\&.PhotoDialog\&.Photo\fC [get]\fP, \fC [set]\fP"

.PP
The photo 
.SS "Stream FieldService\&.Android\&.Dialogs\&.PhotoDialog\&.PhotoStream\fC [get]\fP, \fC [set]\fP"

.PP
Stream passed in from MediaPicker 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
