.TH "FieldService.iOS.LaborCell" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.LaborCell \- 
.PP
Table cell for labor hours  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UITableViewCell\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLaborCell\fP (IntPtr handle)"
.br
.ti -1c
.RI "void \fBSetLabor\fP (\fBLabor\fP labor)"
.br
.RI "\fISets the labor hours on this cell \fP"
.ti -1c
.RI "override void \fBWillTransitionToState\fP (UITableViewCellState mask)"
.br
.ti -1c
.RI "override void \fBDidTransitionToState\fP (UITableViewCellState mask)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Table cell for labor hours 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.LaborCell\&.LaborCell (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.iOS\&.LaborCell\&.DidTransitionToState (UITableViewCellStatemask)"

.SS "override void FieldService\&.iOS\&.LaborCell\&.Dispose (booldisposing)\fC [protected]\fP"

.SS "void FieldService\&.iOS\&.LaborCell\&.SetLabor (\fBLabor\fPlabor)"

.PP
Sets the labor hours on this cell 
.SS "override void FieldService\&.iOS\&.LaborCell\&.WillTransitionToState (UITableViewCellStatemask)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
