.TH "FieldService.iOS.AddPhotoController" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.AddPhotoController \- 
.PP
Controller for adding a photo  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.iOS\&.BaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddPhotoController\fP (IntPtr handle)"
.br
.ti -1c
.RI "override void \fBViewDidLoad\fP ()"
.br
.ti -1c
.RI "override void \fBViewWillAppear\fP (bool animated)"
.br
.ti -1c
.RI "override void \fBViewWillDisappear\fP (bool animated)"
.br
.ti -1c
.RI "override void \fBViewDidDisappear\fP (bool animated)"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler \fBDismissed\fP"
.br
.RI "\fIOccurs when dismissed\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Controller for adding a photo 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.AddPhotoController\&.AddPhotoController (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.iOS\&.AddPhotoController\&.ViewDidDisappear (boolanimated)"

.SS "override void FieldService\&.iOS\&.AddPhotoController\&.ViewDidLoad ()"

.SS "override void FieldService\&.iOS\&.AddPhotoController\&.ViewWillAppear (boolanimated)"

.SS "override void FieldService\&.iOS\&.AddPhotoController\&.ViewWillDisappear (boolanimated)"

.SH "Event Documentation"
.PP 
.SS "EventHandler FieldService\&.iOS\&.AddPhotoController\&.Dismissed"

.PP
Occurs when dismissed\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
