.TH "FieldService.Android.MapViewActivity" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.MapViewActivity \- 
.PP
Activity for the map overview  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.Android\&.BaseMapActivity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMapViewActivity\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCreate\fP (Bundle bundle)"
.br
.ti -1c
.RI "override void \fBOnResume\fP ()"
.br
.RI "\fIEnabling my location and setting active assignment \fP"
.ti -1c
.RI "override void \fBOnSaveInstanceState\fP (Bundle outState)"
.br
.ti -1c
.RI "override void \fBOnStop\fP ()"
.br
.RI "\fIClearing overlays on map, stopping my location, clearing active assignment in the layout\&. \fP"
.ti -1c
.RI "override void \fBOnPause\fP ()"
.br
.RI "\fIClearing overlay bubble when you leave the screen\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Activity for the map overview 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.MapViewActivity\&.MapViewActivity ()"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.Android\&.MapViewActivity\&.OnCreate (Bundlebundle)\fC [protected]\fP"

.SS "override void FieldService\&.Android\&.MapViewActivity\&.OnPause ()\fC [protected]\fP"

.PP
Clearing overlay bubble when you leave the screen\&. 
.SS "override void FieldService\&.Android\&.MapViewActivity\&.OnResume ()\fC [protected]\fP"

.PP
Enabling my location and setting active assignment 
.SS "override void FieldService\&.Android\&.MapViewActivity\&.OnSaveInstanceState (BundleoutState)\fC [protected]\fP"

.SS "override void FieldService\&.Android\&.MapViewActivity\&.OnStop ()\fC [protected]\fP"

.PP
Clearing overlays on map, stopping my location, clearing active assignment in the layout\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
