.TH "FieldService.WinRT.Views" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.WinRT.Views \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAddExpenseFlyoutPanel\fP"
.br
.ti -1c
.RI "class \fBAddItemFlyoutPanel\fP"
.br
.RI "\fIAdd item flyout panel \fP"
.ti -1c
.RI "class \fBAddLaborFlyoutPanel\fP"
.br
.RI "\fIAdd labor hour flyout panel \fP"
.ti -1c
.RI "class \fBAddSignatureFlyoutPanel\fP"
.br
.RI "\fIFlyout panel for adding signature to the assignment \fP"
.ti -1c
.RI "class \fBAssignmentControl\fP"
.br
.ti -1c
.RI "class \fBAssignmentHistoryPage\fP"
.br
.RI "\fIHistory Page for viewing all history items \fP"
.ti -1c
.RI "class \fBAssignmentMapPage\fP"
.br
.RI "\fIAn empty page that can be used on its own or navigated to within a Frame\&. \fP"
.ti -1c
.RI "class \fBAssignmentPage\fP"
.br
.RI "\fIAn empty page that can be used on its own or navigated to within a Frame\&. \fP"
.ti -1c
.RI "class \fBAssignmentsPage\fP"
.br
.RI "\fIThe page with a list of assignments \fP"
.ti -1c
.RI "class \fBConfirmationsPage\fP"
.br
.RI "\fIConfirmations page for \fP"
.ti -1c
.RI "class \fBDocumentsPage\fP"
.br
.RI "\fIAn empty page that can be used on its own or navigated to within a Frame\&. \fP"
.ti -1c
.RI "class \fBExpensesPage\fP"
.br
.RI "\fIPage for displaying expenses \fP"
.ti -1c
.RI "class \fBImagesPage\fP"
.br
.RI "\fIImages page \fP"
.ti -1c
.RI "class \fBItemsPage\fP"
.br
.RI "\fIThe page for the items \fP"
.ti -1c
.RI "class \fBLaborPage\fP"
.br
.RI "\fIThe page for the labor hours \fP"
.ti -1c
.RI "class \fBLoginPage\fP"
.br
.RI "\fIThe initial login page \fP"
.ti -1c
.RI "class \fBMapPage\fP"
.br
.RI "\fIAn empty page that can be used on its own or navigated to within a Frame\&. \fP"
.ti -1c
.RI "class \fBMapPopup\fP"
.br
.ti -1c
.RI "class \fBMapTile\fP"
.br
.ti -1c
.RI "class \fBSnapPage\fP"
.br
.RI "\fIThe page for when the app is in snap mode \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
