.TH "FieldService.WinRT.Views.SnapPage" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.WinRT.Views.SnapPage \- 
.PP
The page for when the app is in snap mode  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Page\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSnapPage\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnNavigatedTo\fP (NavigationEventArgs e)"
.br
.RI "\fIInvoked when this page is about to be displayed in a Frame\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The page for when the app is in snap mode 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.WinRT\&.Views\&.SnapPage\&.SnapPage ()"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.WinRT\&.Views\&.SnapPage\&.OnNavigatedTo (NavigationEventArgse)\fC [protected]\fP"

.PP
Invoked when this page is about to be displayed in a Frame\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
