.TH "FieldService.iOS.CompleteCell" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.iOS.CompleteCell \- 
.PP
The table cell to complete an assignment  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UITableViewCell\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompleteCell\fP (IntPtr handle)"
.br
.ti -1c
.RI "override void \fBAwakeFromNib\fP ()"
.br
.ti -1c
.RI "void \fBSetAssignment\fP (\fBConfirmationController\fP controller, \fBAssignment\fP assignment, UITableView tableView)"
.br
.RI "\fISets the assignment for this cell \fP"
.in -1c
.SH "Detailed Description"
.PP 
The table cell to complete an assignment 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.iOS\&.CompleteCell\&.CompleteCell (IntPtrhandle)"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.iOS\&.CompleteCell\&.AwakeFromNib ()"

.SS "void FieldService\&.iOS\&.CompleteCell\&.SetAssignment (\fBConfirmationController\fPcontroller, \fBAssignment\fPassignment, UITableViewtableView)"

.PP
Sets the assignment for this cell 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
