.TH "FieldService.Android.LaborTypeSpinnerAdapter" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.LaborTypeSpinnerAdapter \- 
.PP
Adapter for a spinner for selecting LaborType  

.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseAdapter, and ISpinnerAdapter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLaborTypeSpinnerAdapter\fP (\fBLaborType\fP[] items, Context context, int resourceId)"
.br
.ti -1c
.RI "override Java\&.Lang\&.Object \fBGetItem\fP (int position)"
.br
.ti -1c
.RI "override long \fBGetItemId\fP (int position)"
.br
.ti -1c
.RI "override View \fBGetView\fP (int position, View convertView, ViewGroup parent)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override int \fBCount\fP\fC [get]\fP"
.br
.ti -1c
.RI "Color \fBTextColor\fP\fC [get, set]\fP"
.br
.RI "\fIText color for the item \fP"
.ti -1c
.RI "Color \fBBackground\fP\fC [get, set]\fP"
.br
.RI "\fIBackground color of the text view \fP"
.in -1c
.SH "Detailed Description"
.PP 
Adapter for a spinner for selecting LaborType 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.LaborTypeSpinnerAdapter\&.LaborTypeSpinnerAdapter (\fBLaborType\fP[]items, Contextcontext, intresourceId)"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.Android\&.LaborTypeSpinnerAdapter\&.Dispose (booldisposing)\fC [protected]\fP"

.SS "override Java\&.Lang\&.Object FieldService\&.Android\&.LaborTypeSpinnerAdapter\&.GetItem (intposition)"

.SS "override long FieldService\&.Android\&.LaborTypeSpinnerAdapter\&.GetItemId (intposition)"

.SS "override View FieldService\&.Android\&.LaborTypeSpinnerAdapter\&.GetView (intposition, ViewconvertView, ViewGroupparent)"

.SH "Property Documentation"
.PP 
.SS "Color FieldService\&.Android\&.LaborTypeSpinnerAdapter\&.Background\fC [get]\fP, \fC [set]\fP"

.PP
Background color of the text view 
.SS "override int FieldService\&.Android\&.LaborTypeSpinnerAdapter\&.Count\fC [get]\fP"

.SS "Color FieldService\&.Android\&.LaborTypeSpinnerAdapter\&.TextColor\fC [get]\fP, \fC [set]\fP"

.PP
Text color for the item 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
