.TH "FieldService.Android.AssignmentTabActivity" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldService.Android.AssignmentTabActivity \- 
.PP
Activity for the tab bar between 'Assignments' and 'Map Overview'  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFieldService\&.Android\&.BaseActivity\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMapDataWrapper\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssignmentTabActivity\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "override void \fBOnResume\fP ()"
.br
.ti -1c
.RI "override void \fBOnPause\fP ()"
.br
.ti -1c
.RI "override void \fBOnStop\fP ()"
.br
.ti -1c
.RI "override void \fBOnSaveInstanceState\fP (Bundle outState)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "TabHost \fBTabHost\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBMapDataWrapper\fP \fBMapData\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Activity for the tab bar between 'Assignments' and 'Map Overview' 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldService\&.Android\&.AssignmentTabActivity\&.AssignmentTabActivity ()"

.SH "Member Function Documentation"
.PP 
.SS "override void FieldService\&.Android\&.AssignmentTabActivity\&.OnCreate (BundlesavedInstanceState)\fC [protected]\fP"

.SS "override void FieldService\&.Android\&.AssignmentTabActivity\&.OnPause ()\fC [protected]\fP"

.SS "override void FieldService\&.Android\&.AssignmentTabActivity\&.OnResume ()\fC [protected]\fP"

.SS "override void FieldService\&.Android\&.AssignmentTabActivity\&.OnSaveInstanceState (BundleoutState)\fC [protected]\fP"

.SS "override void FieldService\&.Android\&.AssignmentTabActivity\&.OnStop ()\fC [protected]\fP"

.SH "Property Documentation"
.PP 
.SS "\fBMapDataWrapper\fP FieldService\&.Android\&.AssignmentTabActivity\&.MapData\fC [get]\fP, \fC [set]\fP"

.SS "TabHost FieldService\&.Android\&.AssignmentTabActivity\&.TabHost\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
