.TH "GeolocationSample.MainPageViewModel" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeolocationSample.MainPageViewModel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits INotifyPropertyChanged\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainPageViewModel\fP (Geolocator geolocator, SynchronizationContext syncContext)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBShowProgress\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBStatus\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "ICommand \fBGetPosition\fP\fC [get]\fP"
.br
.ti -1c
.RI "ICommand \fBToggleListening\fP\fC [get]\fP"
.br
.ti -1c
.RI "Position \fBCurrentPosition\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "PropertyChangedEventHandler \fBPropertyChanged\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GeolocationSample\&.MainPageViewModel\&.MainPageViewModel (Geolocatorgeolocator, SynchronizationContextsyncContext)"

.SH "Property Documentation"
.PP 
.SS "Position GeolocationSample\&.MainPageViewModel\&.CurrentPosition\fC [get]\fP, \fC [set]\fP"

.SS "ICommand GeolocationSample\&.MainPageViewModel\&.GetPosition\fC [get]\fP"

.SS "bool GeolocationSample\&.MainPageViewModel\&.ShowProgress\fC [get]\fP, \fC [set]\fP"

.SS "string GeolocationSample\&.MainPageViewModel\&.Status\fC [get]\fP, \fC [set]\fP"

.SS "ICommand GeolocationSample\&.MainPageViewModel\&.ToggleListening\fC [get]\fP"

.SH "Event Documentation"
.PP 
.SS "PropertyChangedEventHandler GeolocationSample\&.MainPageViewModel\&.PropertyChanged"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
