.TH "GeolocationSample.DelegatedCommand" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeolocationSample.DelegatedCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ICommand\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDelegatedCommand\fP (Action< object > execute, Func< object, bool > canExecute)"
.br
.ti -1c
.RI "void \fBChangeCanExecute\fP ()"
.br
.ti -1c
.RI "bool \fBCanExecute\fP (object parameter)"
.br
.ti -1c
.RI "void \fBExecute\fP (object parameter)"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler \fBCanExecuteChanged\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GeolocationSample\&.DelegatedCommand\&.DelegatedCommand (Action< object >execute, Func< object, bool >canExecute)"

.SH "Member Function Documentation"
.PP 
.SS "bool GeolocationSample\&.DelegatedCommand\&.CanExecute (objectparameter)"

.SS "void GeolocationSample\&.DelegatedCommand\&.ChangeCanExecute ()"

.SS "void GeolocationSample\&.DelegatedCommand\&.Execute (objectparameter)"

.SH "Event Documentation"
.PP 
.SS "EventHandler GeolocationSample\&.DelegatedCommand\&.CanExecuteChanged"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
