.TH "GeolocationSample.Resource.String" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeolocationSample.Resource.String \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBapp_name\fP = 2130968580"
.br
.ti -1c
.RI "const int \fBcancelPosition\fP = 2130968577"
.br
.ti -1c
.RI "const int \fBgetPosition\fP = 2130968576"
.br
.ti -1c
.RI "const int \fBstartListening\fP = 2130968578"
.br
.ti -1c
.RI "const int \fBstopListening\fP = 2130968579"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const int GeolocationSample\&.Resource\&.String\&.app_name = 2130968580"

.SS "const int GeolocationSample\&.Resource\&.String\&.cancelPosition = 2130968577"

.SS "const int GeolocationSample\&.Resource\&.String\&.getPosition = 2130968576"

.SS "const int GeolocationSample\&.Resource\&.String\&.startListening = 2130968578"

.SS "const int GeolocationSample\&.Resource\&.String\&.stopListening = 2130968579"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
