.TH "GeolocationSample.Resource.Drawable" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeolocationSample.Resource.Drawable \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBIcon\fP = 2130837504"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const int GeolocationSample\&.Resource\&.Drawable\&.Icon = 2130837504"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
