.TH "/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.Android/Fragments/HistoryFragment.cs" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.Android/Fragments/HistoryFragment.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFieldService\&.Android\&.Fragments\&.HistoryFragment\fP"
.br
.ti -1c
.RI "class \fBFieldService\&.Android\&.Fragments\&.HistoryFragment\&.TabContent\fP"
.br
.RI "\fICustom class to create tabs for the history fragment \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBFieldService\&.Android\&.Fragments\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
