.TH "/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService/ILoginService.cs" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService/ILoginService.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBFieldService\&.ILoginService\fP"
.br
.RI "\fIInterface providing backend data to \fBViewModels\fP \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBFieldService\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
