.TH "md___users_bsd-mac__downloads__pruebas_prebuilt-apps-master__field_service__field_service._android__r_e_a_d_m_e" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md___users_bsd-mac__downloads__pruebas_prebuilt-apps-master__field_service__field_service._android__r_e_a_d_m_e \- Field Service - Android 
We are using Google Maps API Key, documentation here: https://developers.google.com/maps/documentation/android/v1/maps-api-signup
.PP
Instructions here: http://docs.xamarin.com/Android/Guides/Platform_Features/Maps_and_Location/Obtaining_a_Google_Maps_API_Key
.PP
You will need a Google Maps API here: http://developer.android.com/sdk/installing/adding-packages.html 
