.TH "MediaPickerSample.Resource.Id" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MediaPickerSample.Resource.Id \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBimage\fP = 2131034116"
.br
.ti -1c
.RI "const int \fBpickPhotoButton\fP = 2131034114"
.br
.ti -1c
.RI "const int \fBpickVideoButton\fP = 2131034115"
.br
.ti -1c
.RI "const int \fBsurfacevideoview\fP = 2131034117"
.br
.ti -1c
.RI "const int \fBtakePhotoButton\fP = 2131034112"
.br
.ti -1c
.RI "const int \fBtakeVideoButton\fP = 2131034113"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const int MediaPickerSample\&.Resource\&.Id\&.image = 2131034116"

.SS "const int MediaPickerSample\&.Resource\&.Id\&.pickPhotoButton = 2131034114"

.SS "const int MediaPickerSample\&.Resource\&.Id\&.pickVideoButton = 2131034115"

.SS "const int MediaPickerSample\&.Resource\&.Id\&.surfacevideoview = 2131034117"

.SS "const int MediaPickerSample\&.Resource\&.Id\&.takePhotoButton = 2131034112"

.SS "const int MediaPickerSample\&.Resource\&.Id\&.takeVideoButton = 2131034113"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
