.TH "MediaPickerSample.App" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MediaPickerSample.App \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMediaPickerSample\&.Application\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBApp\fP ()"
.br
.RI "\fIConstructor for the \fBApplication\fP object\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "PhoneApplicationFrame \fBRootFrame\fP\fC [get, set]\fP"
.br
.RI "\fIProvides easy access to the root frame of the Phone \fBApplication\fP\&. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MediaPickerSample\&.App\&.App ()"

.PP
Constructor for the \fBApplication\fP object\&. 
.SH "Property Documentation"
.PP 
.SS "PhoneApplicationFrame MediaPickerSample\&.App\&.RootFrame\fC [get]\fP, \fC [set]\fP"

.PP
Provides easy access to the root frame of the Phone \fBApplication\fP\&. 
.PP
\fBReturns:\fP
.RS 4
The root frame of the Phone \fBApplication\fP\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
