.TH "MediaPickerSample.MainPageViewModel" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MediaPickerSample.MainPageViewModel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits INotifyPropertyChanged\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainPageViewModel\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBState\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "ICommand \fBTakePhoto\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "ICommand \fBPickPhoto\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "BitmapImage \fBImage\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "PropertyChangedEventHandler \fBPropertyChanged\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MediaPickerSample\&.MainPageViewModel\&.MainPageViewModel ()"

.SH "Property Documentation"
.PP 
.SS "BitmapImage MediaPickerSample\&.MainPageViewModel\&.Image\fC [get]\fP, \fC [set]\fP"

.SS "ICommand MediaPickerSample\&.MainPageViewModel\&.PickPhoto\fC [get]\fP, \fC [set]\fP"

.SS "string MediaPickerSample\&.MainPageViewModel\&.State\fC [get]\fP, \fC [set]\fP"

.SS "ICommand MediaPickerSample\&.MainPageViewModel\&.TakePhoto\fC [get]\fP, \fC [set]\fP"

.SH "Event Documentation"
.PP 
.SS "PropertyChangedEventHandler MediaPickerSample\&.MainPageViewModel\&.PropertyChanged"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
