.TH "MediaLibrarySample.App" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MediaLibrarySample.App \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Application\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBApp\fP ()"
.br
.RI "\fIConstructor for the Application object\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "PhoneApplicationFrame \fBRootFrame\fP\fC [get, set]\fP"
.br
.RI "\fIProvides easy access to the root frame of the Phone Application\&. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MediaLibrarySample\&.App\&.App ()"

.PP
Constructor for the Application object\&. 
.SH "Property Documentation"
.PP 
.SS "PhoneApplicationFrame MediaLibrarySample\&.App\&.RootFrame\fC [get]\fP, \fC [set]\fP"

.PP
Provides easy access to the root frame of the Phone Application\&. 
.PP
\fBReturns:\fP
.RS 4
The root frame of the Phone Application\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
