.TH "MediaPickerSample.Resource" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MediaPickerSample.Resource \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAttribute\fP"
.br
.ti -1c
.RI "class \fBDrawable\fP"
.br
.ti -1c
.RI "class \fBId\fP"
.br
.ti -1c
.RI "class \fBLayout\fP"
.br
.ti -1c
.RI "class \fBString\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBUpdateIdValues\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void MediaPickerSample\&.Resource\&.UpdateIdValues ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
