.TH "MediaPickerSample.MainActivity" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MediaPickerSample.MainActivity \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Activity\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCreate\fP (Bundle bundle)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void MediaPickerSample\&.MainActivity\&.OnCreate (Bundlebundle)\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
