.TH "/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.Tests/Mocks/MockAssignmentService.cs" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.Tests/Mocks/MockAssignmentService.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFieldService\&.Tests\&.Mocks\&.MockAssignmentService\fP"
.br
.RI "\fIThis is just a mock service to bypass the \fBSQLite\fP database for speed during test runs \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBFieldService\&.Tests\&.Mocks\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
