.TH "mono.MonoPackageManager" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mono.MonoPackageManager \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBLoadApplication\fP (Context context, String runtimeDataDir, String[] apks)"
.br
.ti -1c
.RI "static String[] \fBgetAssemblies\fP ()"
.br
.ti -1c
.RI "static String[] \fBgetDependencies\fP ()"
.br
.ti -1c
.RI "static String \fBgetApiPackageName\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static String mono\&.MonoPackageManager\&.getApiPackageName ()\fC [static]\fP"

.SS "static String [] mono\&.MonoPackageManager\&.getAssemblies ()\fC [static]\fP"

.SS "static String [] mono\&.MonoPackageManager\&.getDependencies ()\fC [static]\fP"

.SS "static void mono\&.MonoPackageManager\&.LoadApplication (Contextcontext, StringruntimeDataDir, String[]apks)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
