.TH "mono.com.google.android.maps.ItemizedOverlay_OnFocusChangeListenerImplementor" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mono.com.google.android.maps.ItemizedOverlay_OnFocusChangeListenerImplementor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Object, IGCUserPeer, and OnFocusChangeListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBItemizedOverlay_OnFocusChangeListenerImplementor\fP ()  throws java\&.lang\&.Throwable 	"
.br
.ti -1c
.RI "void \fBonFocusChanged\fP (com\&.google\&.android\&.maps\&.ItemizedOverlay p0, com\&.google\&.android\&.maps\&.OverlayItem p1)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mono\&.com\&.google\&.android\&.maps\&.ItemizedOverlay_OnFocusChangeListenerImplementor\&.ItemizedOverlay_OnFocusChangeListenerImplementor () throws java\&.lang\&.Throwable"

.SH "Member Function Documentation"
.PP 
.SS "void mono\&.com\&.google\&.android\&.maps\&.ItemizedOverlay_OnFocusChangeListenerImplementor\&.monodroidAddReference (java\&.lang\&.Objectobj)"

.SS "void mono\&.com\&.google\&.android\&.maps\&.ItemizedOverlay_OnFocusChangeListenerImplementor\&.monodroidClearReferences ()"

.SS "void mono\&.com\&.google\&.android\&.maps\&.ItemizedOverlay_OnFocusChangeListenerImplementor\&.onFocusChanged (com\&.google\&.android\&.maps\&.ItemizedOverlayp0, com\&.google\&.android\&.maps\&.OverlayItemp1)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
