.TH "/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.Android/obj/Debug/android/src/fieldservice/android/R.java" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bsd-mac/Downloads/Pruebas/prebuilt-apps-master/FieldService/FieldService.Android/obj/Debug/android/src/fieldservice/android/R.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBfieldservice\&.android\&.R\fP"
.br
.ti -1c
.RI "class \fBfieldservice\&.android\&.R\&.attr\fP"
.br
.ti -1c
.RI "class \fBfieldservice\&.android\&.R\&.color\fP"
.br
.ti -1c
.RI "class \fBfieldservice\&.android\&.R\&.drawable\fP"
.br
.ti -1c
.RI "class \fBfieldservice\&.android\&.R\&.id\fP"
.br
.ti -1c
.RI "class \fBfieldservice\&.android\&.R\&.layout\fP"
.br
.ti -1c
.RI "class \fBfieldservice\&.android\&.R\&.menu\fP"
.br
.ti -1c
.RI "class \fBfieldservice\&.android\&.R\&.string\fP"
.br
.ti -1c
.RI "class \fBfieldservice\&.android\&.R\&.style\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBfieldservice\&.android\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
