.TH "Sample.SampleController" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sample.SampleController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIViewController\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSampleController\fP ()"
.br
.ti -1c
.RI "override void \fBLoadView\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Sample\&.SampleController\&.SampleController ()"

.SH "Member Function Documentation"
.PP 
.SS "override void Sample\&.SampleController\&.LoadView ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
