.TH "Sample.Android.Resource.String" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sample.Android.Resource.String \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBapp_name\fP = 2130968576"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const int Sample\&.Android\&.Resource\&.String\&.app_name = 2130968576"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
