.TH "Sample.Android.Activity1" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sample.Android.Activity1 \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Activity\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCreate\fP (Bundle bundle)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void Sample\&.Android\&.Activity1\&.OnCreate (Bundlebundle)\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
