.TH "Sample.Android.Resource.Id" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sample.Android.Resource.Id \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBbtnLoad\fP = 2131034114"
.br
.ti -1c
.RI "const int \fBbtnSave\fP = 2131034113"
.br
.ti -1c
.RI "const int \fBsignatureView\fP = 2131034112"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const int Sample\&.Android\&.Resource\&.Id\&.btnLoad = 2131034114"

.SS "const int Sample\&.Android\&.Resource\&.Id\&.btnSave = 2131034113"

.SS "const int Sample\&.Android\&.Resource\&.Id\&.signatureView = 2131034112"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
