.TH "signaturepad.SignaturePadView" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
signaturepad.SignaturePadView \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits FrameLayout, and IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSignaturePadView\fP (android\&.content\&.Context p0)  throws java\&.lang\&.Throwable 	"
.br
.ti -1c
.RI "\fBSignaturePadView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1)  throws java\&.lang\&.Throwable 	"
.br
.ti -1c
.RI "\fBSignaturePadView\fP (android\&.content\&.Context p0, android\&.util\&.AttributeSet p1, int p2)  throws java\&.lang\&.Throwable 	"
.br
.ti -1c
.RI "boolean \fBonTouchEvent\fP (android\&.view\&.MotionEvent p0)"
.br
.ti -1c
.RI "void \fBonDraw\fP (android\&.graphics\&.Canvas p0)"
.br
.ti -1c
.RI "void \fBonLayout\fP (boolean p0, int p1, int p2, int p3, int p4)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "signaturepad\&.SignaturePadView\&.SignaturePadView (android\&.content\&.Contextp0) throws java\&.lang\&.Throwable"

.SS "signaturepad\&.SignaturePadView\&.SignaturePadView (android\&.content\&.Contextp0, android\&.util\&.AttributeSetp1) throws java\&.lang\&.Throwable"

.SS "signaturepad\&.SignaturePadView\&.SignaturePadView (android\&.content\&.Contextp0, android\&.util\&.AttributeSetp1, intp2) throws java\&.lang\&.Throwable"

.SH "Member Function Documentation"
.PP 
.SS "void signaturepad\&.SignaturePadView\&.monodroidAddReference (java\&.lang\&.Objectobj)"

.SS "void signaturepad\&.SignaturePadView\&.monodroidClearReferences ()"

.SS "void signaturepad\&.SignaturePadView\&.onDraw (android\&.graphics\&.Canvasp0)"

.SS "void signaturepad\&.SignaturePadView\&.onLayout (booleanp0, intp1, intp2, intp3, intp4)"

.SS "boolean signaturepad\&.SignaturePadView\&.onTouchEvent (android\&.view\&.MotionEventp0)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
