.TH "SQLite.iOS.Sample.TaskListsViewController" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLite.iOS.Sample.TaskListsViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits DialogViewController\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTaskListsViewController\fP (\fBSQLiteAsyncConnection\fP connection)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SQLite\&.iOS\&.Sample\&.TaskListsViewController\&.TaskListsViewController (\fBSQLiteAsyncConnection\fPconnection)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
