.TH "SQLite.iOS.Sample.TasksViewController" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLite.iOS.Sample.TasksViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits DialogViewController\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTasksViewController\fP (\fBSQLiteAsyncConnection\fP connection, \fBList\fP list)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SQLite\&.iOS\&.Sample\&.TasksViewController\&.TasksViewController (\fBSQLiteAsyncConnection\fPconnection, \fBList\fPlist)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
