.TH "SQLite.TableMapping.Column" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLite.TableMapping.Column \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColumn\fP (PropertyInfo prop, \fBCreateFlags\fP createFlags=CreateFlags\&.None)"
.br
.ti -1c
.RI "void \fBSetValue\fP (object obj, object val)"
.br
.ti -1c
.RI "object \fBGetValue\fP (object obj)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBPropertyName\fP\fC [get]\fP"
.br
.ti -1c
.RI "Type \fBColumnType\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCollation\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsAutoInc\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsAutoGuid\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsPK\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "IEnumerable< \fBIndexedAttribute\fP > \fBIndices\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsNullable\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBMaxStringLength\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SQLite\&.TableMapping\&.Column\&.Column (PropertyInfoprop, \fBCreateFlags\fPcreateFlags = \fCCreateFlags\&.None\fP)"

.SH "Member Function Documentation"
.PP 
.SS "object SQLite\&.TableMapping\&.Column\&.GetValue (objectobj)"

.SS "void SQLite\&.TableMapping\&.Column\&.SetValue (objectobj, objectval)"

.SH "Property Documentation"
.PP 
.SS "string SQLite\&.TableMapping\&.Column\&.Collation\fC [get]\fP, \fC [set]\fP"

.SS "Type SQLite\&.TableMapping\&.Column\&.ColumnType\fC [get]\fP, \fC [set]\fP"

.SS "IEnumerable<\fBIndexedAttribute\fP> SQLite\&.TableMapping\&.Column\&.Indices\fC [get]\fP, \fC [set]\fP"

.SS "bool SQLite\&.TableMapping\&.Column\&.IsAutoGuid\fC [get]\fP, \fC [set]\fP"

.SS "bool SQLite\&.TableMapping\&.Column\&.IsAutoInc\fC [get]\fP, \fC [set]\fP"

.SS "bool SQLite\&.TableMapping\&.Column\&.IsNullable\fC [get]\fP, \fC [set]\fP"

.SS "bool SQLite\&.TableMapping\&.Column\&.IsPK\fC [get]\fP, \fC [set]\fP"

.SS "int SQLite\&.TableMapping\&.Column\&.MaxStringLength\fC [get]\fP, \fC [set]\fP"

.SS "string SQLite\&.TableMapping\&.Column\&.Name\fC [get]\fP, \fC [set]\fP"

.SS "string SQLite\&.TableMapping\&.Column\&.PropertyName\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
