.TH "SQLite.CollationAttribute" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLite.CollationAttribute \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCollationAttribute\fP (string collation)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBValue\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SQLite\&.CollationAttribute\&.CollationAttribute (stringcollation)"

.SH "Property Documentation"
.PP 
.SS "string SQLite\&.CollationAttribute\&.Value\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
