.TH "SQLite.NotifyTableChangedEventArgs" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLite.NotifyTableChangedEventArgs \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNotifyTableChangedEventArgs\fP (\fBTableMapping\fP table, \fBNotifyTableChangedAction\fP action)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTableMapping\fP \fBTable\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBNotifyTableChangedAction\fP \fBAction\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SQLite\&.NotifyTableChangedEventArgs\&.NotifyTableChangedEventArgs (\fBTableMapping\fPtable, \fBNotifyTableChangedAction\fPaction)"

.SH "Property Documentation"
.PP 
.SS "\fBNotifyTableChangedAction\fP SQLite\&.NotifyTableChangedEventArgs\&.Action\fC [get]\fP, \fC [set]\fP"

.SS "\fBTableMapping\fP SQLite\&.NotifyTableChangedEventArgs\&.Table\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
