.TH "SQLite.iOS.Sample.AppDelegate" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLite.iOS.Sample.AppDelegate \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIApplicationDelegate\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBFinishedLaunching\fP (UIApplication app, NSDictionary options)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBAddActivity\fP ()"
.br
.ti -1c
.RI "static void \fBFinishActivity\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void SQLite\&.iOS\&.Sample\&.AppDelegate\&.AddActivity ()\fC [static]\fP"

.SS "static void SQLite\&.iOS\&.Sample\&.AppDelegate\&.FinishActivity ()\fC [static]\fP"

.SS "override bool SQLite\&.iOS\&.Sample\&.AppDelegate\&.FinishedLaunching (UIApplicationapp, NSDictionaryoptions)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
