.TH "SQLite.NotNullConstraintViolationException" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLite.NotNullConstraintViolationException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSQLite\&.SQLiteException\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static new 
.br
\fBNotNullConstraintViolationException\fP \fBNew\fP (SQLite3\&.Result r, string message)"
.br
.ti -1c
.RI "static 
.br
\fBNotNullConstraintViolationException\fP \fBNew\fP (SQLite3\&.Result r, string message, \fBTableMapping\fP mapping, object obj)"
.br
.ti -1c
.RI "static 
.br
\fBNotNullConstraintViolationException\fP \fBNew\fP (\fBSQLiteException\fP exception, \fBTableMapping\fP mapping, object obj)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBNotNullConstraintViolationException\fP (SQLite3\&.Result r, string message)"
.br
.ti -1c
.RI "\fBNotNullConstraintViolationException\fP (SQLite3\&.Result r, string message, \fBTableMapping\fP mapping, object obj)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IEnumerable< \fBTableMapping\&.Column\fP > \fBColumns\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SQLite\&.NotNullConstraintViolationException\&.NotNullConstraintViolationException (SQLite3\&.Resultr, stringmessage)\fC [protected]\fP"

.SS "SQLite\&.NotNullConstraintViolationException\&.NotNullConstraintViolationException (SQLite3\&.Resultr, stringmessage, \fBTableMapping\fPmapping, objectobj)\fC [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static new \fBNotNullConstraintViolationException\fP SQLite\&.NotNullConstraintViolationException\&.New (SQLite3\&.Resultr, stringmessage)\fC [static]\fP"

.SS "static \fBNotNullConstraintViolationException\fP SQLite\&.NotNullConstraintViolationException\&.New (SQLite3\&.Resultr, stringmessage, \fBTableMapping\fPmapping, objectobj)\fC [static]\fP"

.SS "static \fBNotNullConstraintViolationException\fP SQLite\&.NotNullConstraintViolationException\&.New (\fBSQLiteException\fPexception, \fBTableMapping\fPmapping, objectobj)\fC [static]\fP"

.SH "Property Documentation"
.PP 
.SS "IEnumerable<\fBTableMapping\&.Column\fP> SQLite\&.NotNullConstraintViolationException\&.Columns\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
