.TH "SQLite.SQLiteConnectionWithLock" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLite.SQLiteConnectionWithLock \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSQLite\&.SQLiteConnection\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSQLiteConnectionWithLock\fP (\fBSQLiteConnectionString\fP connectionString, \fBSQLiteOpenFlags\fP openFlags)"
.br
.ti -1c
.RI "IDisposable \fBLock\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SQLite\&.SQLiteConnectionWithLock\&.SQLiteConnectionWithLock (\fBSQLiteConnectionString\fPconnectionString, \fBSQLiteOpenFlags\fPopenFlags)"

.SH "Member Function Documentation"
.PP 
.SS "IDisposable SQLite\&.SQLiteConnectionWithLock\&.Lock ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
