.TH "SQLite.SQLiteException" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLite.SQLiteException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.PP
Inherited by \fBSQLite\&.NotNullConstraintViolationException\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSQLiteException\fP \fBNew\fP (SQLite3\&.Result r, string message)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBSQLiteException\fP (SQLite3\&.Result r, string message)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "SQLite3\&.Result \fBResult\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SQLite\&.SQLiteException\&.SQLiteException (SQLite3\&.Resultr, stringmessage)\fC [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static \fBSQLiteException\fP SQLite\&.SQLiteException\&.New (SQLite3\&.Resultr, stringmessage)\fC [static]\fP"

.SH "Property Documentation"
.PP 
.SS "SQLite3\&.Result SQLite\&.SQLiteException\&.Result\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
