.TH "SQLite.SQLiteConnectionString" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLite.SQLiteConnectionString \- 
.PP
Represents a parsed connection string\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSQLiteConnectionString\fP (string databasePath, bool storeDateTimeAsTicks)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBConnectionString\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDatabasePath\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBStoreDateTimeAsTicks\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a parsed connection string\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "SQLite\&.SQLiteConnectionString\&.SQLiteConnectionString (stringdatabasePath, boolstoreDateTimeAsTicks)"

.SH "Property Documentation"
.PP 
.SS "string SQLite\&.SQLiteConnectionString\&.ConnectionString\fC [get]\fP, \fC [set]\fP"

.SS "string SQLite\&.SQLiteConnectionString\&.DatabasePath\fC [get]\fP, \fC [set]\fP"

.SS "bool SQLite\&.SQLiteConnectionString\&.StoreDateTimeAsTicks\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
