.TH "SQLite.SQLiteConnection.ColumnInfo" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLite.SQLiteConnection.ColumnInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBnotnull\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override string SQLite\&.SQLiteConnection\&.ColumnInfo\&.ToString ()"

.SH "Property Documentation"
.PP 
.SS "string SQLite\&.SQLiteConnection\&.ColumnInfo\&.Name\fC [get]\fP, \fC [set]\fP"

.SS "int SQLite\&.SQLiteConnection\&.ColumnInfo\&.notnull\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
