.TH "SQLite.MaxLengthAttribute" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLite.MaxLengthAttribute \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaxLengthAttribute\fP (int length)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBValue\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SQLite\&.MaxLengthAttribute\&.MaxLengthAttribute (intlength)"

.SH "Property Documentation"
.PP 
.SS "int SQLite\&.MaxLengthAttribute\&.Value\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
