.TH "SQLite.CreateTablesResult" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLite.CreateTablesResult \- 
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "Dictionary< Type, int > \fBResults\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "Dictionary<Type, int> SQLite\&.CreateTablesResult\&.Results\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
