.TH "SQLite.IndexedAttribute" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLite.IndexedAttribute \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute\&.
.PP
Inherited by \fBSQLite\&.UniqueAttribute\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIndexedAttribute\fP ()"
.br
.ti -1c
.RI "\fBIndexedAttribute\fP (string name, int order)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBOrder\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual bool \fBUnique\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SQLite\&.IndexedAttribute\&.IndexedAttribute ()"

.SS "SQLite\&.IndexedAttribute\&.IndexedAttribute (stringname, intorder)"

.SH "Property Documentation"
.PP 
.SS "string SQLite\&.IndexedAttribute\&.Name\fC [get]\fP, \fC [set]\fP"

.SS "int SQLite\&.IndexedAttribute\&.Order\fC [get]\fP, \fC [set]\fP"

.SS "virtual bool SQLite\&.IndexedAttribute\&.Unique\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
