.TH "SQLite.Android.Sample.MainActivity" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLite.Android.Sample.MainActivity \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Activity\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCreateList\fP (string name)"
.br
.ti -1c
.RI "override bool \fBOnCreateOptionsMenu\fP (IMenu menu)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCreate\fP (Bundle bundle)"
.br
.ti -1c
.RI "override void \fBOnSaveInstanceState\fP (Bundle outState)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void SQLite\&.Android\&.Sample\&.MainActivity\&.CreateList (stringname)"

.SS "override void SQLite\&.Android\&.Sample\&.MainActivity\&.OnCreate (Bundlebundle)\fC [protected]\fP"

.SS "override bool SQLite\&.Android\&.Sample\&.MainActivity\&.OnCreateOptionsMenu (IMenumenu)"

.SS "override void SQLite\&.Android\&.Sample\&.MainActivity\&.OnSaveInstanceState (BundleoutState)\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
