.TH "SQLite.Android.Sample.DelegatedMenuItemListener" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLite.Android.Sample.DelegatedMenuItemListener \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Object, and IMenuItemOnMenuItemClickListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDelegatedMenuItemListener\fP (Func< IMenuItem, bool > handler)"
.br
.ti -1c
.RI "bool \fBOnMenuItemClick\fP (IMenuItem item)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SQLite\&.Android\&.Sample\&.DelegatedMenuItemListener\&.DelegatedMenuItemListener (Func< IMenuItem, bool >handler)"

.SH "Member Function Documentation"
.PP 
.SS "bool SQLite\&.Android\&.Sample\&.DelegatedMenuItemListener\&.OnMenuItemClick (IMenuItemitem)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
