.TH "SQLite.Android.Sample.TabListener< T >" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLite.Android.Sample.TabListener< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Object, and ITabListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTabListener\fP (Context listenerContext)"
.br
.ti -1c
.RI "\fBTabListener\fP (Context listenerContext, string tag, T existingFragment=null)"
.br
.ti -1c
.RI "void \fBOnTabReselected\fP (ActionBar\&.Tab tab, FragmentTransaction ft)"
.br
.ti -1c
.RI "void \fBOnTabSelected\fP (ActionBar\&.Tab tab, FragmentTransaction ft)"
.br
.ti -1c
.RI "void \fBOnTabUnselected\fP (ActionBar\&.Tab tab, FragmentTransaction ft)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "T \fBFragment\fP\fC [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SQLite\&.Android\&.Sample\&.TabListener< T >\&.TabListener (ContextlistenerContext)"

.SS "SQLite\&.Android\&.Sample\&.TabListener< T >\&.TabListener (ContextlistenerContext, stringtag, TexistingFragment = \fCnull\fP)"

.SH "Member Function Documentation"
.PP 
.SS "override void SQLite\&.Android\&.Sample\&.TabListener< T >\&.Dispose (booldisposing)\fC [protected]\fP"

.SS "void SQLite\&.Android\&.Sample\&.TabListener< T >\&.OnTabReselected (ActionBar\&.Tabtab, FragmentTransactionft)"

.SS "void SQLite\&.Android\&.Sample\&.TabListener< T >\&.OnTabSelected (ActionBar\&.Tabtab, FragmentTransactionft)"

.SS "void SQLite\&.Android\&.Sample\&.TabListener< T >\&.OnTabUnselected (ActionBar\&.Tabtab, FragmentTransactionft)"

.SH "Property Documentation"
.PP 
.SS "T SQLite\&.Android\&.Sample\&.TabListener< T >\&.Fragment\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
