.TH "xamarin.geolocation.GeolocationSingleListener" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xamarin.geolocation.GeolocationSingleListener \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Object, IGCUserPeer, and LocationListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeolocationSingleListener\fP ()  throws java\&.lang\&.Throwable 	"
.br
.ti -1c
.RI "void \fBonLocationChanged\fP (android\&.location\&.Location p0)"
.br
.ti -1c
.RI "void \fBonProviderDisabled\fP (java\&.lang\&.String p0)"
.br
.ti -1c
.RI "void \fBonProviderEnabled\fP (java\&.lang\&.String p0)"
.br
.ti -1c
.RI "void \fBonStatusChanged\fP (java\&.lang\&.String p0, int p1, android\&.os\&.Bundle p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xamarin\&.geolocation\&.GeolocationSingleListener\&.GeolocationSingleListener () throws java\&.lang\&.Throwable"

.SH "Member Function Documentation"
.PP 
.SS "void xamarin\&.geolocation\&.GeolocationSingleListener\&.monodroidAddReference (java\&.lang\&.Objectobj)"

.SS "void xamarin\&.geolocation\&.GeolocationSingleListener\&.monodroidClearReferences ()"

.SS "void xamarin\&.geolocation\&.GeolocationSingleListener\&.onLocationChanged (android\&.location\&.Locationp0)"

.SS "void xamarin\&.geolocation\&.GeolocationSingleListener\&.onProviderDisabled (java\&.lang\&.Stringp0)"

.SS "void xamarin\&.geolocation\&.GeolocationSingleListener\&.onProviderEnabled (java\&.lang\&.Stringp0)"

.SS "void xamarin\&.geolocation\&.GeolocationSingleListener\&.onStatusChanged (java\&.lang\&.Stringp0, intp1, android\&.os\&.Bundlep2)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
