.TH "xamarin.media.MediaPickerActivity" 3 "Tue Jul 1 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xamarin.media.MediaPickerActivity \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Activity, and IGCUserPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMediaPickerActivity\fP ()  throws java\&.lang\&.Throwable 	"
.br
.ti -1c
.RI "void \fBonSaveInstanceState\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonCreate\fP (android\&.os\&.Bundle p0)"
.br
.ti -1c
.RI "void \fBonActivityResult\fP (int p0, int p1, android\&.content\&.Intent p2)"
.br
.ti -1c
.RI "void \fBmonodroidAddReference\fP (java\&.lang\&.Object obj)"
.br
.ti -1c
.RI "void \fBmonodroidClearReferences\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xamarin\&.media\&.MediaPickerActivity\&.MediaPickerActivity () throws java\&.lang\&.Throwable"

.SH "Member Function Documentation"
.PP 
.SS "void xamarin\&.media\&.MediaPickerActivity\&.monodroidAddReference (java\&.lang\&.Objectobj)"

.SS "void xamarin\&.media\&.MediaPickerActivity\&.monodroidClearReferences ()"

.SS "void xamarin\&.media\&.MediaPickerActivity\&.onActivityResult (intp0, intp1, android\&.content\&.Intentp2)"

.SS "void xamarin\&.media\&.MediaPickerActivity\&.onCreate (android\&.os\&.Bundlep0)"

.SS "void xamarin\&.media\&.MediaPickerActivity\&.onSaveInstanceState (android\&.os\&.Bundlep0)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
