var searchData=
[
  ['activities',['activities',['../namespacefieldservice_1_1android_1_1activities.html',1,'fieldservice.android.activities'],['../namespace_field_service_1_1_android_1_1_activities.html',1,'FieldService.Android.Activities']]],
  ['adapters',['adapters',['../namespacefieldservice_1_1android_1_1adapters.html',1,'fieldservice.android.adapters'],['../namespace_field_service_1_1_android_1_1_adapters.html',1,'FieldService.Android.Adapters']]],
  ['android',['android',['../namespacefieldservice_1_1android.html',1,'fieldservice.android'],['../namespace_field_service_1_1_android.html',1,'FieldService.Android']]],
  ['data',['Data',['../namespace_field_service_1_1_data.html',1,'FieldService']]],
  ['data',['Data',['../namespace_field_service_1_1_tests_1_1_data.html',1,'FieldService::Tests']]],
  ['dialogs',['dialogs',['../namespacefieldservice_1_1android_1_1dialogs.html',1,'fieldservice.android.dialogs'],['../namespace_field_service_1_1_android_1_1_dialogs.html',1,'FieldService.Android.Dialogs']]],
  ['fieldservice',['fieldservice',['../namespacefieldservice.html',1,'fieldservice'],['../namespace_field_service.html',1,'FieldService']]],
  ['fragments',['fragments',['../namespacefieldservice_1_1android_1_1fragments.html',1,'fieldservice.android.fragments'],['../namespace_field_service_1_1_android_1_1_fragments.html',1,'FieldService.Android.Fragments']]],
  ['ios',['iOS',['../namespace_field_service_1_1i_o_s.html',1,'FieldService']]],
  ['mocks',['Mocks',['../namespace_field_service_1_1_tests_1_1_mocks.html',1,'FieldService::Tests']]],
  ['tests',['Tests',['../namespace_field_service_1_1_tests.html',1,'FieldService']]],
  ['utilities',['Utilities',['../namespace_field_service_1_1_utilities.html',1,'FieldService']]],
  ['utilities',['Utilities',['../namespace_field_service_1_1_win_r_t_1_1_utilities.html',1,'FieldService::WinRT']]],
  ['utilities',['Utilities',['../namespace_field_service_1_1_android_1_1_utilities.html',1,'FieldService.Android.Utilities'],['../namespacefieldservice_1_1android_1_1utilities.html',1,'fieldservice.android.utilities']]],
  ['viewmodels',['ViewModels',['../namespace_field_service_1_1_view_models.html',1,'FieldService']]],
  ['viewmodels',['ViewModels',['../namespace_field_service_1_1_win_r_t_1_1_view_models.html',1,'FieldService::WinRT']]],
  ['viewmodels',['ViewModels',['../namespace_field_service_1_1_tests_1_1_view_models.html',1,'FieldService::Tests']]],
  ['views',['Views',['../namespace_field_service_1_1_win_r_t_1_1_views.html',1,'FieldService::WinRT']]],
  ['winrt',['WinRT',['../namespace_field_service_1_1_win_r_t.html',1,'FieldService']]]
];
